/*
 * Copyright (C) 2012, Freescale Semiconductor, Inc. All Rights Reserved
 * THIS SOURCE CODE IS CONFIDENTIAL AND PROPRIETARY AND MAY NOT
 * BE USED OR DISTRIBUTED WITHOUT THE WRITTEN PERMISSION OF
 * Freescale Semiconductor, Inc.
*/

// File: usb_iomux_config.c

/* ------------------------------------------------------------------------------
 * <auto-generated>
 *     This code was generated by a tool.
 *     Runtime Version:3.3.2.1
 *
 *     Changes to this file may cause incorrect behavior and will be lost if
 *     the code is regenerated.
 * </auto-generated>
 * ------------------------------------------------------------------------------
*/

#include "iomux_config.h"
#include "iomux_define.h"
#include "registers/regsiomuxc.h"

// Function to configure IOMUXC for usb module.
void usb_iomux_config(void)
{
    // Config usb.USB_OTG1_ID to pad REF_CLK_32K(AD14)
    // HW_IOMUXC_SW_MUX_CTL_PAD_REF_CLK_32K_WR(0x00000003);
    // HW_IOMUXC_ANALOG_USB_OTG_ID_SELECT_INPUT_WR(0x00000003);
    // HW_IOMUXC_SW_PAD_CTL_PAD_REF_CLK_32K_WR(0x000110B0);
    // Mux Register:
    // IOMUXC_SW_MUX_CTL_PAD_REF_CLK_32K(0x020E0228)
    //   SION [4] - Software Input On Field Reset: SION_DISABLED
    //              Force the selected mux mode Input path no matter of MUX_MODE functionality.
    //     SION_DISABLED (0) - Input Path is determined by functionality of the selected mux mode (regular).
    //     SION_ENABLED (1) - Force input path of pad REF_CLK_32K.
    //   MUX_MODE [2:0] - MUX Mode Select Field Reset: ALT5
    //                    Select 1 of 8 iomux modes to be used for pad: REF_CLK_32K.
    //     ALT1 (1) - Select mux mode: ALT1 mux port: SDA of instance: i2c3.
    //                NOTE: - Config Register IOMUXC_I2C3_IPP_SDA_IN_SELECT_INPUT for mode ALT1.
    //     ALT2 (2) - Select mux mode: ALT2 mux port: PWMO of instance: pwm4.
    //     ALT3 (3) - Select mux mode: ALT3 mux port: USB_OTG1_ID of instance: usb.
    //                NOTE: - Config Register IOMUXC_ANALOG_USB_OTG_ID_SELECT_INPUT for mode ALT3.
    //     ALT4 (4) - Select mux mode: ALT4 mux port: LCTL of instance: usdhc1.
    //     ALT5 (5) - Select mux mode: ALT5 mux port: GPIO[22] of instance: gpio3.
    //     ALT6 (6) - Select mux mode: ALT6 mux port: CD of instance: usdhc3.
    //                NOTE: - Config Register IOMUXC_USDHC3_IPP_CARD_DET_SELECT_INPUT for mode ALT6.
    HW_IOMUXC_SW_MUX_CTL_PAD_REF_CLK_32K_WR(
            BF_IOMUXC_SW_MUX_CTL_PAD_REF_CLK_32K_SION(SION_DISABLED) | 
            BF_IOMUXC_SW_MUX_CTL_PAD_REF_CLK_32K_MUX_MODE(ALT3));
    // Pad REF_CLK_32K is involved in Daisy Chain.
    // Input Select Register:
    // IOMUXC_ANALOG_USB_OTG_ID_SELECT_INPUT(0x020E05DC)
    //   DAISY [2:0] Reset: SEL_EPDC_PWRCOM_ALT4
    //                 Selecting Pads Involved in Daisy Chain.
    //                 NOTE: Instance: usb,   In Pin: usb_otg_id
    //     SEL_EPDC_PWRCOM_ALT4 (0) - Selecting Pad: EPDC_PWRCOM for Mode: ALT4.
    //     SEL_FEC_RXD0_ALT2 (1) - Selecting Pad: FEC_RXD0 for Mode: ALT2.
    //     SEL_LCD_DAT1_ALT2 (2) - Selecting Pad: LCD_DAT1 for Mode: ALT2.
    //     SEL_REF_CLK_32K_ALT3 (3) - Selecting Pad: REF_CLK_32K for Mode: ALT3.
    //     SEL_SD3_DAT0_ALT4 (4) - Selecting Pad: SD3_DAT0 for Mode: ALT4.
    HW_IOMUXC_ANALOG_USB_OTG_ID_SELECT_INPUT_WR(
            BF_IOMUXC_ANALOG_USB_OTG_ID_SELECT_INPUT_DAISY(SEL_REF_CLK_32K_ALT3));
    // Pad Control Register:
    // IOMUXC_SW_PAD_CTL_PAD_REF_CLK_32K(0x020E0530)
    //   LVE [22] - Low Voltage Enable Field Reset: LVE_DISABLED
    //              Select one out of next values for pad: REF_CLK_32K.
    //     LVE_DISABLED (0) - High Voltage
    //     LVE_ENABLED (1) - Low Voltage
    //   HYS [16] - Hysteresis Enable Field Reset: HYS_ENABLED
    //              Select one out of next values for pad: REF_CLK_32K.
    //     HYS_DISABLED (0) - Hysteresis Disabled
    //     HYS_ENABLED (1) - Hysteresis Enabled
    //   PUS [15:14] - Pull Up / Down Configure Field Reset: PUS_100KOHM_PD
    //                 Select one out of next values for pad: REF_CLK_32K.
    //     PUS_100KOHM_PD (0) - 100K Ohm Pull Down
    //     PUS_47KOHM_PU (1) - 47K Ohm Pull Up
    //     PUS_100KOHM_PU (2) - 100K Ohm Pull Up
    //     PUS_22KOHM_PU (3) - 22K Ohm Pull Up
    //   PUE [13] - Pull / Keep Select Field Reset: PUE_KEEP
    //              Select one out of next values for pad: REF_CLK_32K.
    //     PUE_KEEP (0) - Keeper
    //     PUE_PULL (1) - Pull
    //   PKE [12] - Pull / Keep Enable Field Reset: PKE_ENABLED
    //              Select one out of next values for pad: REF_CLK_32K.
    //     PKE_DISABLED (0) - Pull/Keeper Disabled
    //     PKE_ENABLED (1) - Pull/Keeper Enabled
    //   ODE [11] - Open Drain Enable Field Reset: ODE_DISABLED
    //              Select one out of next values for pad: REF_CLK_32K.
    //     ODE_DISABLED (0) - Open Drain Disabled
    //     ODE_ENABLED (1) - Open Drain Enabled
    //   SPEED [7:6] - Speed Field Reset: SPD_100MHZ
    //                 Select one out of next values for pad: REF_CLK_32K.
    //     SPD_TBD (0) - TBD
    //     SPD_50MHZ (1) - Low(50 MHz)
    //     SPD_100MHZ (2) - Medium(100 MHz)
    //     SPD_200MHZ (3) - Maximum(200 MHz)
    //   DSE [5:3] - Drive Strength Field Reset: DSE_40OHM
    //               Select one out of next values for pad: REF_CLK_32K.
    //     DSE_DISABLED (0) - Output driver disabled.
    //     DSE_240OHM (1) - 240 Ohm
    //     DSE_120OHM (2) - 120 Ohm
    //     DSE_80OHM (3) - 80 Ohm
    //     DSE_60OHM (4) - 60 Ohm
    //     DSE_48OHM (5) - 48 Ohm
    //     DSE_40OHM (6) - 40 Ohm
    //     DSE_34OHM (7) - 34 Ohm
    //   SRE [0] - Slew Rate Field Reset: SRE_SLOW
    //             Select one out of next values for pad: REF_CLK_32K.
    //     SRE_SLOW (0) - Slow Slew Rate
    //     SRE_FAST (1) - Fast Slew Rate
    HW_IOMUXC_SW_PAD_CTL_PAD_REF_CLK_32K_WR(
            BF_IOMUXC_SW_PAD_CTL_PAD_REF_CLK_32K_LVE(LVE_DISABLED) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_REF_CLK_32K_HYS(HYS_ENABLED) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_REF_CLK_32K_PUS(PUS_100KOHM_PD) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_REF_CLK_32K_PUE(PUE_KEEP) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_REF_CLK_32K_PKE(PKE_ENABLED) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_REF_CLK_32K_ODE(ODE_DISABLED) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_REF_CLK_32K_SPEED(SPD_100MHZ) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_REF_CLK_32K_DSE(DSE_40OHM) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_REF_CLK_32K_SRE(SRE_SLOW));

    // Config usb.USB_OTG1_PWR to pad KEY_COL4(E20)
    // HW_IOMUXC_SW_MUX_CTL_PAD_KEY_COL4_WR(0x00000006);
    // HW_IOMUXC_SW_PAD_CTL_PAD_KEY_COL4_WR(0x000110B0);
    // Mux Register:
    // IOMUXC_SW_MUX_CTL_PAD_KEY_COL4(0x020E017C)
    //   SION [4] - Software Input On Field Reset: SION_DISABLED
    //              Force the selected mux mode Input path no matter of MUX_MODE functionality.
    //     SION_DISABLED (0) - Input Path is determined by functionality of the selected mux mode (regular).
    //     SION_ENABLED (1) - Force input path of pad KEY_COL4.
    //   MUX_MODE [2:0] - MUX Mode Select Field Reset: ALT5
    //                    Select 1 of 8 iomux modes to be used for pad: KEY_COL4.
    //     ALT0 (0) - Select mux mode: ALT0 mux port: COL[4] of instance: kpp.
    //                NOTE: - Config Register IOMUXC_KPP_IPP_IND_COL_4_SELECT_INPUT for mode ALT0.
    //     ALT1 (1) - Select mux mode: ALT1 mux port: AUD6_RXD of instance: audmux.
    //                NOTE: - Config Register IOMUXC_AUDMUX_P6_INPUT_DA_AMX_SELECT_INPUT for mode ALT1.
    //     ALT2 (2) - Select mux mode: ALT2 mux port: DAT[8] of instance: lcdif.
    //                NOTE: - Config Register IOMUXC_LCDIF_LCDIF_RXDATA_8_SELECT_INPUT for mode ALT2.
    //     ALT3 (3) - Select mux mode: ALT3 mux port: WEIM_DA_A[8] of instance: weim.
    //     ALT4 (4) - Select mux mode: ALT4 mux port: CLK of instance: usdhc4.
    //                NOTE: - Config Register IOMUXC_USDHC4_IPP_CARD_CLK_IN_SELECT_INPUT for mode ALT4.
    //     ALT5 (5) - Select mux mode: ALT5 mux port: GPIO[0] of instance: gpio4.
    //     ALT6 (6) - Select mux mode: ALT6 mux port: USB_OTG1_PWR of instance: usb.
    HW_IOMUXC_SW_MUX_CTL_PAD_KEY_COL4_WR(
            BF_IOMUXC_SW_MUX_CTL_PAD_KEY_COL4_SION(SION_DISABLED) | 
            BF_IOMUXC_SW_MUX_CTL_PAD_KEY_COL4_MUX_MODE(ALT6));
    // Pad Control Register:
    // IOMUXC_SW_PAD_CTL_PAD_KEY_COL4(0x020E0484)
    //   LVE [22] - Low Voltage Enable Field Reset: LVE_DISABLED
    //              Select one out of next values for pad: KEY_COL4.
    //     LVE_DISABLED (0) - High Voltage
    //     LVE_ENABLED (1) - Low Voltage
    //   HYS [16] - Hysteresis Enable Field Reset: HYS_ENABLED
    //              Select one out of next values for pad: KEY_COL4.
    //     HYS_DISABLED (0) - Hysteresis Disabled
    //     HYS_ENABLED (1) - Hysteresis Enabled
    //   PUS [15:14] - Pull Up / Down Configure Field Reset: PUS_100KOHM_PD
    //                 Select one out of next values for pad: KEY_COL4.
    //     PUS_100KOHM_PD (0) - 100K Ohm Pull Down
    //     PUS_47KOHM_PU (1) - 47K Ohm Pull Up
    //     PUS_100KOHM_PU (2) - 100K Ohm Pull Up
    //     PUS_22KOHM_PU (3) - 22K Ohm Pull Up
    //   PUE [13] - Pull / Keep Select Field Reset: PUE_KEEP
    //              Select one out of next values for pad: KEY_COL4.
    //     PUE_KEEP (0) - Keeper
    //     PUE_PULL (1) - Pull
    //   PKE [12] - Pull / Keep Enable Field Reset: PKE_ENABLED
    //              Select one out of next values for pad: KEY_COL4.
    //     PKE_DISABLED (0) - Pull/Keeper Disabled
    //     PKE_ENABLED (1) - Pull/Keeper Enabled
    //   ODE [11] - Open Drain Enable Field Reset: ODE_DISABLED
    //              Select one out of next values for pad: KEY_COL4.
    //     ODE_DISABLED (0) - Open Drain Disabled
    //     ODE_ENABLED (1) - Open Drain Enabled
    //   SPEED [7:6] - Speed Field Reset: SPD_100MHZ
    //                 Select one out of next values for pad: KEY_COL4.
    //     SPD_TBD (0) - TBD
    //     SPD_50MHZ (1) - Low(50 MHz)
    //     SPD_100MHZ (2) - Medium(100 MHz)
    //     SPD_200MHZ (3) - Maximum(200 MHz)
    //   DSE [5:3] - Drive Strength Field Reset: DSE_40OHM
    //               Select one out of next values for pad: KEY_COL4.
    //     DSE_DISABLED (0) - Output driver disabled.
    //     DSE_240OHM (1) - 240 Ohm
    //     DSE_120OHM (2) - 120 Ohm
    //     DSE_80OHM (3) - 80 Ohm
    //     DSE_60OHM (4) - 60 Ohm
    //     DSE_48OHM (5) - 48 Ohm
    //     DSE_40OHM (6) - 40 Ohm
    //     DSE_34OHM (7) - 34 Ohm
    //   SRE [0] - Slew Rate Field Reset: SRE_SLOW
    //             Select one out of next values for pad: KEY_COL4.
    //     SRE_SLOW (0) - Slow Slew Rate
    //     SRE_FAST (1) - Fast Slew Rate
    HW_IOMUXC_SW_PAD_CTL_PAD_KEY_COL4_WR(
            BF_IOMUXC_SW_PAD_CTL_PAD_KEY_COL4_LVE(LVE_DISABLED) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_KEY_COL4_HYS(HYS_ENABLED) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_KEY_COL4_PUS(PUS_100KOHM_PD) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_KEY_COL4_PUE(PUE_KEEP) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_KEY_COL4_PKE(PKE_ENABLED) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_KEY_COL4_ODE(ODE_DISABLED) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_KEY_COL4_SPEED(SPD_100MHZ) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_KEY_COL4_DSE(DSE_40OHM) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_KEY_COL4_SRE(SRE_SLOW));

    // Config usb.USB_OTG2_ID to pad REF_CLK_24M(AC14)
    // HW_IOMUXC_SW_MUX_CTL_PAD_REF_CLK_24M_WR(0x00000003);
    // HW_IOMUXC_ANALOG_USB_UH1_ID_SELECT_INPUT_WR(0x00000002);
    // HW_IOMUXC_SW_PAD_CTL_PAD_REF_CLK_24M_WR(0x000110B0);
    // Mux Register:
    // IOMUXC_SW_MUX_CTL_PAD_REF_CLK_24M(0x020E0224)
    //   SION [4] - Software Input On Field Reset: SION_DISABLED
    //              Force the selected mux mode Input path no matter of MUX_MODE functionality.
    //     SION_DISABLED (0) - Input Path is determined by functionality of the selected mux mode (regular).
    //     SION_ENABLED (1) - Force input path of pad REF_CLK_24M.
    //   MUX_MODE [2:0] - MUX Mode Select Field Reset: ALT5
    //                    Select 1 of 8 iomux modes to be used for pad: REF_CLK_24M.
    //     ALT1 (1) - Select mux mode: ALT1 mux port: SCL of instance: i2c3.
    //                NOTE: - Config Register IOMUXC_I2C3_IPP_SCL_IN_SELECT_INPUT for mode ALT1.
    //     ALT2 (2) - Select mux mode: ALT2 mux port: PWMO of instance: pwm3.
    //     ALT3 (3) - Select mux mode: ALT3 mux port: USB_OTG2_ID of instance: usb.
    //                NOTE: - Config Register IOMUXC_ANALOG_USB_UH1_ID_SELECT_INPUT for mode ALT3.
    //     ALT4 (4) - Select mux mode: ALT4 mux port: PMIC_RDY of instance: ccm.
    //                NOTE: - Config Register IOMUXC_CCM_PMIC_VFUNCIONAL_READY_SELECT_INPUT for mode ALT4.
    //     ALT5 (5) - Select mux mode: ALT5 mux port: GPIO[21] of instance: gpio3.
    //     ALT6 (6) - Select mux mode: ALT6 mux port: WP of instance: usdhc3.
    //                NOTE: - Config Register IOMUXC_USDHC3_IPP_WP_ON_SELECT_INPUT for mode ALT6.
    HW_IOMUXC_SW_MUX_CTL_PAD_REF_CLK_24M_WR(
            BF_IOMUXC_SW_MUX_CTL_PAD_REF_CLK_24M_SION(SION_DISABLED) | 
            BF_IOMUXC_SW_MUX_CTL_PAD_REF_CLK_24M_MUX_MODE(ALT3));
    // Pad REF_CLK_24M is involved in Daisy Chain.
    // Input Select Register:
    // IOMUXC_ANALOG_USB_UH1_ID_SELECT_INPUT(0x020E05E0)
    //   DAISY [1:0] Reset: SEL_EPDC_PWRINT_ALT4
    //                 Selecting Pads Involved in Daisy Chain.
    //                 NOTE: Instance: usb,   In Pin: usb_uh1_id
    //     SEL_EPDC_PWRINT_ALT4 (0) - Selecting Pad: EPDC_PWRINT for Mode: ALT4.
    //     SEL_LCD_DAT0_ALT2 (1) - Selecting Pad: LCD_DAT0 for Mode: ALT2.
    //     SEL_REF_CLK_24M_ALT3 (2) - Selecting Pad: REF_CLK_24M for Mode: ALT3.
    //     SEL_SD3_CMD_ALT4 (3) - Selecting Pad: SD3_CMD for Mode: ALT4.
    HW_IOMUXC_ANALOG_USB_UH1_ID_SELECT_INPUT_WR(
            BF_IOMUXC_ANALOG_USB_UH1_ID_SELECT_INPUT_DAISY(SEL_REF_CLK_24M_ALT3));
    // Pad Control Register:
    // IOMUXC_SW_PAD_CTL_PAD_REF_CLK_24M(0x020E052C)
    //   LVE [22] - Low Voltage Enable Field Reset: LVE_DISABLED
    //              Select one out of next values for pad: REF_CLK_24M.
    //     LVE_DISABLED (0) - High Voltage
    //     LVE_ENABLED (1) - Low Voltage
    //   HYS [16] - Hysteresis Enable Field Reset: HYS_ENABLED
    //              Select one out of next values for pad: REF_CLK_24M.
    //     HYS_DISABLED (0) - Hysteresis Disabled
    //     HYS_ENABLED (1) - Hysteresis Enabled
    //   PUS [15:14] - Pull Up / Down Configure Field Reset: PUS_100KOHM_PD
    //                 Select one out of next values for pad: REF_CLK_24M.
    //     PUS_100KOHM_PD (0) - 100K Ohm Pull Down
    //     PUS_47KOHM_PU (1) - 47K Ohm Pull Up
    //     PUS_100KOHM_PU (2) - 100K Ohm Pull Up
    //     PUS_22KOHM_PU (3) - 22K Ohm Pull Up
    //   PUE [13] - Pull / Keep Select Field Reset: PUE_KEEP
    //              Select one out of next values for pad: REF_CLK_24M.
    //     PUE_KEEP (0) - Keeper
    //     PUE_PULL (1) - Pull
    //   PKE [12] - Pull / Keep Enable Field Reset: PKE_ENABLED
    //              Select one out of next values for pad: REF_CLK_24M.
    //     PKE_DISABLED (0) - Pull/Keeper Disabled
    //     PKE_ENABLED (1) - Pull/Keeper Enabled
    //   ODE [11] - Open Drain Enable Field Reset: ODE_DISABLED
    //              Select one out of next values for pad: REF_CLK_24M.
    //     ODE_DISABLED (0) - Open Drain Disabled
    //     ODE_ENABLED (1) - Open Drain Enabled
    //   SPEED [7:6] - Speed Field Reset: SPD_100MHZ
    //                 Select one out of next values for pad: REF_CLK_24M.
    //     SPD_TBD (0) - TBD
    //     SPD_50MHZ (1) - Low(50 MHz)
    //     SPD_100MHZ (2) - Medium(100 MHz)
    //     SPD_200MHZ (3) - Maximum(200 MHz)
    //   DSE [5:3] - Drive Strength Field Reset: DSE_40OHM
    //               Select one out of next values for pad: REF_CLK_24M.
    //     DSE_DISABLED (0) - Output driver disabled.
    //     DSE_240OHM (1) - 240 Ohm
    //     DSE_120OHM (2) - 120 Ohm
    //     DSE_80OHM (3) - 80 Ohm
    //     DSE_60OHM (4) - 60 Ohm
    //     DSE_48OHM (5) - 48 Ohm
    //     DSE_40OHM (6) - 40 Ohm
    //     DSE_34OHM (7) - 34 Ohm
    //   SRE [0] - Slew Rate Field Reset: SRE_SLOW
    //             Select one out of next values for pad: REF_CLK_24M.
    //     SRE_SLOW (0) - Slow Slew Rate
    //     SRE_FAST (1) - Fast Slew Rate
    HW_IOMUXC_SW_PAD_CTL_PAD_REF_CLK_24M_WR(
            BF_IOMUXC_SW_PAD_CTL_PAD_REF_CLK_24M_LVE(LVE_DISABLED) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_REF_CLK_24M_HYS(HYS_ENABLED) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_REF_CLK_24M_PUS(PUS_100KOHM_PD) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_REF_CLK_24M_PUE(PUE_KEEP) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_REF_CLK_24M_PKE(PKE_ENABLED) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_REF_CLK_24M_ODE(ODE_DISABLED) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_REF_CLK_24M_SPEED(SPD_100MHZ) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_REF_CLK_24M_DSE(DSE_40OHM) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_REF_CLK_24M_SRE(SRE_SLOW));

    // Config usb.USB_OTG2_PWR to pad KEY_COL5(D24)
    // HW_IOMUXC_SW_MUX_CTL_PAD_KEY_COL5_WR(0x00000006);
    // HW_IOMUXC_SW_PAD_CTL_PAD_KEY_COL5_WR(0x000110B0);
    // Mux Register:
    // IOMUXC_SW_MUX_CTL_PAD_KEY_COL5(0x020E0180)
    //   SION [4] - Software Input On Field Reset: SION_DISABLED
    //              Force the selected mux mode Input path no matter of MUX_MODE functionality.
    //     SION_DISABLED (0) - Input Path is determined by functionality of the selected mux mode (regular).
    //     SION_ENABLED (1) - Force input path of pad KEY_COL5.
    //   MUX_MODE [2:0] - MUX Mode Select Field Reset: ALT5
    //                    Select 1 of 8 iomux modes to be used for pad: KEY_COL5.
    //     ALT0 (0) - Select mux mode: ALT0 mux port: COL[5] of instance: kpp.
    //                NOTE: - Config Register IOMUXC_KPP_IPP_IND_COL_5_SELECT_INPUT for mode ALT0.
    //     ALT1 (1) - Select mux mode: ALT1 mux port: AUD6_TXFS of instance: audmux.
    //                NOTE: - Config Register IOMUXC_AUDMUX_P6_INPUT_TXFS_AMX_SELECT_INPUT for mode ALT1.
    //     ALT2 (2) - Select mux mode: ALT2 mux port: DAT[10] of instance: lcdif.
    //                NOTE: - Config Register IOMUXC_LCDIF_LCDIF_RXDATA_10_SELECT_INPUT for mode ALT2.
    //     ALT3 (3) - Select mux mode: ALT3 mux port: WEIM_DA_A[10] of instance: weim.
    //     ALT4 (4) - Select mux mode: ALT4 mux port: DAT0 of instance: usdhc4.
    //                NOTE: - Config Register IOMUXC_USDHC4_IPP_DAT0_IN_SELECT_INPUT for mode ALT4.
    //     ALT5 (5) - Select mux mode: ALT5 mux port: GPIO[2] of instance: gpio4.
    //     ALT6 (6) - Select mux mode: ALT6 mux port: USB_OTG2_PWR of instance: usb.
    HW_IOMUXC_SW_MUX_CTL_PAD_KEY_COL5_WR(
            BF_IOMUXC_SW_MUX_CTL_PAD_KEY_COL5_SION(SION_DISABLED) | 
            BF_IOMUXC_SW_MUX_CTL_PAD_KEY_COL5_MUX_MODE(ALT6));
    // Pad Control Register:
    // IOMUXC_SW_PAD_CTL_PAD_KEY_COL5(0x020E0488)
    //   LVE [22] - Low Voltage Enable Field Reset: LVE_DISABLED
    //              Select one out of next values for pad: KEY_COL5.
    //     LVE_DISABLED (0) - High Voltage
    //     LVE_ENABLED (1) - Low Voltage
    //   HYS [16] - Hysteresis Enable Field Reset: HYS_ENABLED
    //              Select one out of next values for pad: KEY_COL5.
    //     HYS_DISABLED (0) - Hysteresis Disabled
    //     HYS_ENABLED (1) - Hysteresis Enabled
    //   PUS [15:14] - Pull Up / Down Configure Field Reset: PUS_100KOHM_PD
    //                 Select one out of next values for pad: KEY_COL5.
    //     PUS_100KOHM_PD (0) - 100K Ohm Pull Down
    //     PUS_47KOHM_PU (1) - 47K Ohm Pull Up
    //     PUS_100KOHM_PU (2) - 100K Ohm Pull Up
    //     PUS_22KOHM_PU (3) - 22K Ohm Pull Up
    //   PUE [13] - Pull / Keep Select Field Reset: PUE_KEEP
    //              Select one out of next values for pad: KEY_COL5.
    //     PUE_KEEP (0) - Keeper
    //     PUE_PULL (1) - Pull
    //   PKE [12] - Pull / Keep Enable Field Reset: PKE_ENABLED
    //              Select one out of next values for pad: KEY_COL5.
    //     PKE_DISABLED (0) - Pull/Keeper Disabled
    //     PKE_ENABLED (1) - Pull/Keeper Enabled
    //   ODE [11] - Open Drain Enable Field Reset: ODE_DISABLED
    //              Select one out of next values for pad: KEY_COL5.
    //     ODE_DISABLED (0) - Open Drain Disabled
    //     ODE_ENABLED (1) - Open Drain Enabled
    //   SPEED [7:6] - Speed Field Reset: SPD_100MHZ
    //                 Select one out of next values for pad: KEY_COL5.
    //     SPD_TBD (0) - TBD
    //     SPD_50MHZ (1) - Low(50 MHz)
    //     SPD_100MHZ (2) - Medium(100 MHz)
    //     SPD_200MHZ (3) - Maximum(200 MHz)
    //   DSE [5:3] - Drive Strength Field Reset: DSE_40OHM
    //               Select one out of next values for pad: KEY_COL5.
    //     DSE_DISABLED (0) - Output driver disabled.
    //     DSE_240OHM (1) - 240 Ohm
    //     DSE_120OHM (2) - 120 Ohm
    //     DSE_80OHM (3) - 80 Ohm
    //     DSE_60OHM (4) - 60 Ohm
    //     DSE_48OHM (5) - 48 Ohm
    //     DSE_40OHM (6) - 40 Ohm
    //     DSE_34OHM (7) - 34 Ohm
    //   SRE [0] - Slew Rate Field Reset: SRE_SLOW
    //             Select one out of next values for pad: KEY_COL5.
    //     SRE_SLOW (0) - Slow Slew Rate
    //     SRE_FAST (1) - Fast Slew Rate
    HW_IOMUXC_SW_PAD_CTL_PAD_KEY_COL5_WR(
            BF_IOMUXC_SW_PAD_CTL_PAD_KEY_COL5_LVE(LVE_DISABLED) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_KEY_COL5_HYS(HYS_ENABLED) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_KEY_COL5_PUS(PUS_100KOHM_PD) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_KEY_COL5_PUE(PUE_KEEP) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_KEY_COL5_PKE(PKE_ENABLED) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_KEY_COL5_ODE(ODE_DISABLED) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_KEY_COL5_SPEED(SPD_100MHZ) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_KEY_COL5_DSE(DSE_40OHM) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_KEY_COL5_SRE(SRE_SLOW));
}
