include $(SDK_ROOT)/mk/common.mk


# Specify the lib to which these sources will be added.
#TARGET_LIB_NAME = libsdk.a

# Specify sources files to compile.
C_SOURCES = spinlock.c system_util.c text_color.c version.c

ASM_SOURCES = atomics.s



include $(SDK_ROOT)/mk/targets.mk
