/*
 * Copyright (C) 2011-2012, Freescale Semiconductor, Inc. All Rights Reserved
 * THIS SOURCE CODE IS CONFIDENTIAL AND PROPRIETARY AND MAY NOT
 * BE USED OR DISTRIBUTED WITHOUT THE WRITTEN PERMISSION OF
 * Freescale Semiconductor, Inc.
*/

#ifndef _PCIE_PHY_REGS_H_
#define _PCIE_PHY_REGS_H_

#define SSP_CR_SUP_DIG_IDCODE_LO 0x0000
// FIELD: IDCODE_LO [15:0]

#define SSP_CR_SUP_DIG_IDCODE_HI 0x0001
// FIELD: IDCODE_HI [15:0]

#define SSP_CR_SUP_DIG_DEBUG 0x0002
// FIELD: DTB_SEL [6:5]
// FIELD: TX_VREF_SEL [4:0]

#define SSP_CR_SUP_DIG_SS_PHASE 0x0005
// FIELD: REF_SEL_DIV [15:13]
// FIELD: PH_SEL [12:12]
// FIELD: ZERO_FREQ [11:11]
// FIELD: VAL [10:2]
// FIELD: DTHR [1:0]

#define SSP_CR_SUP_DIG_SS_FREQ 0x0006
// FIELD: FREQ_OVRD [14:14]
// FIELD: FREQ_PK [13:7]
// FIELD: FREQ_CNT_INIT [6:0]

#define SSP_CR_SUP_DIG_ATEOVRD 0x0010
// FIELD: ateovrd_en [2:2]
// FIELD: ref_usb2_en [1:1]
// FIELD: ref_clkdiv2 [0:0]

#define SSP_CR_SUP_DIG_MPLL_OVRD_IN_LO 0x0011
// FIELD: RES_ACK_IN_OVRD [15:15]
// FIELD: RES_ACK_IN [14:14]
// FIELD: RES_REQ_IN_OVRD [13:13]
// FIELD: RES_REQ_IN [12:12]
// FIELD: RTUNE_REQ_OVRD [11:11]
// FIELD: RTUNE_REQ [10:10]
// FIELD: MPLL_MULTIPLIER_OVRD [9:9]
// FIELD: MPLL_MULTIPLIER [8:2]
// FIELD: MPLL_EN_OVRD [1:1]
// FIELD: MPLL_EN [0:0]

#define SSP_CR_SUP_DIG_MPLL_OVRD_IN_HI 0x0012
// FIELD: MPLL_RST [10:10]
// FIELD: FSEL_OVRD [9:9]
// FIELD: FSEL [8:6]
// FIELD: MPLL_WORD_CLK_EN_OVRD [5:5]
// FIELD: MPLL_WORD_CLK_EN [4:4]
// FIELD: MPLL_DWORD_CLK_EN_OVRD [3:3]
// FIELD: MPLL_DWORD_CLK_EN [2:2]
// FIELD: MPLL_QWORD_CLK_EN_OVRD [1:1]
// FIELD: MPLL_QWORD_CLK_EN [0:0]

#define SSP_CR_SUP_DIG_SSC_OVRD_IN 0x0013
// FIELD: SSC_OVRD_IN_EN [11:11]
// FIELD: SSC_EN [10:10]
// FIELD: SSC_RANGE [9:8]
// FIELD: SSC_REF_CLK_SEL [7:0]

#define SSP_CR_SUP_DIG_BS_OVRD_IN 0x0014
// FIELD: EN [11:11]
// FIELD: INVERT [10:10]
// FIELD: INIT [9:9]
// FIELD: HIGHZ [8:8]
// FIELD: CLAMP [7:7]
// FIELD: EXTEST_AC [6:6]
// FIELD: EXTEST [5:5]
// FIELD: PRELOAD [4:4]
// FIELD: UPDATE_DR [3:3]
// FIELD: CAPTURE_DR [2:2]
// FIELD: SHIFT_DR [1:1]
// FIELD: IN [0:0]

#define SSP_CR_SUP_DIG_LEVEL_OVRD_IN 0x0015
// FIELD: EN [10:10]
// FIELD: ACJT_LEVEL [9:5]
// FIELD: LOS_LEVEL [4:0]

#define SSP_CR_SUP_DIG_SUP_OVRD_OUT 0x0016
// FIELD: MPLL_STATE_OVRD [9:9]
// FIELD: MPLL_STATE [8:8]
// FIELD: BS_OUT_OVRD [7:7]
// FIELD: BS_OUT [6:6]
// FIELD: RTUNE_ACK_OVRD [5:5]
// FIELD: RTUNE_ACK [4:4]
// FIELD: RES_REQ_OUT_OVRD [3:3]
// FIELD: RES_REQ_OUT [2:2]
// FIELD: RES_ACK_OUT_OVRD [1:1]
// FIELD: RES_ACK_OUT [0:0]

#define SSP_CR_SUP_DIG_MPLL_ASIC_IN 0x0017
// FIELD: MPLL_WORD_CLK_EN [13:13]
// FIELD: MPLL_DWORD_CLK_EN [12:12]
// FIELD: MPLL_QWORD_CLK_EN [11:11]
// FIELD: RES_ACK_IN [10:10]
// FIELD: RES_REQ_IN [9:9]
// FIELD: RTUNE_REQ [8:8]
// FIELD: MPLL_MULTIPLIER [7:1]
// FIELD: MPLL_EN [0:0]

#define SSP_CR_SUP_DIG_BS_ASIC_IN 0x0018
// FIELD: INVERT [10:10]
// FIELD: INIT [9:9]
// FIELD: HIGHZ [8:8]
// FIELD: CLAMP [7:7]
// FIELD: EXTEST_AC [6:6]
// FIELD: EXTEST [5:5]
// FIELD: PRELOAD [4:4]
// FIELD: UPDATE_DR [3:3]
// FIELD: CAPTURE_DR [2:2]
// FIELD: SHIFT_DR [1:1]
// FIELD: IN [0:0]

#define SSP_CR_SUP_DIG_LEVEL_ASIC_IN 0x0019
// FIELD: ACJT_LEVEL [9:5]
// FIELD: LOS_LEVEL [4:0]

#define SSP_CR_SUP_DIG_SSC_ASIC_IN 0x001A
// FIELD: SS_EN [13:13]
// FIELD: SSC_RANGE [12:11]
// FIELD: SSC_REF_CLK_SEL [10:3]
// FIELD: FSEL [2:0]

#define SSP_CR_SUP_DIG_SUP_ASIC_OUT 0x001B
// FIELD: MPLL_STATE [4:4]
// FIELD: BS_OUT [3:3]
// FIELD: RTUNE_ACK [2:2]
// FIELD: RES_REQ_OUT [1:1]
// FIELD: RES_ACK_OUT [0:0]

#define SSP_CR_SUP_DIG_ATEOVRD_STATUS 0x001C
// FIELD: REF_SSP_EN [7:7]
// FIELD: REF_USE_PAD [6:6]
// FIELD: PHY_RESET_IN [5:5]
// FIELD: REF_CLKDIV2_IN [4:4]
// FIELD: REF_USB2_EN_IN [3:3]
// FIELD: ATEOVRD_EN [2:2]
// FIELD: REF_CLKDIV2_OUT [1:1]
// FIELD: REF_USB2_EN_OUT [0:0]

#define SSP_CR_SUP_DIG_RTUNE_DEBUG 0x0003
// FIELD: FLIP_COMP [0:0]
// FIELD: MAN_TUNE [1:1]
// FIELD: SET_VAL [2:2]
// FIELD: TYPE [4:3]
// FIELD: VALUE [14:5]

#define SSP_CR_SUP_DIG_RTUNE_STAT 0x0004
// FIELD: STAT [9:0]

#define SSP_CR_SUP_DIG_SCOPE_ENABLES 0x0020
// FIELD: MASK_SATURATION_MODE [2:2]
// FIELD: MASK_EN [1:1]
// FIELD: XOR_EN [0:0]

#define SSP_CR_SUP_DIG_SCOPE_SAMPLES 0x0021
// FIELD: SAMPLES [15:0]

#define SSP_CR_SUP_DIG_SCOPE_COUNT 0x0022
// FIELD: COUNT [15:0]

#define SSP_CR_SUP_DIG_SCOPE_CTL 0x0023
// FIELD: MASK_START [1:1]
// FIELD: MASK_SATURATION [0:0]

#define SSP_CR_SUP_DIG_SCOPE_MASK_000 0x0024
// FIELD: MASK_VAL_000 [15:0]

#define SSP_CR_SUP_DIG_SCOPE_MASK_001 0x0025
// FIELD: MASK_VAL_001 [15:0]

#define SSP_CR_SUP_DIG_SCOPE_MASK_010 0x0026
// FIELD: MASK_VAL_010 [15:0]

#define SSP_CR_SUP_DIG_SCOPE_MASK_011 0x0027
// FIELD: MASK_VAL_011 [15:0]

#define SSP_CR_SUP_DIG_SCOPE_MASK_100 0x0028
// FIELD: MASK_VAL_100 [15:0]

#define SSP_CR_SUP_DIG_SCOPE_MASK_101 0x0029
// FIELD: MASK_VAL_101 [15:0]

#define SSP_CR_SUP_DIG_SCOPE_MASK_110 0x002A
// FIELD: MASK_VAL_110 [15:0]

#define SSP_CR_SUP_DIG_SCOPE_MASK_111 0x002B
// FIELD: MASK_VAL_111 [15:0]

#define SSP_CR_SUP_ANA_MPLL_LOOP_CTL 0x0030
// FIELD: VMB [0:0]
// FIELD: VBF_SF [1:1]
// FIELD: INT_CNTRL [3:2]
// FIELD: PROP_CNTRL [7:4]

#define SSP_CR_SUP_ANA_MPLL_ATB_MEAS1 0x0031
// FIELD: VREG_MPLL [0:0]
// FIELD: VP_CP [1:1]
// FIELD: VPA [2:2]
// FIELD: IVCO [3:3]
// FIELD: GD [4:4]
// FIELD: VCNTRL [5:5]
// FIELD: VREF [6:6]
// FIELD: VPSF [7:7]

#define SSP_CR_SUP_ANA_MPLL_ATB_MEAS2 0x0032
// FIELD: EN_MPMIX_TST [0:0]
// FIELD: EN_MPMIX_VPMIX [1:1]
// FIELD: FRC_MPMIX_VPMIX [2:2]
// FIELD: MEAS_TEMP [3:3]
// FIELD: ATB_SENSE_SEL [4:4]
// FIELD: VCNTRL_P [5:5]
// FIELD: VCNTRL_M [6:6]
// FIELD: IVCO_FILT [7:7]

#define SSP_CR_SUP_ANA_MPLL_OVRD 0x0033
// FIELD: EN_PMIX_CLK_SEL_LCL [0:0]
// FIELD: PMIX_CLK_SEL_LCL [1:1]
// FIELD: EN_RST_LCL [2:2]
// FIELD: RST_LCL [3:3]
// FIELD: EN_GS_LCL [4:4]
// FIELD: GS_LCL [5:5]
// FIELD: EN_PWRON_LCL [6:6]
// FIELD: PWRON_LCL [7:7]

#define SSP_CR_SUP_ANA_RTUNE_RTUNE_CTRL 0x0034
// FIELD: RT_SEL_ATBF [0:0]
// FIELD: RT_SEL_ATBP [1:1]
// FIELD: RT_ATB [2:2]
// FIELD: RT_DAC_CHOP [3:3]
// FIELD: RT_DAC_MODE [5:4]
// FIELD: X4_FRC_OFF [6:6]
// FIELD: RT_PWRON_FRC_ON [7:7]

#define SSP_CR_SUP_ANA_ATB_SWITCHYARD_CTRL 0x0035
// FIELD: ATEST_ASP [0:0]
// FIELD: ATEST_ASM [1:1]
// FIELD: ATEST_AFP [2:2]
// FIELD: ATEST_AFM [3:3]
// FIELD: ASP_VPH [4:4]
// FIELD: ASP_VHPREG [5:5]
// FIELD: ASP_VP [6:6]
// FIELD: ASM_GD [7:7]

#define SSP_CR_LANE0_DIG_TX_OVRD_IN_LO 0x1000
// FIELD: TX_DETECT_RX_REQ_OVRD [13:13]
// FIELD: TX_DETECT_RX_REQ [12:12]
// FIELD: TX_BEACON_EN_OVRD [11:11]
// FIELD: TX_BEACON_EN [10:10]
// FIELD: TX_CM_EN_OVRD [9:9]
// FIELD: TX_CM_EN [8:8]
// FIELD: TX_EN_OVRD [7:7]
// FIELD: TX_EN [6:6]
// FIELD: TX_DATA_EN_OVRD [5:5]
// FIELD: TX_DATA_EN [4:4]
// FIELD: TX_INVERT_OVRD [3:3]
// FIELD: TX_INVERT [2:2]
// FIELD: TX_LOOPBK_EN_OVRD [1:1]
// FIELD: LOOPBK_EN [0:0]

#define SSP_CR_LANE0_DIG_TX_OVRD_IN_HI 0x1001
// FIELD: TX_RESET_OVRD [7:7]
// FIELD: TX_RESET [6:6]
// FIELD: TX_NYQUIST_DATA [5:5]
// FIELD: TX_CLK_OUT_EN_OVRD [4:4]
// FIELD: TX_CLK_OUT_EN [3:3]
// FIELD: TX_RATE_OVRD [2:2]
// FIELD: TX_RATE [1:0]

#define SSP_CR_LANE0_DIG_TX_OVRD_DRV_LO 0x1002
// FIELD: EN [14:14]
// FIELD: PREEMPH [13:7]
// FIELD: AMPLITUDE [6:0]

#define SSP_CR_LANE0_DIG_TX_OVRD_DRV_HI 0x1003
// FIELD: EN [5:5]
// FIELD: TERM_OFFSET [4:0]

#define SSP_CR_LANE0_DIG_TX_OVRD_OUT 0x1004
// FIELD: TX_STATE_OVRD [7:7]
// FIELD: TX_STATE [6:6]
// FIELD: TX_CM_STATE_OVRD [5:5]
// FIELD: TX_CM_STATE [4:4]
// FIELD: TX_DETECT_RX_ACK_OVRD [3:3]
// FIELD: TX_DETECT_RX_ACK [2:2]
// FIELD: DETECT_RX_RES_OVRD [1:1]
// FIELD: DETECT_RX_RES [0:0]

#define SSP_CR_LANE0_DIG_RX_OVRD_IN_LO 0x1005
// FIELD: RX_LOS_EN_OVRD [13:13]
// FIELD: RX_LOS_EN [12:12]
// FIELD: RX_TERM_EN_OVRD [11:11]
// FIELD: RX_TERM_EN [10:10]
// FIELD: RX_BIT_SHIFT_OVRD [9:9]
// FIELD: RX_BIT_SHIFT [8:8]
// FIELD: RX_ALIGN_EN_OVRD [7:7]
// FIELD: RX_ALIGN_EN [6:6]
// FIELD: RX_DATA_EN_OVRD [5:5]
// FIELD: RX_DATA_EN [4:4]
// FIELD: RX_PLL_EN_OVRD [3:3]
// FIELD: RX_PLL_EN [2:2]
// FIELD: RX_INVERT_OVRD [1:1]
// FIELD: RX_INVERT [0:0]

#define SSP_CR_LANE0_DIG_RX_OVRD_IN_HI 0x1006
// FIELD: RX_RESET_OVRD [13:13]
// FIELD: RX_RESET [12:12]
// FIELD: RX_EQ_OVRD [11:11]
// FIELD: RX_EQ [10:8]
// FIELD: RX_EQ_EN_OVRD [7:7]
// FIELD: RX_EQ_EN [6:6]
// FIELD: RX_LOS_FILTER_OVRD [5:5]
// FIELD: RX_LOS_FILTER [4:3]
// FIELD: RX_RATE_OVRD [2:2]
// FIELD: RX_RATE [1:0]

#define SSP_CR_LANE0_DIG_RX_OVRD_OUT 0x1007
// FIELD: ZERO_DATA [6:6]
// FIELD: LOS_OVRD [5:5]
// FIELD: LOS [4:4]
// FIELD: PLL_STATE_OVRD [3:3]
// FIELD: PLL_STATE [2:2]
// FIELD: VALID_OVRD [1:1]
// FIELD: VALID [0:0]

#define SSP_CR_LANE0_DIG_TX_ASIC_IN 0x1008
// FIELD: TX_CLK_OUT_EN [10:10]
// FIELD: DETECT_RX_REQ [9:9]
// FIELD: BEACON_EN [8:8]
// FIELD: CM_EN [7:7]
// FIELD: TX_EN [6:6]
// FIELD: DATA_EN [5:5]
// FIELD: TX_RESET [4:4]
// FIELD: INVERT [3:3]
// FIELD: LOOPBK_EN [2:2]
// FIELD: TX_RATE [1:0]

#define SSP_CR_LANE0_DIG_TX_ASIC_DRV_LO 0x1009
// FIELD: PREEMPH [13:7]
// FIELD: AMPLITUDE [6:0]

#define SSP_CR_LANE0_DIG_TX_ASIC_DRV_HI 0x100A
// FIELD: TERM_OFFSET [4:0]

#define SSP_CR_LANE0_DIG_TX_ASIC_OUT 0x100B
// FIELD: STATE [4:4]
// FIELD: CM_STATE [3:3]
// FIELD: DETECT_RX_ACK [2:2]
// FIELD: RESERVED [1:1]
// FIELD: DETECT_RX_RES [0:0]

#define SSP_CR_LANE0_DIG_RX_ASIC_IN 0x100C
// FIELD: RX_EQ_EN [15:15]
// FIELD: RX_EQ [14:12]
// FIELD: LOS_FILTER [11:10]
// FIELD: LOS_EN [9:9]
// FIELD: TERM_EN [8:8]
// FIELD: CLK_SHIFT [7:7]
// FIELD: ALIGN_EN [6:6]
// FIELD: DATA_EN [5:5]
// FIELD: PLL_EN [4:4]
// FIELD: RX_RESET [3:3]
// FIELD: INVERT [2:2]
// FIELD: RX_RATE [1:0]

#define SSP_CR_LANE0_DIG_RX_ASIC_OUT 0x100D
// FIELD: LOS [2:2]
// FIELD: PLL_STATE [1:1]
// FIELD: VALID [0:0]

#define SSP_CR_LANE0_DIG_TX_DEBUG 0x1010
// FIELD: DTB_SEL [2:0]
// FIELD: DETECT_RX_ALWAYS [3:3]
// FIELD: RXDET_MEAS_TIME [10:4]
// FIELD: CM_TIME [15:11]

#define SSP_CR_LANE0_DIG_TX_VMD_FSM_TX_VCM_0 0x1011
// FIELD: DONE [14:14]
// FIELD: N_USE [13:7]
// FIELD: N_TRISTATE [6:0]

#define SSP_CR_LANE0_DIG_TX_VMD_FSM_TX_VCM_1 0x1012
// FIELD: FIXED_DONE [15:15]
// FIELD: TRA_DONE [14:14]
// FIELD: N_FIXED [13:7]
// FIELD: N_TRAILER [6:0]

#define SSP_CR_LANE0_DIG_TX_VMD_FSM_TX_VCM_DEBUG_IN 0x1013
// FIELD: CONFIG_OVRD [3:3]
// FIELD: CONFIG_LOAD [2:2]
// FIELD: CONFIG_CLK [1:1]
// FIELD: CONFIG_DATA [0:0]

#define SSP_CR_LANE0_DIG_TX_VMD_FSM_TX_VCM_DEBUG_OUT 0x1014
// FIELD: SHIFT_OUT [0:0]

#define SSP_CR_LANE0_DIG_TX_LBERT_CTL 0x1015
// FIELD: MODE [2:0]
// FIELD: TRIGGER_ERR [3:3]
// FIELD: PAT0 [13:4]

#define SSP_CR_LANE0_DIG_RX_LBERT_CTL 0x1016
// FIELD: MODE [2:0]
// FIELD: SYNC [3:3]

#define SSP_CR_LANE0_DIG_RX_LBERT_ERR 0x1017
// FIELD: COUNT [14:0]
// FIELD: OV14 [15:15]

#define SSP_CR_LANE0_DIG_RX_SCOPE_CTL 0x1018
// FIELD: RX_VALID_CTL [13:12]
// FIELD: DELAY [11:3]
// FIELD: MODE [2:0]

#define SSP_CR_LANE0_DIG_RX_SCOPE_PHASE 0x1019
// FIELD: BASE [14:10]
// FIELD: SCOPE_DELAY [9:8]
// FIELD: SCOPE_SEL [7:7]
// FIELD: UPDATE [6:6]
// FIELD: SAMPLE_PHASE [5:0]

#define SSP_CR_LANE0_DIG_RX_DPLL_FREQ 0x101A
// FIELD: DTHR [0:0]
// FIELD: VAL [12:1]

#define SSP_CR_LANE0_DIG_RX_CDR_CTL 0x101B
// FIELD: PHDET_EN [1:0]
// FIELD: PHDET_EDGE [3:2]
// FIELD: PHDET_POL [4:4]
// FIELD: OVRD_DPLL_GAIN [5:5]
// FIELD: PHUG_VALUE [7:6]
// FIELD: FRUG_VALUE [9:8]
// FIELD: FAST_START [10:10]
// FIELD: ALWAYS_REALIGN [11:11]
// FIELD: DTB_SEL [15:12]

#define SSP_CR_LANE0_DIG_RX_CDR_CDR_FSM_DEBUG 0x101C
// FIELD: adap_rx_eq [15:13]
// FIELD: rx_eq_ctr [12:10]
// FIELD: rx_ana_eq [9:7]
// FIELD: adap_rx_valid [6:6]
// FIELD: cdr_en_adap [5:5]
// FIELD: cdr_en_eq [4:4]
// FIELD: aligned [3:3]
// FIELD: cdr_rx_valid [2:2]
// FIELD: cdr_timeout [1:1]
// FIELD: cdr_en [0:0]

#define SSP_CR_LANE0_DIG_RX_CDR_LOCK_VEC_OVRD 0x101D
// FIELD: adap_ctr_level [15:11]
// FIELD: adap_polarity [10:10]
// FIELD: lock_vector_ovrd [9:9]
// FIELD: lock_vector_en [8:8]
// FIELD: lock_vector [7:0]

#define SSP_CR_LANE0_DIG_RX_CDR_LOCK_VEC 0x101E
// FIELD: eq_rx_eq [11:9]
// FIELD: eq_locked_vector_en [8:8]
// FIELD: eq_locked_vector [7:0]

#define SSP_CR_LANE0_DIG_RX_CDR_ADAP_FSM 0x101F
// FIELD: mstr_ctr [15:11]
// FIELD: loop_ctr [10:7]
// FIELD: adap_ctr [6:3]
// FIELD: adap_state [2:0]

#define SSP_CR_LANE0_ANA_RX_ATB0 0x1020
// FIELD: EN_ATB_VOFF [0:0]
// FIELD: EN_ATB_VOS [1:1]
// FIELD: EN_ATB_RP_S [2:2]
// FIELD: EN_ATB_RP_F [3:3]
// FIELD: EN_ATB_RM_S [4:4]
// FIELD: EN_ATB_RM_F [5:5]
// FIELD: EN_MARG [6:6]
// FIELD: EN_ATB [7:7]

#define SSP_CR_LANE0_ANA_RX_ATB1 0x1021
// FIELD: RX_NC0 [0:0]
// FIELD: EN_VLOS_USB3 [1:1]
// FIELD: MEAS_VP [2:2]
// FIELD: MEAS_GD [3:3]
// FIELD: EN_ATB_VRF [4:4]
// FIELD: EN_ATB_VLOS [5:5]
// FIELD: VLOS_MIN [6:6]
// FIELD: VLOS_MAX [7:7]

#define SSP_CR_LANE0_ANA_RX_ENPWR0 0x1022
// FIELD: LCL_ACJT [0:0]
// FIELD: CTL_ACJT [1:1]
// FIELD: LCL_RXCK [2:2]
// FIELD: CTL_RXCK [3:3]
// FIELD: LCL_EN_LOS [4:4]
// FIELD: CTL_EN_LOS [5:5]
// FIELD: LCL_RXPWRON [6:6]
// FIELD: CTL_RXPWRON [7:7]

#define SSP_CR_LANE0_ANA_RX_PMIX_PHASE 0x1023
// FIELD: PHASE [7:0]

#define SSP_CR_LANE0_ANA_RX_ENPWR1 0x1024
// FIELD: CTL_PHASE_REG_RST [7:7]
// FIELD: LCL_PHASE_REG_RST [6:6]
// FIELD: CTL_BST [5:5]
// FIELD: LCL_BST [4:2]
// FIELD: CTL_RXTERM [1:1]
// FIELD: LCL_RXTERM [0:0]

#define SSP_CR_LANE0_ANA_RX_ENPWR2 0x1025
// FIELD: RX_SCOPE_ATB_0 [0:0]
// FIELD: RX_SCOPE_ATB_1 [1:1]
// FIELD: RX_SCOPE_ATB_2 [2:2]
// FIELD: EN_RXPMIX_FRC_VPMIX [3:3]
// FIELD: EN_RXPMIX_VOSC [4:4]
// FIELD: EN_RXPMIX_VRX [5:5]
// FIELD: EN_RXPMIX_VPMIX [6:6]
// FIELD: EN_RXPMIX_TST [7:7]

#define SSP_CR_LANE0_ANA_RX_SCOPE 0x1026
// FIELD: RX_NC1 [2:0]
// FIELD: RX_SCOPE_FDIV20 [3:3]
// FIELD: RX_SCOPE_SLEW [4:4]
// FIELD: RX_NC2 [7:5]

#define SSP_CR_LANE0_ANA_TX_TXDRV_CNTRL 0x102B
// FIELD: NOCONN_6 [0:0]
// FIELD: NOCONN_7 [1:1]
// FIELD: NOCONN_8 [2:2]
// FIELD: OVRD_VCM_HOLD [3:3]
// FIELD: VCM_HOLD_REG [4:4]
// FIELD: OVRD_PULL_UP [5:5]
// FIELD: PULL_UP_REG [6:6]
// FIELD: PULL_DN_REG [7:7]

#define SSP_CR_LANE0_ANA_TX_POWER_CTL 0x102C
// FIELD: NOCONN_5 [0:0]
// FIELD: REFGEN_PDN_REG [1:1]
// FIELD: TX_DIV_CLK_EN [2:2]
// FIELD: REFGEN_EN_REG [3:3]
// FIELD: DATA_EN_REG [4:4]
// FIELD: CLK_EN_REG [5:5]
// FIELD: SERIAL_EN_REG [6:6]
// FIELD: OVRD_EN [7:7]

#define SSP_CR_LANE0_ANA_TX_ALT_BLOCK 0x102D
// FIELD: OVRD_ALT_BUS [0:0]
// FIELD: ALT_OSC_VPHREG [1:1]
// FIELD: ALT_OSC_VPH [2:2]
// FIELD: ALT_OSC_VP [3:3]
// FIELD: JTAG_DATA_REG [4:4]
// FIELD: DRV_SOURCE_REG [6:5]
// FIELD: EN_ALT_BUS [7:7]

#define SSP_CR_LANE0_ANA_TX_ALT_AND_LOOPBACK 0x102E
// FIELD: NOCONN_00 [0:0]
// FIELD: NOCONN_01 [1:1]
// FIELD: NOCONN_02 [2:2]
// FIELD: NOCONN_03 [3:3]
// FIELD: NOCONN_04 [4:4]
// FIELD: ALT_VPTX_OSC [5:5]
// FIELD: TX_LB_EN_REG [6:6]
// FIELD: OVRD_TX_LB [7:7]

#define SSP_CR_LANE0_ANA_TX_TX_ATB_REG 0x102F
// FIELD: ATB_VCM [0:0]
// FIELD: ATB_TXSM [1:1]
// FIELD: ATB_TXSP [2:2]
// FIELD: ATB_TXFM [3:3]
// FIELD: ATB_TXFP [4:4]
// FIELD: ATB_RXDETREF [5:5]
// FIELD: ATB_VCM_REP [6:6]
// FIELD: ATB_PBIAS [7:7]

#define SSP_CR_LANEX_DIG_TX_OVRD_IN_LO 0x9000
// FIELD: TX_DETECT_RX_REQ_OVRD [13:13]
// FIELD: TX_DETECT_RX_REQ [12:12]
// FIELD: TX_BEACON_EN_OVRD [11:11]
// FIELD: TX_BEACON_EN [10:10]
// FIELD: TX_CM_EN_OVRD [9:9]
// FIELD: TX_CM_EN [8:8]
// FIELD: TX_EN_OVRD [7:7]
// FIELD: TX_EN [6:6]
// FIELD: TX_DATA_EN_OVRD [5:5]
// FIELD: TX_DATA_EN [4:4]
// FIELD: TX_INVERT_OVRD [3:3]
// FIELD: TX_INVERT [2:2]
// FIELD: TX_LOOPBK_EN_OVRD [1:1]
// FIELD: LOOPBK_EN [0:0]

#define SSP_CR_LANEX_DIG_TX_OVRD_IN_HI 0x9001
// FIELD: TX_RESET_OVRD [7:7]
// FIELD: TX_RESET [6:6]
// FIELD: TX_NYQUIST_DATA [5:5]
// FIELD: TX_CLK_OUT_EN_OVRD [4:4]
// FIELD: TX_CLK_OUT_EN [3:3]
// FIELD: TX_RATE_OVRD [2:2]
// FIELD: TX_RATE [1:0]

#define SSP_CR_LANEX_DIG_TX_OVRD_DRV_LO 0x9002
// FIELD: EN [14:14]
// FIELD: PREEMPH [13:7]
// FIELD: AMPLITUDE [6:0]

#define SSP_CR_LANEX_DIG_TX_OVRD_DRV_HI 0x9003
// FIELD: EN [5:5]
// FIELD: TERM_OFFSET [4:0]

#define SSP_CR_LANEX_DIG_TX_OVRD_OUT 0x9004
// FIELD: TX_STATE_OVRD [7:7]
// FIELD: TX_STATE [6:6]
// FIELD: TX_CM_STATE_OVRD [5:5]
// FIELD: TX_CM_STATE [4:4]
// FIELD: TX_DETECT_RX_ACK_OVRD [3:3]
// FIELD: TX_DETECT_RX_ACK [2:2]
// FIELD: DETECT_RX_RES_OVRD [1:1]
// FIELD: DETECT_RX_RES [0:0]

#define SSP_CR_LANEX_DIG_RX_OVRD_IN_LO 0x9005
// FIELD: RX_LOS_EN_OVRD [13:13]
// FIELD: RX_LOS_EN [12:12]
// FIELD: RX_TERM_EN_OVRD [11:11]
// FIELD: RX_TERM_EN [10:10]
// FIELD: RX_BIT_SHIFT_OVRD [9:9]
// FIELD: RX_BIT_SHIFT [8:8]
// FIELD: RX_ALIGN_EN_OVRD [7:7]
// FIELD: RX_ALIGN_EN [6:6]
// FIELD: RX_DATA_EN_OVRD [5:5]
// FIELD: RX_DATA_EN [4:4]
// FIELD: RX_PLL_EN_OVRD [3:3]
// FIELD: RX_PLL_EN [2:2]
// FIELD: RX_INVERT_OVRD [1:1]
// FIELD: RX_INVERT [0:0]

#define SSP_CR_LANEX_DIG_RX_OVRD_IN_HI 0x9006
// FIELD: RX_RESET_OVRD [13:13]
// FIELD: RX_RESET [12:12]
// FIELD: RX_EQ_OVRD [11:11]
// FIELD: RX_EQ [10:8]
// FIELD: RX_EQ_EN_OVRD [7:7]
// FIELD: RX_EQ_EN [6:6]
// FIELD: RX_LOS_FILTER_OVRD [5:5]
// FIELD: RX_LOS_FILTER [4:3]
// FIELD: RX_RATE_OVRD [2:2]
// FIELD: RX_RATE [1:0]

#define SSP_CR_LANEX_DIG_RX_OVRD_OUT 0x9007
// FIELD: ZERO_DATA [6:6]
// FIELD: LOS_OVRD [5:5]
// FIELD: LOS [4:4]
// FIELD: PLL_STATE_OVRD [3:3]
// FIELD: PLL_STATE [2:2]
// FIELD: VALID_OVRD [1:1]
// FIELD: VALID [0:0]

#define SSP_CR_LANEX_DIG_TX_ASIC_IN 0x9008
// FIELD: TX_CLK_OUT_EN [10:10]
// FIELD: DETECT_RX_REQ [9:9]
// FIELD: BEACON_EN [8:8]
// FIELD: CM_EN [7:7]
// FIELD: TX_EN [6:6]
// FIELD: DATA_EN [5:5]
// FIELD: TX_RESET [4:4]
// FIELD: INVERT [3:3]
// FIELD: LOOPBK_EN [2:2]
// FIELD: TX_RATE [1:0]

#define SSP_CR_LANEX_DIG_TX_ASIC_DRV_LO 0x9009
// FIELD: PREEMPH [13:7]
// FIELD: AMPLITUDE [6:0]

#define SSP_CR_LANEX_DIG_TX_ASIC_DRV_HI 0x900A
// FIELD: TERM_OFFSET [4:0]

#define SSP_CR_LANEX_DIG_TX_ASIC_OUT 0x900B
// FIELD: STATE [4:4]
// FIELD: CM_STATE [3:3]
// FIELD: DETECT_RX_ACK [2:2]
// FIELD: RESERVED [1:1]
// FIELD: DETECT_RX_RES [0:0]

#define SSP_CR_LANEX_DIG_RX_ASIC_IN 0x900C
// FIELD: RX_EQ_EN [15:15]
// FIELD: RX_EQ [14:12]
// FIELD: LOS_FILTER [11:10]
// FIELD: LOS_EN [9:9]
// FIELD: TERM_EN [8:8]
// FIELD: CLK_SHIFT [7:7]
// FIELD: ALIGN_EN [6:6]
// FIELD: DATA_EN [5:5]
// FIELD: PLL_EN [4:4]
// FIELD: RX_RESET [3:3]
// FIELD: INVERT [2:2]
// FIELD: RX_RATE [1:0]

#define SSP_CR_LANEX_DIG_RX_ASIC_OUT 0x900D
// FIELD: LOS [2:2]
// FIELD: PLL_STATE [1:1]
// FIELD: VALID [0:0]

#define SSP_CR_LANEX_DIG_TX_DEBUG 0x9010
// FIELD: DTB_SEL [2:0]
// FIELD: DETECT_RX_ALWAYS [3:3]
// FIELD: RXDET_MEAS_TIME [10:4]
// FIELD: CM_TIME [15:11]

#define SSP_CR_LANEX_DIG_TX_VMD_FSM_TX_VCM_0 0x9011
// FIELD: DONE [14:14]
// FIELD: N_USE [13:7]
// FIELD: N_TRISTATE [6:0]

#define SSP_CR_LANEX_DIG_TX_VMD_FSM_TX_VCM_1 0x9012
// FIELD: FIXED_DONE [15:15]
// FIELD: TRA_DONE [14:14]
// FIELD: N_FIXED [13:7]
// FIELD: N_TRAILER [6:0]

#define SSP_CR_LANEX_DIG_TX_VMD_FSM_TX_VCM_DEBUG_IN 0x9013
// FIELD: CONFIG_OVRD [3:3]
// FIELD: CONFIG_LOAD [2:2]
// FIELD: CONFIG_CLK [1:1]
// FIELD: CONFIG_DATA [0:0]

#define SSP_CR_LANEX_DIG_TX_VMD_FSM_TX_VCM_DEBUG_OUT 0x9014
// FIELD: SHIFT_OUT [0:0]

#define SSP_CR_LANEX_DIG_TX_LBERT_CTL 0x9015
// FIELD: MODE [2:0]
// FIELD: TRIGGER_ERR [3:3]
// FIELD: PAT0 [13:4]

#define SSP_CR_LANEX_DIG_RX_LBERT_CTL 0x9016
// FIELD: MODE [2:0]
// FIELD: SYNC [3:3]

#define SSP_CR_LANEX_DIG_RX_LBERT_ERR 0x9017
// FIELD: COUNT [14:0]
// FIELD: OV14 [15:15]

#define SSP_CR_LANEX_DIG_RX_SCOPE_CTL 0x9018
// FIELD: RX_VALID_CTL [13:12]
// FIELD: DELAY [11:3]
// FIELD: MODE [2:0]

#define SSP_CR_LANEX_DIG_RX_SCOPE_PHASE 0x9019
// FIELD: BASE [14:10]
// FIELD: SCOPE_DELAY [9:8]
// FIELD: SCOPE_SEL [7:7]
// FIELD: UPDATE [6:6]
// FIELD: SAMPLE_PHASE [5:0]

#define SSP_CR_LANEX_DIG_RX_DPLL_FREQ 0x901A
// FIELD: DTHR [0:0]
// FIELD: VAL [12:1]

#define SSP_CR_LANEX_DIG_RX_CDR_CTL 0x901B
// FIELD: PHDET_EN [1:0]
// FIELD: PHDET_EDGE [3:2]
// FIELD: PHDET_POL [4:4]
// FIELD: OVRD_DPLL_GAIN [5:5]
// FIELD: PHUG_VALUE [7:6]
// FIELD: FRUG_VALUE [9:8]
// FIELD: FAST_START [10:10]
// FIELD: ALWAYS_REALIGN [11:11]
// FIELD: DTB_SEL [15:12]

#define SSP_CR_LANEX_DIG_RX_CDR_CDR_FSM_DEBUG 0x901C
// FIELD: adap_rx_eq [15:13]
// FIELD: rx_eq_ctr [12:10]
// FIELD: rx_ana_eq [9:7]
// FIELD: adap_rx_valid [6:6]
// FIELD: cdr_en_adap [5:5]
// FIELD: cdr_en_eq [4:4]
// FIELD: aligned [3:3]
// FIELD: cdr_rx_valid [2:2]
// FIELD: cdr_timeout [1:1]
// FIELD: cdr_en [0:0]

#define SSP_CR_LANEX_DIG_RX_CDR_LOCK_VEC_OVRD 0x901D
// FIELD: adap_ctr_level [15:11]
// FIELD: adap_polarity [10:10]
// FIELD: lock_vector_ovrd [9:9]
// FIELD: lock_vector_en [8:8]
// FIELD: lock_vector [7:0]

#define SSP_CR_LANEX_DIG_RX_CDR_LOCK_VEC 0x901E
// FIELD: eq_rx_eq [11:9]
// FIELD: eq_locked_vector_en [8:8]
// FIELD: eq_locked_vector [7:0]

#define SSP_CR_LANEX_DIG_RX_CDR_ADAP_FSM 0x901F
// FIELD: mstr_ctr [15:11]
// FIELD: loop_ctr [10:7]
// FIELD: adap_ctr [6:3]
// FIELD: adap_state [2:0]

#define SSP_CR_LANEX_ANA_RX_ATB0 0x9020
// FIELD: EN_ATB_VOFF [0:0]
// FIELD: EN_ATB_VOS [1:1]
// FIELD: EN_ATB_RP_S [2:2]
// FIELD: EN_ATB_RP_F [3:3]
// FIELD: EN_ATB_RM_S [4:4]
// FIELD: EN_ATB_RM_F [5:5]
// FIELD: EN_MARG [6:6]
// FIELD: EN_ATB [7:7]

#define SSP_CR_LANEX_ANA_RX_ATB1 0x9021
// FIELD: RX_NC0 [0:0]
// FIELD: EN_VLOS_USB3 [1:1]
// FIELD: MEAS_VP [2:2]
// FIELD: MEAS_GD [3:3]
// FIELD: EN_ATB_VRF [4:4]
// FIELD: EN_ATB_VLOS [5:5]
// FIELD: VLOS_MIN [6:6]
// FIELD: VLOS_MAX [7:7]

#define SSP_CR_LANEX_ANA_RX_ENPWR0 0x9022
// FIELD: LCL_ACJT [0:0]
// FIELD: CTL_ACJT [1:1]
// FIELD: LCL_RXCK [2:2]
// FIELD: CTL_RXCK [3:3]
// FIELD: LCL_EN_LOS [4:4]
// FIELD: CTL_EN_LOS [5:5]
// FIELD: LCL_RXPWRON [6:6]
// FIELD: CTL_RXPWRON [7:7]

#define SSP_CR_LANEX_ANA_RX_PMIX_PHASE 0x9023
// FIELD: PHASE [7:0]

#define SSP_CR_LANEX_ANA_RX_ENPWR1 0x9024
// FIELD: CTL_PHASE_REG_RST [7:7]
// FIELD: LCL_PHASE_REG_RST [6:6]
// FIELD: CTL_BST [5:5]
// FIELD: LCL_BST [4:2]
// FIELD: CTL_RXTERM [1:1]
// FIELD: LCL_RXTERM [0:0]

#define SSP_CR_LANEX_ANA_RX_ENPWR2 0x9025
// FIELD: RX_SCOPE_ATB_0 [0:0]
// FIELD: RX_SCOPE_ATB_1 [1:1]
// FIELD: RX_SCOPE_ATB_2 [2:2]
// FIELD: EN_RXPMIX_FRC_VPMIX [3:3]
// FIELD: EN_RXPMIX_VOSC [4:4]
// FIELD: EN_RXPMIX_VRX [5:5]
// FIELD: EN_RXPMIX_VPMIX [6:6]
// FIELD: EN_RXPMIX_TST [7:7]

#define SSP_CR_LANEX_ANA_RX_SCOPE 0x9026
// FIELD: RX_NC1 [2:0]
// FIELD: RX_SCOPE_FDIV20 [3:3]
// FIELD: RX_SCOPE_SLEW [4:4]
// FIELD: RX_NC2 [7:5]

#define SSP_CR_LANEX_ANA_TX_TXDRV_CNTRL 0x902B
// FIELD: NOCONN_6 [0:0]
// FIELD: NOCONN_7 [1:1]
// FIELD: NOCONN_8 [2:2]
// FIELD: OVRD_VCM_HOLD [3:3]
// FIELD: VCM_HOLD_REG [4:4]
// FIELD: OVRD_PULL_UP [5:5]
// FIELD: PULL_UP_REG [6:6]
// FIELD: PULL_DN_REG [7:7]

#define SSP_CR_LANEX_ANA_TX_POWER_CTL 0x902C
// FIELD: NOCONN_5 [0:0]
// FIELD: REFGEN_PDN_REG [1:1]
// FIELD: TX_DIV_CLK_EN [2:2]
// FIELD: REFGEN_EN_REG [3:3]
// FIELD: DATA_EN_REG [4:4]
// FIELD: CLK_EN_REG [5:5]
// FIELD: SERIAL_EN_REG [6:6]
// FIELD: OVRD_EN [7:7]

#define SSP_CR_LANEX_ANA_TX_ALT_BLOCK 0x902D
// FIELD: OVRD_ALT_BUS [0:0]
// FIELD: ALT_OSC_VPHREG [1:1]
// FIELD: ALT_OSC_VPH [2:2]
// FIELD: ALT_OSC_VP [3:3]
// FIELD: JTAG_DATA_REG [4:4]
// FIELD: DRV_SOURCE_REG [6:5]
// FIELD: EN_ALT_BUS [7:7]

#define SSP_CR_LANEX_ANA_TX_ALT_AND_LOOPBACK 0x902E
// FIELD: NOCONN_00 [0:0]
// FIELD: NOCONN_01 [1:1]
// FIELD: NOCONN_02 [2:2]
// FIELD: NOCONN_03 [3:3]
// FIELD: NOCONN_04 [4:4]
// FIELD: ALT_VPTX_OSC [5:5]
// FIELD: TX_LB_EN_REG [6:6]
// FIELD: OVRD_TX_LB [7:7]

#define SSP_CR_LANEX_ANA_TX_TX_ATB_REG 0x902F
// FIELD: ATB_VCM [0:0]
// FIELD: ATB_TXSM [1:1]
// FIELD: ATB_TXSP [2:2]
// FIELD: ATB_TXFM [3:3]
// FIELD: ATB_TXFP [4:4]
// FIELD: ATB_RXDETREF [5:5]
// FIELD: ATB_VCM_REP [6:6]
// FIELD: ATB_PBIAS [7:7]

// SSP ID_CODE
// -----------------
// RTL Version = 8.0          ==>  4'h7
// Product     = SSP          ==>  4'h2
// Foundry     = TSMC 40nm LP ==>  8'h11
// Test_chip   = PHY          ==>  1'h0
// Site ID     = Hillsboro    ==>  3'h6
// Synopsys                   ==> 12'h4CD
#define SSP_JTAG_DR_IDCODE_VAL_HI  0x7211
#define SSP_JTAG_DR_IDCODE_VAL_LO  0x64CD

int pcie_phy_cr_read(uint32_t addr, uint32_t * data);
int pcie_phy_cr_write(uint32_t addr, uint32_t data);

#endif //_PCIE_PHY_REGS_H_
