/*
 * Copyright (C) 2011-2012, Freescale Semiconductor, Inc. All Rights Reserved
 * THIS SOURCE CODE IS CONFIDENTIAL AND PROPRIETARY AND MAY NOT
 * BE USED OR DISTRIBUTED WITHOUT THE WRITTEN PERMISSION OF
 * Freescale Semiconductor, Inc.
*/

#ifndef __SSI_H__
#define __SSI_H__

#define SSI_SFCSR_TX_WATERMARK      4   // Default 4
#define SSI_SFCSR_RX_WATERMARK      4   // Default 4

#define SSI_SCR_RESET_VAL	0x00000000
#define SSI_SISR_RESET_VAL      0x00003003
#define SSI_SIER_RESET_VAL      0x00003003
#define SSI_STCR_RESET_VAL      0x00000200
#define SSI_SRCR_RESET_VAL      0x00000200
#define SSI_STCCR_RESET_VAL	0x00040000
#define SSI_SRCCR_RESET_VAL	0x00040000
#define SSI_SFCSR_RESET_VAL	0x00810081
#define SSI_SACNT_RESET_VAL	0x00000000
#define SSI_SACADD_RESET_VAL	0x00000000
#define SSI_SACDAT_RESET_VAL	0x00000000
#define SSI_SATAG_RESET_VAL	0x00000000
#define SSI_STMSK_RESET_VAL	0x00000000
#define SSI_SRMSK_RESET_VAL	0x00000000
#define SSI_SACCST_RESET_VAL	0x00000000
#define SSI_SACCEN_RESET_VAL	0x00000000
#define SSI_SACCDIS_RESET_VAL	0x00000000

typedef enum {
    SSI_SETTING_TX_FIFO1_DATAS_CNT,
    SSI_SETTING_TX_FIFO2_DATAS_CNT,
    SSI_SETTING_RX_FIFO1_DATAS_CNT,
    SSI_SETTING_RX_FIFO2_DATAS_CNT,
    SSI_SETTING_TX_WATERMARK,
    SSI_SETTING_RX_WATERMARK,
    SSI_SETTING_TX_WORD_LEN,
    SSI_SETTING_RX_WORD_LEN,
    SSI_SETTING_TX_BIT_CLOCK,
    SSI_SETTING_RX_BIT_CLOCK,
    SSI_SETTING_TX_FRAME_LENGTH,
    SSI_SETTING_RX_FRAME_LENGTH,
    SSI_SETTING_CLK_FS_DIR,
} ssi_setting_type_e;

typedef enum {
    SSI_CLK_FS_DIR_OUTPUT,
    SSI_CLK_FS_DIR_INPUT,
} ssi_clk_fs_dir_e;

typedef enum {
    SSI_HW_ENABLE_SSI,
    SSI_HW_ENABLE_TX,
    SSI_HW_ENABLE_RX,
    SSI_HW_ENABLE_TXFIFO1,
    SSI_HW_ENABLE_TXFIFO2,
    SSI_HW_ENABLE_RXFIFO1,
    SSI_HW_ENABLE_RXFIFO2,
} ssi_hw_enable_type_e;

#endif
