include $(SDK_ROOT)/mk/common.mk


C_SOURCES = \
	checkspaceinrootdir.c \
	computefreeclusters.c \
	fatsector.c \
	filesystempresent.c \
	findnextcluster.c \
	findnextfreecurrentcluster.c \
	firstfreeandallocate.c \
	firstrootdirsector.c \
	firstsectorofcluster.c \
	getnewcluster.c \
	readfat12entry.c \
	readfatentry.c \
	totalfreecluster.c \
	writefatentry.c



include $(SDK_ROOT)/mk/targets.mk
