/*
 * Copyright (C) 2012, Freescale Semiconductor, Inc. All Rights Reserved
 * THIS SOURCE CODE IS CONFIDENTIAL AND PROPRIETARY AND MAY NOT
 * BE USED OR DISTRIBUTED WITHOUT THE WRITTEN PERMISSION OF
 * Freescale Semiconductor, Inc.
*/

// File: iomux_config.c

/* ------------------------------------------------------------------------------
 * <auto-generated>
 *     This code was generated by a tool.
 *     Runtime Version:3.3.2.0
 *
 *     Changes to this file may cause incorrect behavior and will be lost if
 *     the code is regenerated.
 * </auto-generated>
 * ------------------------------------------------------------------------------
*/

#include <iomux_config.h>

// Function to configure iomux for i.MX53 board ARD rev. A.
void iomux_config(void)
{
    audmux_iomux_config();
    can1_iomux_config();
    can2_iomux_config();
    ccm_iomux_config();
    ecspi2_iomux_config();
    emi_iomux_config();
    esai1_iomux_config();
    esdhc1_iomux_config();
    esdhc2_iomux_config();
    fec_iomux_config();
    gpio1_iomux_config();
    gpio2_iomux_config();
    gpio4_iomux_config();
    gpio5_iomux_config();
    gpio7_iomux_config();
    i2c2_iomux_config();
    i2c3_iomux_config();
    ipu_iomux_config();
    kpp_iomux_config();
    mlb_iomux_config();
    pata_iomux_config();
    pwm1_iomux_config();
    pwm2_iomux_config();
    sjc_iomux_config();
    spdif_iomux_config();
    src_iomux_config();
    srtc_iomux_config();
    uart1_iomux_config();
    uart2_iomux_config();
    uart3_iomux_config();
    usboh3_iomux_config();
}

// Definitions for unused modules.
void analog_iomux_config()
{
};

void camp1_iomux_config()
{
};

void camp2_iomux_config()
{
};

void cspi_iomux_config()
{
};

void csu_iomux_config()
{
};

void dpllip1_iomux_config()
{
};

void ecspi1_iomux_config()
{
};

void epit1_iomux_config()
{
};

void epit2_iomux_config()
{
};

void esdhc3_iomux_config()
{
};

void esdhc4_iomux_config()
{
};

void firi_iomux_config()
{
};

void gpc_iomux_config()
{
};

void gpio3_iomux_config()
{
};

void gpio6_iomux_config()
{
};

void gpt_iomux_config()
{
};

void gpu3d_iomux_config()
{
};

void i2c1_iomux_config()
{
};

void ldb_iomux_config()
{
};

void observe_mux_iomux_config()
{
};

void osc32k_iomux_config()
{
};

void owire_iomux_config()
{
};

void p_platform_ne_32k_256k_iomux_config()
{
};

void rtc_iomux_config()
{
};

void rtic_iomux_config()
{
};

void sata_iomux_config()
{
};

void sata_phy_iomux_config()
{
};

void scc_iomux_config()
{
};

void sdma_iomux_config()
{
};

void tcu_iomux_config()
{
};

void tpiu_iomux_config()
{
};

void tvdac_iomux_config()
{
};

void tzic_iomux_config()
{
};

void uart4_iomux_config()
{
};

void uart5_iomux_config()
{
};

void usbphy1_iomux_config()
{
};

void usbphy2_iomux_config()
{
};

void wdog1_iomux_config()
{
};

void wdog2_iomux_config()
{
};
