/*
 * Copyright (C) 2012, Freescale Semiconductor, Inc. All Rights Reserved
 * THIS SOURCE CODE IS CONFIDENTIAL AND PROPRIETARY AND MAY NOT
 * BE USED OR DISTRIBUTED WITHOUT THE WRITTEN PERMISSION OF
 * Freescale Semiconductor, Inc.
*/

// File: mlb_iomux_config.c

/* ------------------------------------------------------------------------------
 * <auto-generated>
 *     This code was generated by a tool.
 *     Runtime Version:3.3.2.0
 *
 *     Changes to this file may cause incorrect behavior and will be lost if
 *     the code is regenerated.
 * </auto-generated>
 * ------------------------------------------------------------------------------
*/

#include "iomux_config.h"
#include "iomux_define.h"
#include "registers/regsiomuxc.h"

// Function to configure IOMUXC for mlb module.
void mlb_iomux_config(void)
{
    // Config mlb.MLBCLK to pad FEC_TXD1(D10)
    // FEC_TXD1
    // HW_IOMUXC_SW_MUX_CTL_PAD_FEC_TXD1_WR(0x00000003);
    // HW_IOMUXC_MLB_MLBCLK_IN_SELECT_INPUT_WR(0x00000000);
    // HW_IOMUXC_SW_PAD_CTL_PAD_FEC_TXD1_WR(0x000001E4);
    // Mux Register:
    // IOMUXC_SW_MUX_CTL_PAD_FEC_TXD1(0x53FA8264)
    //   SION (4) - Software Input On Field Reset: SION_DISABLED
    //              Force the selected mux mode Input path no matter of MUX_MODE functionality.
    //     SION_DISABLED (0) - Input Path is determined by functionality of the selected mux mode (regular).
    //     SION_ENABLED (1) - Force input path of pad FEC_TXD1.
    //   MUX_MODE (2-0) - MUX Mode Select Field Reset: ALT1
    //                    Select 1 of 5 iomux modes to be used for pad: FEC_TXD1.
    //     ALT0 (0) - Select mux mode: ALT0 mux port: TDATA[1] of instance: fec.
    //     ALT1 (1) - Select mux mode: ALT1 mux port: GPIO[29] of instance: gpio1.
    //     ALT2 (2) - Select mux mode: ALT2 mux port: TX2_RX3 of instance: esai1.
    //                NOTE: - Config Register IOMUXC_ESAI1_IPP_IND_SDO2_SDI3_SELECT_INPUT for mode ALT2.
    //     ALT3 (3) - Select mux mode: ALT3 mux port: MLBCLK of instance: mlb.
    //                NOTE: - Config Register IOMUXC_MLB_MLBCLK_IN_SELECT_INPUT for mode ALT3.
    //     ALT4 (4) - Select mux mode: ALT4 mux port: CE_RTC_PRSC_CLK of instance: rtc.
    HW_IOMUXC_SW_MUX_CTL_PAD_FEC_TXD1_WR(
            BF_IOMUXC_SW_MUX_CTL_PAD_FEC_TXD1_SION(SION_DISABLED) | 
            BF_IOMUXC_SW_MUX_CTL_PAD_FEC_TXD1_MUX_MODE(ALT3));
    // Pad FEC_TXD1 is involved in Daisy Chain.
    // Input Select Register:
    // IOMUXC_MLB_MLBCLK_IN_SELECT_INPUT(0x53FA8858)
    //   DAISY (1-0) Reset: SEL_NANDF_CS1_ALT6
    //                 Selecting Pads Involved in Daisy Chain.
    //                 NOTE: Instance: mlb, In Pin: mlbclk_in
    //     SEL_NANDF_CS1_ALT6 (0) - Selecting Pad: NANDF_CS1 for Mode: ALT6.
    //     SEL_FEC_TXD1_ALT3 (1) - Selecting Pad: FEC_TXD1 for Mode: ALT3.
    //     SEL_GPIO_3_ALT7 (2) - Selecting Pad: GPIO_3 for Mode: ALT7.
    HW_IOMUXC_MLB_MLBCLK_IN_SELECT_INPUT_WR(
            BF_IOMUXC_MLB_MLBCLK_IN_SELECT_INPUT_DAISY(SEL_NANDF_CS1_ALT6));
    // Pad Control Register:
    // IOMUXC_SW_PAD_CTL_PAD_FEC_TXD1(0x53FA85E0)
    //   HVE (13) - Low / High Output Voltage Field Reset: HVE_RES0
    //              Read Only Field
    //     HVE_RES0 (0) - Reserved
    //   TEST_TS (12) - Test TS Field Reset: TEST_TS_DISABLED
    //                  Read Only Field
    //     TEST_TS_DISABLED (0) - Disabled
    //   DSE_TEST (11) - DSE Test Field Reset: DSE_TEST_NORMAL
    //                   Read Only Field
    //     DSE_TEST_NORMAL (0) - Normal
    //   HYS (8) - Hysteresis Enable Field Reset: HYS_ENABLED
    //             Select one out of next values for pad: FEC_TXD1.
    //     HYS_DISABLED (0) - Hysteresis Disabled
    //     HYS_ENABLED (1) - Hysteresis Enabled
    //   PKE (7) - Pull / Keep Enable Field Reset: PKE_ENABLED
    //             Select one out of next values for pad: FEC_TXD1.
    //     PKE_DISABLED (0) - Pull/Keeper Disabled
    //     PKE_ENABLED (1) - Pull/Keeper Enabled
    //   PUE (6) - Pull / Keep Select Field Reset: PUE_PULL
    //             Select one out of next values for pad: FEC_TXD1.
    //     PUE_KEEP (0) - Keeper
    //     PUE_PULL (1) - Pull
    //   PUS (5-4) - Pull Up / Down Config. Field Reset: PUS_100KOHM_PU
    //               Select one out of next values for pad: FEC_TXD1.
    //     PUS_360KOHM_PD (0) - 360K Ohm Pull Down
    //     PUS_75KOHM_PU (1) - 75K Ohm Pull Up
    //     PUS_100KOHM_PU (2) - 100K Ohm Pull Up
    //     PUS_22KOHM_PU (3) - 22K Ohm Pull Up
    //   ODE (3) - Open Drain Enable Field Reset: ODE_DISABLED
    //             Select one out of next values for pad: FEC_TXD1.
    //     ODE_DISABLED (0) - Open Drain Disabled
    //     ODE_ENABLED (1) - Open Drain Enabled
    //   DSE (2-1) - Drive Strength Field Reset: DSE_120OHM
    //               Select one out of next values for pad: FEC_TXD1.
    //     DSE_DISABLED (0) - Output driver disabled.
    //     DSE_240OHM (1) - 240 Ohm
    //     DSE_120OHM (2) - 120 Ohm
    //     DSE_80OHM (3) - 80 Ohm
    HW_IOMUXC_SW_PAD_CTL_PAD_FEC_TXD1_WR(
            BF_IOMUXC_SW_PAD_CTL_PAD_FEC_TXD1_HYS(HYS_ENABLED) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_FEC_TXD1_PKE(PKE_ENABLED) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_FEC_TXD1_PUE(PUE_PULL) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_FEC_TXD1_PUS(PUS_100KOHM_PU) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_FEC_TXD1_ODE(ODE_DISABLED) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_FEC_TXD1_DSE(DSE_120OHM));

    // Config mlb.MLBDAT to pad FEC_MDC(E10)
    // FEC_MDC
    // HW_IOMUXC_SW_MUX_CTL_PAD_FEC_MDC_WR(0x00000003);
    // HW_IOMUXC_MLB_MLBDAT_IN_SELECT_INPUT_WR(0x00000000);
    // HW_IOMUXC_SW_PAD_CTL_PAD_FEC_MDC_WR(0x000001E4);
    // Mux Register:
    // IOMUXC_SW_MUX_CTL_PAD_FEC_MDC(0x53FA826C)
    //   SION (4) - Software Input On Field Reset: SION_DISABLED
    //              Force the selected mux mode Input path no matter of MUX_MODE functionality.
    //     SION_DISABLED (0) - Input Path is determined by functionality of the selected mux mode (regular).
    //     SION_ENABLED (1) - Force input path of pad FEC_MDC.
    //   MUX_MODE (2-0) - MUX Mode Select Field Reset: ALT1
    //                    Select 1 of 6 iomux modes to be used for pad: FEC_MDC.
    //     ALT0 (0) - Select mux mode: ALT0 mux port: MDC of instance: fec.
    //     ALT1 (1) - Select mux mode: ALT1 mux port: GPIO[31] of instance: gpio1.
    //     ALT2 (2) - Select mux mode: ALT2 mux port: TX5_RX0 of instance: esai1.
    //                NOTE: - Config Register IOMUXC_ESAI1_IPP_IND_SDO5_SDI0_SELECT_INPUT for mode ALT2.
    //     ALT3 (3) - Select mux mode: ALT3 mux port: MLBDAT of instance: mlb.
    //                NOTE: - Config Register IOMUXC_MLB_MLBDAT_IN_SELECT_INPUT for mode ALT3.
    //     ALT4 (4) - Select mux mode: ALT4 mux port: CE_RTC_ALARM1_TRIG of instance: rtc.
    //     ALT7 (7) - Select mux mode: ALT7 mux port: DATAOUT[1] of instance: usbphy2.
    HW_IOMUXC_SW_MUX_CTL_PAD_FEC_MDC_WR(
            BF_IOMUXC_SW_MUX_CTL_PAD_FEC_MDC_SION(SION_DISABLED) | 
            BF_IOMUXC_SW_MUX_CTL_PAD_FEC_MDC_MUX_MODE(ALT3));
    // Pad FEC_MDC is involved in Daisy Chain.
    // Input Select Register:
    // IOMUXC_MLB_MLBDAT_IN_SELECT_INPUT(0x53FA885C)
    //   DAISY (1-0) Reset: SEL_NANDF_CS3_ALT6
    //                 Selecting Pads Involved in Daisy Chain.
    //                 NOTE: Instance: mlb, In Pin: mlbdat_in
    //     SEL_NANDF_CS3_ALT6 (0) - Selecting Pad: NANDF_CS3 for Mode: ALT6.
    //     SEL_FEC_MDC_ALT3 (1) - Selecting Pad: FEC_MDC for Mode: ALT3.
    //     SEL_GPIO_2_ALT7 (2) - Selecting Pad: GPIO_2 for Mode: ALT7.
    HW_IOMUXC_MLB_MLBDAT_IN_SELECT_INPUT_WR(
            BF_IOMUXC_MLB_MLBDAT_IN_SELECT_INPUT_DAISY(SEL_NANDF_CS3_ALT6));
    // Pad Control Register:
    // IOMUXC_SW_PAD_CTL_PAD_FEC_MDC(0x53FA85E8)
    //   HVE (13) - Low / High Output Voltage Field Reset: HVE_RES0
    //              Read Only Field
    //     HVE_RES0 (0) - Reserved
    //   TEST_TS (12) - Test TS Field Reset: TEST_TS_DISABLED
    //                  Read Only Field
    //     TEST_TS_DISABLED (0) - Disabled
    //   DSE_TEST (11) - DSE Test Field Reset: DSE_TEST_NORMAL
    //                   Read Only Field
    //     DSE_TEST_NORMAL (0) - Normal
    //   HYS (8) - Hysteresis Enable Field Reset: HYS_ENABLED
    //             Select one out of next values for pad: FEC_MDC.
    //     HYS_DISABLED (0) - Hysteresis Disabled
    //     HYS_ENABLED (1) - Hysteresis Enabled
    //   PKE (7) - Pull / Keep Enable Field Reset: PKE_ENABLED
    //             Select one out of next values for pad: FEC_MDC.
    //     PKE_DISABLED (0) - Pull/Keeper Disabled
    //     PKE_ENABLED (1) - Pull/Keeper Enabled
    //   PUE (6) - Pull / Keep Select Field Reset: PUE_PULL
    //             Select one out of next values for pad: FEC_MDC.
    //     PUE_KEEP (0) - Keeper
    //     PUE_PULL (1) - Pull
    //   PUS (5-4) - Pull Up / Down Config. Field Reset: PUS_100KOHM_PU
    //               Select one out of next values for pad: FEC_MDC.
    //     PUS_360KOHM_PD (0) - 360K Ohm Pull Down
    //     PUS_75KOHM_PU (1) - 75K Ohm Pull Up
    //     PUS_100KOHM_PU (2) - 100K Ohm Pull Up
    //     PUS_22KOHM_PU (3) - 22K Ohm Pull Up
    //   ODE (3) - Open Drain Enable Field Reset: ODE_DISABLED
    //             Select one out of next values for pad: FEC_MDC.
    //     ODE_DISABLED (0) - Open Drain Disabled
    //     ODE_ENABLED (1) - Open Drain Enabled
    //   DSE (2-1) - Drive Strength Field Reset: DSE_120OHM
    //               Select one out of next values for pad: FEC_MDC.
    //     DSE_DISABLED (0) - Output driver disabled.
    //     DSE_240OHM (1) - 240 Ohm
    //     DSE_120OHM (2) - 120 Ohm
    //     DSE_80OHM (3) - 80 Ohm
    HW_IOMUXC_SW_PAD_CTL_PAD_FEC_MDC_WR(
            BF_IOMUXC_SW_PAD_CTL_PAD_FEC_MDC_HYS(HYS_ENABLED) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_FEC_MDC_PKE(PKE_ENABLED) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_FEC_MDC_PUE(PUE_PULL) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_FEC_MDC_PUS(PUS_100KOHM_PU) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_FEC_MDC_ODE(ODE_DISABLED) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_FEC_MDC_DSE(DSE_120OHM));

    // Config mlb.MLBSIG to pad GPIO_6(B6)
    // HW_IOMUXC_SW_MUX_CTL_PAD_GPIO_6_WR(0x00000007);
    // HW_IOMUXC_MLB_MLBSIG_IN_SELECT_INPUT_WR(0x00000000);
    // HW_IOMUXC_SW_PAD_CTL_PAD_GPIO_6_WR(0x000001C4);
    // Mux Register:
    // IOMUXC_SW_MUX_CTL_PAD_GPIO_6(0x53FA8324)
    //   SION (4) - Software Input On Field Reset: SION_DISABLED
    //              Force the selected mux mode Input path no matter of MUX_MODE functionality.
    //     SION_DISABLED (0) - Input Path is determined by functionality of the selected mux mode (regular).
    //     SION_ENABLED (1) - Force input path of pad GPIO_6.
    //   MUX_MODE (2-0) - MUX Mode Select Field Reset: ALT1
    //                    Select 1 of 8 iomux modes to be used for pad: GPIO_6.
    //     ALT0 (0) - Select mux mode: ALT0 mux port: SCKT of instance: esai1.
    //                NOTE: - Config Register IOMUXC_ESAI1_IPP_IND_SCKT_SELECT_INPUT for mode ALT0.
    //     ALT1 (1) - Select mux mode: ALT1 mux port: GPIO[6] of instance: gpio1.
    //     ALT2 (2) - Select mux mode: ALT2 mux port: SDA of instance: i2c3.
    //                NOTE: - Config Register IOMUXC_I2C3_IPP_SDA_IN_SELECT_INPUT for mode ALT2.
    //     ALT3 (3) - Select mux mode: ALT3 mux port: CCM_OUT_0 of instance: ccm.
    //     ALT4 (4) - Select mux mode: ALT4 mux port: CSU_INT_DEB of instance: csu.
    //     ALT5 (5) - Select mux mode: ALT5 mux port: OBSRV_INT_OUT1 of instance: observe_mux.
    //     ALT6 (6) - Select mux mode: ALT6 mux port: LCTL of instance: esdhc2.
    //     ALT7 (7) - Select mux mode: ALT7 mux port: MLBSIG of instance: mlb.
    //                NOTE: - Config Register IOMUXC_MLB_MLBSIG_IN_SELECT_INPUT for mode ALT7.
    HW_IOMUXC_SW_MUX_CTL_PAD_GPIO_6_WR(
            BF_IOMUXC_SW_MUX_CTL_PAD_GPIO_6_SION(SION_DISABLED) | 
            BF_IOMUXC_SW_MUX_CTL_PAD_GPIO_6_MUX_MODE(ALT7));
    // Pad GPIO_6 is involved in Daisy Chain.
    // Input Select Register:
    // IOMUXC_MLB_MLBSIG_IN_SELECT_INPUT(0x53FA8860)
    //   DAISY (1-0) Reset: SEL_NANDF_CS2_ALT6
    //                 Selecting Pads Involved in Daisy Chain.
    //                 NOTE: Instance: mlb, In Pin: mlbsig_in
    //     SEL_NANDF_CS2_ALT6 (0) - Selecting Pad: NANDF_CS2 for Mode: ALT6.
    //     SEL_FEC_RXD1_ALT3 (1) - Selecting Pad: FEC_RXD1 for Mode: ALT3.
    //     SEL_GPIO_6_ALT7 (2) - Selecting Pad: GPIO_6 for Mode: ALT7.
    HW_IOMUXC_MLB_MLBSIG_IN_SELECT_INPUT_WR(
            BF_IOMUXC_MLB_MLBSIG_IN_SELECT_INPUT_DAISY(SEL_NANDF_CS2_ALT6));
    // Pad Control Register:
    // IOMUXC_SW_PAD_CTL_PAD_GPIO_6(0x53FA86B4)
    //   HVE (13) - Low / High Output Voltage Field Reset: HVE_RES0
    //              Read Only Field
    //     HVE_RES0 (0) - Reserved
    //   TEST_TS (12) - Test TS Field Reset: TEST_TS_DISABLED
    //                  Read Only Field
    //     TEST_TS_DISABLED (0) - Disabled
    //   DSE_TEST (11) - DSE Test Field Reset: DSE_TEST_NORMAL
    //                   Read Only Field
    //     DSE_TEST_NORMAL (0) - Normal
    //   HYS (8) - Hysteresis Enable Field Reset: HYS_ENABLED
    //             Select one out of next values for pad: GPIO_6.
    //     HYS_DISABLED (0) - Hysteresis Disabled
    //     HYS_ENABLED (1) - Hysteresis Enabled
    //   PKE (7) - Pull / Keep Enable Field Reset: PKE_ENABLED
    //             Select one out of next values for pad: GPIO_6.
    //     PKE_DISABLED (0) - Pull/Keeper Disabled
    //     PKE_ENABLED (1) - Pull/Keeper Enabled
    //   PUE (6) - Pull / Keep Select Field Reset: PUE_PULL
    //             Select one out of next values for pad: GPIO_6.
    //     PUE_KEEP (0) - Keeper
    //     PUE_PULL (1) - Pull
    //   PUS (5-4) - Pull Up / Down Config. Field Reset: PUS_360KOHM_PD
    //               Select one out of next values for pad: GPIO_6.
    //     PUS_360KOHM_PD (0) - 360K Ohm Pull Down
    //     PUS_75KOHM_PU (1) - 75K Ohm Pull Up
    //     PUS_100KOHM_PU (2) - 100K Ohm Pull Up
    //     PUS_22KOHM_PU (3) - 22K Ohm Pull Up
    //   ODE (3) - Open Drain Enable Field Reset: ODE_DISABLED
    //             Select one out of next values for pad: GPIO_6.
    //     ODE_DISABLED (0) - Open Drain Disabled
    //     ODE_ENABLED (1) - Open Drain Enabled
    //   DSE (2-1) - Drive Strength Field Reset: DSE_120OHM
    //               Select one out of next values for pad: GPIO_6.
    //     DSE_DISABLED (0) - Output driver disabled.
    //     DSE_240OHM (1) - 240 Ohm
    //     DSE_120OHM (2) - 120 Ohm
    //     DSE_80OHM (3) - 80 Ohm
    HW_IOMUXC_SW_PAD_CTL_PAD_GPIO_6_WR(
            BF_IOMUXC_SW_PAD_CTL_PAD_GPIO_6_HYS(HYS_ENABLED) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_GPIO_6_PKE(PKE_ENABLED) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_GPIO_6_PUE(PUE_PULL) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_GPIO_6_PUS(PUS_360KOHM_PD) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_GPIO_6_ODE(ODE_DISABLED) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_GPIO_6_DSE(DSE_120OHM));
}
