include $(SDK_ROOT)/mk/common.mk


# Recurse into the filesystem.
SUBDIRS = filesystem

# Compile these sources directly.
SOURCES = \
	profile/profile.c \
	ioexpander/max7310.c


include $(SDK_ROOT)/mk/targets.mk
