include $(SDK_ROOT)/mk/common.mk


C_SOURCES = \
	arrangelongfilename.c \
	checkmode.c \
	convert_itoa.c \
	createdirectoryrecord.c \
	createshortdirrecord.c \
	dbcstotwobytestring.c \
	discardtrailigperiods.c \
	extractfilename.c \
	extractpath.c \
	findfreerecord.c \
	findnextsector.c \
	fstrcpy.c \
	getchar.c \
	getname.c \
	isdirectoryempty.c \
	isshortnamevalid.c \
	longdirmatch.c \
	matchdirrecord.c \
	putchar.c \
	reentrant_section.c \
	searchfreerecord.c \
	setcwd.c \
	setshortfilename.c \
	shortdirmatch.c \
	strlength.c



include $(SDK_ROOT)/mk/targets.mk
