include $(SDK_ROOT)/mk/common.mk


C_SOURCES = \
	changepath.c \
	chdir.c \
	chdirw.c \
	checkforvalidrecord.c \
	deletetree.c \
	feof.c \
	ferror.c \
	findfirst.c \
	findnext.c \
	fopen.c \
	fopenw.c \
	fremove.c \
	fremovew.c \
	frename.c \
	ftell.c \
	getcwd.c \
	getvolumelabel.c \
	longfilename.c \
	mkdir.c \
	mkdirw.c \
	rmdir.c \
	rmdirw.c \
	searchdirectory.c \
	searchfile.c \
	sethandleforsearch.c



include $(SDK_ROOT)/mk/targets.mk
