/*
 * Copyright (C) 2012, Freescale Semiconductor, Inc. All Rights Reserved.
 * THIS SOURCE CODE IS CONFIDENTIAL AND PROPRIETARY AND MAY NOT
 * BE USED OR DISTRIBUTED WITHOUT THE WRITTEN PERMISSION OF
 * Freescale Semiconductor, Inc.
*/

#include <io.h>
#include <iomux_define.h>
#include <iomux_register.h>

// Function to config iomux for instance spdif.
void iomux_config_spdif(void)
{
    // Config spdif_IN1 to pad KEY_COL3(U5)
    writel(0x00000006, IOMUXC_SW_MUX_CTL_PAD_KEY_COL3); // SION_DISABLED, ALT6
    writel(0x00000002, IOMUXC_SPDIF_SPDIF_IN1_SELECT_INPUT);    // SEL_KEY_COL3_ALT6
    // HYS_DISABLED, PUS_100KOHM_PD, PUE_PULL, PKE_ENABLED, ODE_DISABLED, SPD_TBD, DSE_DISABLED, SRE_SLOW
    writel(0x00003000, IOMUXC_SW_PAD_CTL_PAD_KEY_COL3);

    // Config spdif_OUT1 to pad GPIO_19(P5)
    writel(0x00000004, IOMUXC_SW_MUX_CTL_PAD_GPIO_17);  // SION_DISABLED, ALT4
    // HYS_DISABLED, PUS_100KOHM_PD, PUE_KEEP, PKE_DISABLED, ODE_DISABLED, SPD_100MHZ, DSE_40OHM, SRE_FAST
    writel(0x000000B1, IOMUXC_SW_PAD_CTL_PAD_GPIO_17);

    // Config spdif_PLOCK to pad ENET_MDIO(V23)
    writel(0x00000006, IOMUXC_SW_MUX_CTL_PAD_ENET_MDIO);    // SION_DISABLED, ALT6
    // HYS_DISABLED, PUS_100KOHM_PD, PUE_KEEP, PKE_DISABLED, ODE_DISABLED, SPD_100MHZ, DSE_40OHM, SRE_FAST
    writel(0x000000B1, IOMUXC_SW_PAD_CTL_PAD_ENET_MDIO);

    // Config spdif_SPDIF_EXTCLK to pad RGMII_TXC(D21)
    writel(0x00000002, IOMUXC_SW_MUX_CTL_PAD_RGMII_TXC);    // SION_DISABLED, ALT2
    writel(0x00000000, IOMUXC_SPDIF_TX_CLK2_SELECT_INPUT);  // SEL_RGMII_TXC_ALT2
    // DDR_SEL_RES0, DDR_INPUT_CMOS, HYS_DISABLED, PUS_100KOHM_PD, PUE_PULL, PKE_ENABLED, ODT_OFF, DSE_DISABLED
    writel(0x00003000, IOMUXC_SW_PAD_CTL_PAD_RGMII_TXC);
    writel(0x00080000, IOMUXC_SW_PAD_CTL_GRP_DDR_TYPE_RGMII);   // DDR_SEL_LPDDR2

    // Config spdif_SRCLK to pad ENET_REF_CLK(V22)
    writel(0x00000006, IOMUXC_SW_MUX_CTL_PAD_ENET_REF_CLK); // SION_DISABLED, ALT6
    // HYS_DISABLED, PUS_100KOHM_PD, PUE_KEEP, PKE_DISABLED, ODE_DISABLED, SPD_100MHZ, DSE_40OHM, SRE_FAST
    writel(0x000000B1, IOMUXC_SW_PAD_CTL_PAD_ENET_REF_CLK);
}
