include $(SDK_ROOT)/mk/common.mk


C_SOURCES = \
	arrangefilename.c \
	changetorootdirectory.c \
	clearcluster.c \
	createdirectory.c \
	deletecontent.c \
	deleterecord.c \
	fastopen.c \
	fcreate.c \
	fflush.c \
	filegetattrib.c \
	filegetattribhandle.c \
	filegetdate.c \
	filesetattrib.c \
	filesetdate.c \
	fread_bypass.c \
	fread.c \
	fseek.c \
	fwrite.c \
	getfilesize.c \
	getshortfilename.c \
	readrootdirrecord.c \
	updatefilesize.c



include $(SDK_ROOT)/mk/targets.mk
