/*
 * Copyright (C) 2012, Freescale Semiconductor, Inc. All Rights Reserved
 * THIS SOURCE CODE IS CONFIDENTIAL AND PROPRIETARY AND MAY NOT
 * BE USED OR DISTRIBUTED WITHOUT THE WRITTEN PERMISSION OF
 * Freescale Semiconductor, Inc.
*/

// File: gpio7_iomux_config.c

/* ------------------------------------------------------------------------------
 * <auto-generated>
 *     This code was generated by a tool.
 *     Runtime Version:3.3.2.0
 *
 *     Changes to this file may cause incorrect behavior and will be lost if
 *     the code is regenerated.
 * </auto-generated>
 * ------------------------------------------------------------------------------
*/

#include "iomux_config.h"
#include "iomux_define.h"
#include "registers/regsiomuxc.h"

// Function to configure IOMUXC for gpio7 module.
void gpio7_iomux_config(void)
{
    // Config gpio7.GPIO[11] to pad GPIO_16(C6)
    // HW_IOMUXC_SW_MUX_CTL_PAD_GPIO_16_WR(0x00000001);
    // HW_IOMUXC_SW_PAD_CTL_PAD_GPIO_16_WR(0x000001C4);
    // Mux Register:
    // IOMUXC_SW_MUX_CTL_PAD_GPIO_16(0x53FA833C)
    //   SION (4) - Software Input On Field Reset: SION_DISABLED
    //              Force the selected mux mode Input path no matter of MUX_MODE functionality.
    //     SION_DISABLED (0) - Input Path is determined by functionality of the selected mux mode (regular).
    //     SION_ENABLED (1) - Force input path of pad GPIO_16.
    //   MUX_MODE (2-0) - MUX Mode Select Field Reset: ALT1
    //                    Select 1 of 8 iomux modes to be used for pad: GPIO_16.
    //     ALT0 (0) - Select mux mode: ALT0 mux port: TX3_RX2 of instance: esai1.
    //                NOTE: - Config Register IOMUXC_ESAI1_IPP_IND_SDO3_SDI2_SELECT_INPUT for mode ALT0.
    //     ALT1 (1) - Select mux mode: ALT1 mux port: GPIO[11] of instance: gpio7.
    //     ALT2 (2) - Select mux mode: ALT2 mux port: PWRFAIL_INT of instance: tzic.
    //     ALT3 (3) - Select mux mode: ALT3 mux port: PMU_IRQ_B of instance: p_platform_ne_32k_256k.
    //     ALT4 (4) - Select mux mode: ALT4 mux port: CE_RTC_EXT_TRIG1 of instance: rtc.
    //     ALT5 (5) - Select mux mode: ALT5 mux port: IN1 of instance: spdif.
    //                NOTE: - Config Register IOMUXC_SPDIF_SPDIF_IN1_SELECT_INPUT for mode ALT5.
    //     ALT6 (6) - Select mux mode: ALT6 mux port: SDA of instance: i2c3.
    //                NOTE: - Config Register IOMUXC_I2C3_IPP_SDA_IN_SELECT_INPUT for mode ALT6.
    //     ALT7 (7) - Select mux mode: ALT7 mux port: DE_B of instance: sjc.
    HW_IOMUXC_SW_MUX_CTL_PAD_GPIO_16_WR(
            BF_IOMUXC_SW_MUX_CTL_PAD_GPIO_16_SION(SION_DISABLED) | 
            BF_IOMUXC_SW_MUX_CTL_PAD_GPIO_16_MUX_MODE(ALT1));
    // Pad Control Register:
    // IOMUXC_SW_PAD_CTL_PAD_GPIO_16(0x53FA86CC)
    //   HVE (13) - Low / High Output Voltage Field Reset: HVE_RES0
    //              Read Only Field
    //     HVE_RES0 (0) - Reserved
    //   TEST_TS (12) - Test TS Field Reset: TEST_TS_DISABLED
    //                  Read Only Field
    //     TEST_TS_DISABLED (0) - Disabled
    //   DSE_TEST (11) - DSE Test Field Reset: DSE_TEST_NORMAL
    //                   Read Only Field
    //     DSE_TEST_NORMAL (0) - Normal
    //   HYS (8) - Hysteresis Enable Field Reset: HYS_ENABLED
    //             Select one out of next values for pad: GPIO_16.
    //     HYS_DISABLED (0) - Hysteresis Disabled
    //     HYS_ENABLED (1) - Hysteresis Enabled
    //   PKE (7) - Pull / Keep Enable Field Reset: PKE_ENABLED
    //             Select one out of next values for pad: GPIO_16.
    //     PKE_DISABLED (0) - Pull/Keeper Disabled
    //     PKE_ENABLED (1) - Pull/Keeper Enabled
    //   PUE (6) - Pull / Keep Select Field Reset: PUE_PULL
    //             Select one out of next values for pad: GPIO_16.
    //     PUE_KEEP (0) - Keeper
    //     PUE_PULL (1) - Pull
    //   PUS (5-4) - Pull Up / Down Config. Field Reset: PUS_360KOHM_PD
    //               Select one out of next values for pad: GPIO_16.
    //     PUS_360KOHM_PD (0) - 360K Ohm Pull Down
    //     PUS_75KOHM_PU (1) - 75K Ohm Pull Up
    //     PUS_100KOHM_PU (2) - 100K Ohm Pull Up
    //     PUS_22KOHM_PU (3) - 22K Ohm Pull Up
    //   ODE (3) - Open Drain Enable Field Reset: ODE_DISABLED
    //             Select one out of next values for pad: GPIO_16.
    //     ODE_DISABLED (0) - Open Drain Disabled
    //     ODE_ENABLED (1) - Open Drain Enabled
    //   DSE (2-1) - Drive Strength Field Reset: DSE_120OHM
    //               Select one out of next values for pad: GPIO_16.
    //     DSE_DISABLED (0) - Output driver disabled.
    //     DSE_240OHM (1) - 240 Ohm
    //     DSE_120OHM (2) - 120 Ohm
    //     DSE_80OHM (3) - 80 Ohm
    HW_IOMUXC_SW_PAD_CTL_PAD_GPIO_16_WR(
            BF_IOMUXC_SW_PAD_CTL_PAD_GPIO_16_HYS(HYS_ENABLED) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_GPIO_16_PKE(PKE_ENABLED) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_GPIO_16_PUE(PUE_PULL) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_GPIO_16_PUS(PUS_360KOHM_PD) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_GPIO_16_ODE(ODE_DISABLED) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_GPIO_16_DSE(DSE_120OHM));

    // Config gpio7.GPIO[2] to pad PATA_INTRQ(K5)
    // HW_IOMUXC_SW_MUX_CTL_PAD_PATA_INTRQ_WR(0x00000001);
    // HW_IOMUXC_SW_PAD_CTL_PAD_PATA_INTRQ_WR(0x000001E4);
    // Mux Register:
    // IOMUXC_SW_MUX_CTL_PAD_PATA_INTRQ(0x53FA8280)
    //   SION (4) - Software Input On Field Reset: SION_DISABLED
    //              Force the selected mux mode Input path no matter of MUX_MODE functionality.
    //     SION_DISABLED (0) - Input Path is determined by functionality of the selected mux mode (regular).
    //     SION_ENABLED (1) - Force input path of pad PATA_INTRQ.
    //   MUX_MODE (2-0) - MUX Mode Select Field Reset: ALT1
    //                    Select 1 of 6 iomux modes to be used for pad: PATA_INTRQ.
    //     ALT0 (0) - Select mux mode: ALT0 mux port: INTRQ of instance: pata.
    //     ALT1 (1) - Select mux mode: ALT1 mux port: GPIO[2] of instance: gpio7.
    //     ALT3 (3) - Select mux mode: ALT3 mux port: CTS of instance: uart2.
    //                NOTE: - Config Register IOMUXC_UART2_IPP_UART_RTS_B_SELECT_INPUT for mode ALT3.
    //     ALT4 (4) - Select mux mode: ALT4 mux port: TXCAN of instance: can1.
    //     ALT5 (5) - Select mux mode: ALT5 mux port: CCM_OUT_2 of instance: ccm.
    //     ALT7 (7) - Select mux mode: ALT7 mux port: DATAOUT[6] of instance: usbphy2.
    HW_IOMUXC_SW_MUX_CTL_PAD_PATA_INTRQ_WR(
            BF_IOMUXC_SW_MUX_CTL_PAD_PATA_INTRQ_SION(SION_DISABLED) | 
            BF_IOMUXC_SW_MUX_CTL_PAD_PATA_INTRQ_MUX_MODE(ALT1));
    // Pad Control Register:
    // IOMUXC_SW_PAD_CTL_PAD_PATA_INTRQ(0x53FA8600)
    //   HVE (13) - Low / High Output Voltage Field Reset: HVE_RES0
    //              Read Only Field
    //     HVE_RES0 (0) - Reserved
    //   TEST_TS (12) - Test TS Field Reset: TEST_TS_DISABLED
    //                  Read Only Field
    //     TEST_TS_DISABLED (0) - Disabled
    //   DSE_TEST (11) - DSE Test Field Reset: DSE_TEST_NORMAL
    //                   Read Only Field
    //     DSE_TEST_NORMAL (0) - Normal
    //   HYS (8) - Hysteresis Enable Field Reset: HYS_ENABLED
    //             Select one out of next values for pad: PATA_INTRQ.
    //     HYS_DISABLED (0) - Hysteresis Disabled
    //     HYS_ENABLED (1) - Hysteresis Enabled
    //   PKE (7) - Pull / Keep Enable Field Reset: PKE_ENABLED
    //             Select one out of next values for pad: PATA_INTRQ.
    //     PKE_DISABLED (0) - Pull/Keeper Disabled
    //     PKE_ENABLED (1) - Pull/Keeper Enabled
    //   PUE (6) - Pull / Keep Select Field Reset: PUE_PULL
    //             Select one out of next values for pad: PATA_INTRQ.
    //     PUE_KEEP (0) - Keeper
    //     PUE_PULL (1) - Pull
    //   PUS (5-4) - Pull Up / Down Config. Field Reset: PUS_100KOHM_PU
    //               Select one out of next values for pad: PATA_INTRQ.
    //     PUS_360KOHM_PD (0) - 360K Ohm Pull Down
    //     PUS_75KOHM_PU (1) - 75K Ohm Pull Up
    //     PUS_100KOHM_PU (2) - 100K Ohm Pull Up
    //     PUS_22KOHM_PU (3) - 22K Ohm Pull Up
    //   ODE (3) - Open Drain Enable Field Reset: ODE_DISABLED
    //             Select one out of next values for pad: PATA_INTRQ.
    //     ODE_DISABLED (0) - Open Drain Disabled
    //     ODE_ENABLED (1) - Open Drain Enabled
    //   DSE (2-1) - Drive Strength Field Reset: DSE_120OHM
    //               Select one out of next values for pad: PATA_INTRQ.
    //     DSE_DISABLED (0) - Output driver disabled.
    //     DSE_240OHM (1) - 240 Ohm
    //     DSE_120OHM (2) - 120 Ohm
    //     DSE_80OHM (3) - 80 Ohm
    HW_IOMUXC_SW_PAD_CTL_PAD_PATA_INTRQ_WR(
            BF_IOMUXC_SW_PAD_CTL_PAD_PATA_INTRQ_HYS(HYS_ENABLED) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_PATA_INTRQ_PKE(PKE_ENABLED) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_PATA_INTRQ_PUE(PUE_PULL) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_PATA_INTRQ_PUS(PUS_100KOHM_PU) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_PATA_INTRQ_ODE(ODE_DISABLED) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_PATA_INTRQ_DSE(DSE_120OHM));
}
