/*
 * Copyright (C) 2012, Freescale Semiconductor, Inc. All Rights Reserved.
 * THIS SOURCE CODE IS CONFIDENTIAL AND PROPRIETARY AND MAY NOT
 * BE USED OR DISTRIBUTED WITHOUT THE WRITTEN PERMISSION OF
 * Freescale Semiconductor, Inc.
*/

// File: fec_iomux_config.c

/* ------------------------------------------------------------------------------
 * <auto-generated>
 *     This code was generated by a tool.
 *     Runtime Version:3.3.2.1
 *
 *     Changes to this file may cause incorrect behavior and will be lost if
 *     the code is regenerated.
 * </auto-generated>
 * ------------------------------------------------------------------------------
*/

#include "iomux_config.h"
#include "iomux_define.h"
#include "registers/regsiomuxc.h"

// Function to configure IOMUXC for fec module.
void fec_iomux_config(void)
{
    // Config fec.MDC to pad FEC_MDC(AA7)
    // HW_IOMUXC_SW_MUX_CTL_PAD_FEC_MDC_WR(0x00000000);
    // HW_IOMUXC_SW_PAD_CTL_PAD_FEC_MDC_WR(0x000110B0);
    // Mux Register:
    // IOMUXC_SW_MUX_CTL_PAD_FEC_MDC(0x020E012C)
    //   SION [4] - Software Input On Field Reset: SION_DISABLED
    //              Force the selected mux mode Input path no matter of MUX_MODE functionality.
    //     SION_DISABLED (0) - Input Path is determined by functionality of the selected mux mode (regular).
    //     SION_ENABLED (1) - Force input path of pad FEC_MDC.
    //   MUX_MODE [2:0] - MUX Mode Select Field Reset: ALT5
    //                    Select 1 of 8 iomux modes to be used for pad: FEC_MDC.
    //     ALT0 (0) - Select mux mode: ALT0 mux port: MDC of instance: fec.
    //     ALT1 (1) - Select mux mode: ALT1 mux port: DAT4 of instance: usdhc4.
    //                NOTE: - Config Register IOMUXC_USDHC4_IPP_DAT4_IN_SELECT_INPUT for mode ALT1.
    //     ALT2 (2) - Select mux mode: ALT2 mux port: AUDIO_CLK_OUT of instance: audmux.
    //     ALT3 (3) - Select mux mode: ALT3 mux port: RST of instance: usdhc1.
    //     ALT4 (4) - Select mux mode: ALT4 mux port: RST of instance: usdhc3.
    //     ALT5 (5) - Select mux mode: ALT5 mux port: GPIO[23] of instance: gpio4.
    HW_IOMUXC_SW_MUX_CTL_PAD_FEC_MDC_WR(
            BF_IOMUXC_SW_MUX_CTL_PAD_FEC_MDC_SION(SION_DISABLED) | 
            BF_IOMUXC_SW_MUX_CTL_PAD_FEC_MDC_MUX_MODE(ALT0));
    // Pad Control Register:
    // IOMUXC_SW_PAD_CTL_PAD_FEC_MDC(0x020E041C)
    //   LVE [22] - Low Voltage Enable Field Reset: LVE_DISABLED
    //              Select one out of next values for pad: FEC_MDC.
    //     LVE_DISABLED (0) - High Voltage
    //     LVE_ENABLED (1) - Low Voltage
    //   HYS [16] - Hysteresis Enable Field Reset: HYS_ENABLED
    //              Select one out of next values for pad: FEC_MDC.
    //     HYS_DISABLED (0) - Hysteresis Disabled
    //     HYS_ENABLED (1) - Hysteresis Enabled
    //   PUS [15:14] - Pull Up / Down Configure Field Reset: PUS_100KOHM_PD
    //                 Select one out of next values for pad: FEC_MDC.
    //     PUS_100KOHM_PD (0) - 100K Ohm Pull Down
    //     PUS_47KOHM_PU (1) - 47K Ohm Pull Up
    //     PUS_100KOHM_PU (2) - 100K Ohm Pull Up
    //     PUS_22KOHM_PU (3) - 22K Ohm Pull Up
    //   PUE [13] - Pull / Keep Select Field Reset: PUE_KEEP
    //              Select one out of next values for pad: FEC_MDC.
    //     PUE_KEEP (0) - Keeper
    //     PUE_PULL (1) - Pull
    //   PKE [12] - Pull / Keep Enable Field Reset: PKE_ENABLED
    //              Select one out of next values for pad: FEC_MDC.
    //     PKE_DISABLED (0) - Pull/Keeper Disabled
    //     PKE_ENABLED (1) - Pull/Keeper Enabled
    //   ODE [11] - Open Drain Enable Field Reset: ODE_DISABLED
    //              Select one out of next values for pad: FEC_MDC.
    //     ODE_DISABLED (0) - Open Drain Disabled
    //     ODE_ENABLED (1) - Open Drain Enabled
    //   SPEED [7:6] - Speed Field Reset: SPD_100MHZ
    //                 Select one out of next values for pad: FEC_MDC.
    //     SPD_TBD (0) - TBD
    //     SPD_50MHZ (1) - Low(50 MHz)
    //     SPD_100MHZ (2) - Medium(100 MHz)
    //     SPD_200MHZ (3) - Maximum(200 MHz)
    //   DSE [5:3] - Drive Strength Field Reset: DSE_40OHM
    //               Select one out of next values for pad: FEC_MDC.
    //     DSE_DISABLED (0) - Output driver disabled.
    //     DSE_240OHM (1) - 240 Ohm
    //     DSE_120OHM (2) - 120 Ohm
    //     DSE_80OHM (3) - 80 Ohm
    //     DSE_60OHM (4) - 60 Ohm
    //     DSE_48OHM (5) - 48 Ohm
    //     DSE_40OHM (6) - 40 Ohm
    //     DSE_34OHM (7) - 34 Ohm
    //   SRE [0] - Slew Rate Field Reset: SRE_SLOW
    //             Select one out of next values for pad: FEC_MDC.
    //     SRE_SLOW (0) - Slow Slew Rate
    //     SRE_FAST (1) - Fast Slew Rate
    HW_IOMUXC_SW_PAD_CTL_PAD_FEC_MDC_WR(
            BF_IOMUXC_SW_PAD_CTL_PAD_FEC_MDC_LVE(LVE_DISABLED) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_FEC_MDC_HYS(HYS_ENABLED) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_FEC_MDC_PUS(PUS_100KOHM_PD) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_FEC_MDC_PUE(PUE_KEEP) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_FEC_MDC_PKE(PKE_ENABLED) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_FEC_MDC_ODE(ODE_DISABLED) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_FEC_MDC_SPEED(SPD_100MHZ) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_FEC_MDC_DSE(DSE_40OHM) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_FEC_MDC_SRE(SRE_SLOW));

    // Config fec.MDIO to pad FEC_MDIO(AB7)
    // HW_IOMUXC_SW_MUX_CTL_PAD_FEC_MDIO_WR(0x00000000);
    // HW_IOMUXC_FEC_FEC_MDI_SELECT_INPUT_WR(0x00000001);
    // HW_IOMUXC_SW_PAD_CTL_PAD_FEC_MDIO_WR(0x000110B0);
    // Mux Register:
    // IOMUXC_SW_MUX_CTL_PAD_FEC_MDIO(0x020E0130)
    //   SION [4] - Software Input On Field Reset: SION_DISABLED
    //              Force the selected mux mode Input path no matter of MUX_MODE functionality.
    //     SION_DISABLED (0) - Input Path is determined by functionality of the selected mux mode (regular).
    //     SION_ENABLED (1) - Force input path of pad FEC_MDIO.
    //   MUX_MODE [2:0] - MUX Mode Select Field Reset: ALT5
    //                    Select 1 of 8 iomux modes to be used for pad: FEC_MDIO.
    //     ALT0 (0) - Select mux mode: ALT0 mux port: MDIO of instance: fec.
    //                NOTE: - Config Register IOMUXC_FEC_FEC_MDI_SELECT_INPUT for mode ALT0.
    //     ALT1 (1) - Select mux mode: ALT1 mux port: CLK of instance: usdhc4.
    //                NOTE: - Config Register IOMUXC_USDHC4_IPP_CARD_CLK_IN_SELECT_INPUT for mode ALT1.
    //     ALT2 (2) - Select mux mode: ALT2 mux port: AUD6_RXFS of instance: audmux.
    //                NOTE: - Config Register IOMUXC_AUDMUX_P6_INPUT_RXFS_AMX_SELECT_INPUT for mode ALT2.
    //     ALT3 (3) - Select mux mode: ALT3 mux port: SS0 of instance: ecspi4.
    //                NOTE: - Config Register IOMUXC_ECSPI4_IPP_IND_SS_B_0_SELECT_INPUT for mode ALT3.
    //     ALT4 (4) - Select mux mode: ALT4 mux port: CAPIN1 of instance: gpt.
    //                NOTE: - Config Register IOMUXC_GPT_IPP_IND_CAPIN1_SELECT_INPUT for mode ALT4.
    //     ALT5 (5) - Select mux mode: ALT5 mux port: GPIO[20] of instance: gpio4.
    HW_IOMUXC_SW_MUX_CTL_PAD_FEC_MDIO_WR(
            BF_IOMUXC_SW_MUX_CTL_PAD_FEC_MDIO_SION(SION_DISABLED) | 
            BF_IOMUXC_SW_MUX_CTL_PAD_FEC_MDIO_MUX_MODE(ALT0));
    // Pad FEC_MDIO is involved in Daisy Chain.
    // Input Select Register:
    // IOMUXC_FEC_FEC_MDI_SELECT_INPUT(0x020E06F4)
    //   DAISY [1:0] Reset: SEL_AUD_RXFS_ALT3
    //                 Selecting Pads Involved in Daisy Chain.
    //                 NOTE: Instance: fec,   In Pin: fec_mdi
    //     SEL_AUD_RXFS_ALT3 (0) - Selecting Pad: AUD_RXFS for Mode: ALT3.
    //     SEL_FEC_MDIO_ALT0 (1) - Selecting Pad: FEC_MDIO for Mode: ALT0.
    //     SEL_SD1_CLK_ALT1 (2) - Selecting Pad: SD1_CLK for Mode: ALT1.
    HW_IOMUXC_FEC_FEC_MDI_SELECT_INPUT_WR(
            BF_IOMUXC_FEC_FEC_MDI_SELECT_INPUT_DAISY(SEL_FEC_MDIO_ALT0));
    // Pad Control Register:
    // IOMUXC_SW_PAD_CTL_PAD_FEC_MDIO(0x020E0420)
    //   LVE [22] - Low Voltage Enable Field Reset: LVE_DISABLED
    //              Select one out of next values for pad: FEC_MDIO.
    //     LVE_DISABLED (0) - High Voltage
    //     LVE_ENABLED (1) - Low Voltage
    //   HYS [16] - Hysteresis Enable Field Reset: HYS_ENABLED
    //              Select one out of next values for pad: FEC_MDIO.
    //     HYS_DISABLED (0) - Hysteresis Disabled
    //     HYS_ENABLED (1) - Hysteresis Enabled
    //   PUS [15:14] - Pull Up / Down Configure Field Reset: PUS_100KOHM_PD
    //                 Select one out of next values for pad: FEC_MDIO.
    //     PUS_100KOHM_PD (0) - 100K Ohm Pull Down
    //     PUS_47KOHM_PU (1) - 47K Ohm Pull Up
    //     PUS_100KOHM_PU (2) - 100K Ohm Pull Up
    //     PUS_22KOHM_PU (3) - 22K Ohm Pull Up
    //   PUE [13] - Pull / Keep Select Field Reset: PUE_KEEP
    //              Select one out of next values for pad: FEC_MDIO.
    //     PUE_KEEP (0) - Keeper
    //     PUE_PULL (1) - Pull
    //   PKE [12] - Pull / Keep Enable Field Reset: PKE_ENABLED
    //              Select one out of next values for pad: FEC_MDIO.
    //     PKE_DISABLED (0) - Pull/Keeper Disabled
    //     PKE_ENABLED (1) - Pull/Keeper Enabled
    //   ODE [11] - Open Drain Enable Field Reset: ODE_DISABLED
    //              Select one out of next values for pad: FEC_MDIO.
    //     ODE_DISABLED (0) - Open Drain Disabled
    //     ODE_ENABLED (1) - Open Drain Enabled
    //   SPEED [7:6] - Speed Field Reset: SPD_100MHZ
    //                 Select one out of next values for pad: FEC_MDIO.
    //     SPD_TBD (0) - TBD
    //     SPD_50MHZ (1) - Low(50 MHz)
    //     SPD_100MHZ (2) - Medium(100 MHz)
    //     SPD_200MHZ (3) - Maximum(200 MHz)
    //   DSE [5:3] - Drive Strength Field Reset: DSE_40OHM
    //               Select one out of next values for pad: FEC_MDIO.
    //     DSE_DISABLED (0) - Output driver disabled.
    //     DSE_240OHM (1) - 240 Ohm
    //     DSE_120OHM (2) - 120 Ohm
    //     DSE_80OHM (3) - 80 Ohm
    //     DSE_60OHM (4) - 60 Ohm
    //     DSE_48OHM (5) - 48 Ohm
    //     DSE_40OHM (6) - 40 Ohm
    //     DSE_34OHM (7) - 34 Ohm
    //   SRE [0] - Slew Rate Field Reset: SRE_SLOW
    //             Select one out of next values for pad: FEC_MDIO.
    //     SRE_SLOW (0) - Slow Slew Rate
    //     SRE_FAST (1) - Fast Slew Rate
    HW_IOMUXC_SW_PAD_CTL_PAD_FEC_MDIO_WR(
            BF_IOMUXC_SW_PAD_CTL_PAD_FEC_MDIO_LVE(LVE_DISABLED) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_FEC_MDIO_HYS(HYS_ENABLED) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_FEC_MDIO_PUS(PUS_100KOHM_PD) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_FEC_MDIO_PUE(PUE_KEEP) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_FEC_MDIO_PKE(PKE_ENABLED) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_FEC_MDIO_ODE(ODE_DISABLED) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_FEC_MDIO_SPEED(SPD_100MHZ) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_FEC_MDIO_DSE(DSE_40OHM) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_FEC_MDIO_SRE(SRE_SLOW));

    // Config fec.RDATA[0] to pad FEC_RXD0(AA10)
    // HW_IOMUXC_SW_MUX_CTL_PAD_FEC_RXD0_WR(0x00000000);
    // HW_IOMUXC_FEC_FEC_RDATA_0_SELECT_INPUT_WR(0x00000000);
    // HW_IOMUXC_SW_PAD_CTL_PAD_FEC_RXD0_WR(0x000110B0);
    // Mux Register:
    // IOMUXC_SW_MUX_CTL_PAD_FEC_RXD0(0x020E013C)
    //   SION [4] - Software Input On Field Reset: SION_DISABLED
    //              Force the selected mux mode Input path no matter of MUX_MODE functionality.
    //     SION_DISABLED (0) - Input Path is determined by functionality of the selected mux mode (regular).
    //     SION_ENABLED (1) - Force input path of pad FEC_RXD0.
    //   MUX_MODE [2:0] - MUX Mode Select Field Reset: ALT5
    //                    Select 1 of 8 iomux modes to be used for pad: FEC_RXD0.
    //     ALT0 (0) - Select mux mode: ALT0 mux port: RDATA[0] of instance: fec.
    //                NOTE: - Config Register IOMUXC_FEC_FEC_RDATA_0_SELECT_INPUT for mode ALT0.
    //     ALT1 (1) - Select mux mode: ALT1 mux port: DAT5 of instance: usdhc4.
    //                NOTE: - Config Register IOMUXC_USDHC4_IPP_DAT5_IN_SELECT_INPUT for mode ALT1.
    //     ALT2 (2) - Select mux mode: ALT2 mux port: USB_OTG1_ID of instance: usb.
    //                NOTE: - Config Register IOMUXC_ANALOG_USB_OTG_ID_SELECT_INPUT for mode ALT2.
    //     ALT3 (3) - Select mux mode: ALT3 mux port: VSELECT of instance: usdhc1.
    //     ALT4 (4) - Select mux mode: ALT4 mux port: VSELECT of instance: usdhc3.
    //     ALT5 (5) - Select mux mode: ALT5 mux port: GPIO[17] of instance: gpio4.
    HW_IOMUXC_SW_MUX_CTL_PAD_FEC_RXD0_WR(
            BF_IOMUXC_SW_MUX_CTL_PAD_FEC_RXD0_SION(SION_DISABLED) | 
            BF_IOMUXC_SW_MUX_CTL_PAD_FEC_RXD0_MUX_MODE(ALT0));
    // Pad FEC_RXD0 is involved in Daisy Chain.
    // Input Select Register:
    // IOMUXC_FEC_FEC_RDATA_0_SELECT_INPUT(0x020E06F8)
    //   DAISY [1:0] Reset: SEL_FEC_RXD0_ALT0
    //                 Selecting Pads Involved in Daisy Chain.
    //                 NOTE: Instance: fec,   In Pin: fec_rdata[0]
    //     SEL_FEC_RXD0_ALT0 (0) - Selecting Pad: FEC_RXD0 for Mode: ALT0.
    //     SEL_I2C1_SCL_ALT3 (1) - Selecting Pad: I2C1_SCL for Mode: ALT3.
    //     SEL_SD1_DAT5_ALT1 (2) - Selecting Pad: SD1_DAT5 for Mode: ALT1.
    HW_IOMUXC_FEC_FEC_RDATA_0_SELECT_INPUT_WR(
            BF_IOMUXC_FEC_FEC_RDATA_0_SELECT_INPUT_DAISY(SEL_FEC_RXD0_ALT0));
    // Pad Control Register:
    // IOMUXC_SW_PAD_CTL_PAD_FEC_RXD0(0x020E042C)
    //   LVE [22] - Low Voltage Enable Field Reset: LVE_DISABLED
    //              Select one out of next values for pad: FEC_RXD0.
    //     LVE_DISABLED (0) - High Voltage
    //     LVE_ENABLED (1) - Low Voltage
    //   HYS [16] - Hysteresis Enable Field Reset: HYS_ENABLED
    //              Select one out of next values for pad: FEC_RXD0.
    //     HYS_DISABLED (0) - Hysteresis Disabled
    //     HYS_ENABLED (1) - Hysteresis Enabled
    //   PUS [15:14] - Pull Up / Down Configure Field Reset: PUS_100KOHM_PD
    //                 Select one out of next values for pad: FEC_RXD0.
    //     PUS_100KOHM_PD (0) - 100K Ohm Pull Down
    //     PUS_47KOHM_PU (1) - 47K Ohm Pull Up
    //     PUS_100KOHM_PU (2) - 100K Ohm Pull Up
    //     PUS_22KOHM_PU (3) - 22K Ohm Pull Up
    //   PUE [13] - Pull / Keep Select Field Reset: PUE_KEEP
    //              Select one out of next values for pad: FEC_RXD0.
    //     PUE_KEEP (0) - Keeper
    //     PUE_PULL (1) - Pull
    //   PKE [12] - Pull / Keep Enable Field Reset: PKE_ENABLED
    //              Select one out of next values for pad: FEC_RXD0.
    //     PKE_DISABLED (0) - Pull/Keeper Disabled
    //     PKE_ENABLED (1) - Pull/Keeper Enabled
    //   ODE [11] - Open Drain Enable Field Reset: ODE_DISABLED
    //              Select one out of next values for pad: FEC_RXD0.
    //     ODE_DISABLED (0) - Open Drain Disabled
    //     ODE_ENABLED (1) - Open Drain Enabled
    //   SPEED [7:6] - Speed Field Reset: SPD_100MHZ
    //                 Select one out of next values for pad: FEC_RXD0.
    //     SPD_TBD (0) - TBD
    //     SPD_50MHZ (1) - Low(50 MHz)
    //     SPD_100MHZ (2) - Medium(100 MHz)
    //     SPD_200MHZ (3) - Maximum(200 MHz)
    //   DSE [5:3] - Drive Strength Field Reset: DSE_40OHM
    //               Select one out of next values for pad: FEC_RXD0.
    //     DSE_DISABLED (0) - Output driver disabled.
    //     DSE_240OHM (1) - 240 Ohm
    //     DSE_120OHM (2) - 120 Ohm
    //     DSE_80OHM (3) - 80 Ohm
    //     DSE_60OHM (4) - 60 Ohm
    //     DSE_48OHM (5) - 48 Ohm
    //     DSE_40OHM (6) - 40 Ohm
    //     DSE_34OHM (7) - 34 Ohm
    //   SRE [0] - Slew Rate Field Reset: SRE_SLOW
    //             Select one out of next values for pad: FEC_RXD0.
    //     SRE_SLOW (0) - Slow Slew Rate
    //     SRE_FAST (1) - Fast Slew Rate
    HW_IOMUXC_SW_PAD_CTL_PAD_FEC_RXD0_WR(
            BF_IOMUXC_SW_PAD_CTL_PAD_FEC_RXD0_LVE(LVE_DISABLED) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_FEC_RXD0_HYS(HYS_ENABLED) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_FEC_RXD0_PUS(PUS_100KOHM_PD) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_FEC_RXD0_PUE(PUE_KEEP) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_FEC_RXD0_PKE(PKE_ENABLED) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_FEC_RXD0_ODE(ODE_DISABLED) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_FEC_RXD0_SPEED(SPD_100MHZ) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_FEC_RXD0_DSE(DSE_40OHM) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_FEC_RXD0_SRE(SRE_SLOW));

    // Config fec.RDATA[1] to pad FEC_RXD1(AC10)
    // HW_IOMUXC_SW_MUX_CTL_PAD_FEC_RXD1_WR(0x00000000);
    // HW_IOMUXC_FEC_FEC_RDATA_1_SELECT_INPUT_WR(0x00000001);
    // HW_IOMUXC_SW_PAD_CTL_PAD_FEC_RXD1_WR(0x000110B0);
    // Mux Register:
    // IOMUXC_SW_MUX_CTL_PAD_FEC_RXD1(0x020E0140)
    //   SION [4] - Software Input On Field Reset: SION_DISABLED
    //              Force the selected mux mode Input path no matter of MUX_MODE functionality.
    //     SION_DISABLED (0) - Input Path is determined by functionality of the selected mux mode (regular).
    //     SION_ENABLED (1) - Force input path of pad FEC_RXD1.
    //   MUX_MODE [2:0] - MUX Mode Select Field Reset: ALT5
    //                    Select 1 of 8 iomux modes to be used for pad: FEC_RXD1.
    //     ALT0 (0) - Select mux mode: ALT0 mux port: RDATA[1] of instance: fec.
    //                NOTE: - Config Register IOMUXC_FEC_FEC_RDATA_1_SELECT_INPUT for mode ALT0.
    //     ALT1 (1) - Select mux mode: ALT1 mux port: DAT2 of instance: usdhc4.
    //                NOTE: - Config Register IOMUXC_USDHC4_IPP_DAT2_IN_SELECT_INPUT for mode ALT1.
    //     ALT2 (2) - Select mux mode: ALT2 mux port: AUD6_TXFS of instance: audmux.
    //                NOTE: - Config Register IOMUXC_AUDMUX_P6_INPUT_TXFS_AMX_SELECT_INPUT for mode ALT2.
    //     ALT3 (3) - Select mux mode: ALT3 mux port: SS1 of instance: ecspi4.
    //                NOTE: - Config Register IOMUXC_ECSPI4_IPP_IND_SS_B_1_SELECT_INPUT for mode ALT3.
    //     ALT4 (4) - Select mux mode: ALT4 mux port: CMPOUT3 of instance: gpt.
    //     ALT5 (5) - Select mux mode: ALT5 mux port: GPIO[18] of instance: gpio4.
    //     ALT6 (6) - Select mux mode: ALT6 mux port: COL of instance: fec.
    //                NOTE: - Config Register IOMUXC_FEC_FEC_COL_SELECT_INPUT for mode ALT6.
    HW_IOMUXC_SW_MUX_CTL_PAD_FEC_RXD1_WR(
            BF_IOMUXC_SW_MUX_CTL_PAD_FEC_RXD1_SION(SION_DISABLED) | 
            BF_IOMUXC_SW_MUX_CTL_PAD_FEC_RXD1_MUX_MODE(ALT0));
    // Pad FEC_RXD1 is involved in Daisy Chain.
    // Input Select Register:
    // IOMUXC_FEC_FEC_RDATA_1_SELECT_INPUT(0x020E06FC)
    //   DAISY [1:0] Reset: SEL_AUD_TXFS_ALT3
    //                 Selecting Pads Involved in Daisy Chain.
    //                 NOTE: Instance: fec,   In Pin: fec_rdata[1]
    //     SEL_AUD_TXFS_ALT3 (0) - Selecting Pad: AUD_TXFS for Mode: ALT3.
    //     SEL_FEC_RXD1_ALT0 (1) - Selecting Pad: FEC_RXD1 for Mode: ALT0.
    //     SEL_SD1_DAT2_ALT1 (2) - Selecting Pad: SD1_DAT2 for Mode: ALT1.
    HW_IOMUXC_FEC_FEC_RDATA_1_SELECT_INPUT_WR(
            BF_IOMUXC_FEC_FEC_RDATA_1_SELECT_INPUT_DAISY(SEL_FEC_RXD1_ALT0));
    // Pad Control Register:
    // IOMUXC_SW_PAD_CTL_PAD_FEC_RXD1(0x020E0430)
    //   LVE [22] - Low Voltage Enable Field Reset: LVE_DISABLED
    //              Select one out of next values for pad: FEC_RXD1.
    //     LVE_DISABLED (0) - High Voltage
    //     LVE_ENABLED (1) - Low Voltage
    //   HYS [16] - Hysteresis Enable Field Reset: HYS_ENABLED
    //              Select one out of next values for pad: FEC_RXD1.
    //     HYS_DISABLED (0) - Hysteresis Disabled
    //     HYS_ENABLED (1) - Hysteresis Enabled
    //   PUS [15:14] - Pull Up / Down Configure Field Reset: PUS_100KOHM_PD
    //                 Select one out of next values for pad: FEC_RXD1.
    //     PUS_100KOHM_PD (0) - 100K Ohm Pull Down
    //     PUS_47KOHM_PU (1) - 47K Ohm Pull Up
    //     PUS_100KOHM_PU (2) - 100K Ohm Pull Up
    //     PUS_22KOHM_PU (3) - 22K Ohm Pull Up
    //   PUE [13] - Pull / Keep Select Field Reset: PUE_KEEP
    //              Select one out of next values for pad: FEC_RXD1.
    //     PUE_KEEP (0) - Keeper
    //     PUE_PULL (1) - Pull
    //   PKE [12] - Pull / Keep Enable Field Reset: PKE_ENABLED
    //              Select one out of next values for pad: FEC_RXD1.
    //     PKE_DISABLED (0) - Pull/Keeper Disabled
    //     PKE_ENABLED (1) - Pull/Keeper Enabled
    //   ODE [11] - Open Drain Enable Field Reset: ODE_DISABLED
    //              Select one out of next values for pad: FEC_RXD1.
    //     ODE_DISABLED (0) - Open Drain Disabled
    //     ODE_ENABLED (1) - Open Drain Enabled
    //   SPEED [7:6] - Speed Field Reset: SPD_100MHZ
    //                 Select one out of next values for pad: FEC_RXD1.
    //     SPD_TBD (0) - TBD
    //     SPD_50MHZ (1) - Low(50 MHz)
    //     SPD_100MHZ (2) - Medium(100 MHz)
    //     SPD_200MHZ (3) - Maximum(200 MHz)
    //   DSE [5:3] - Drive Strength Field Reset: DSE_40OHM
    //               Select one out of next values for pad: FEC_RXD1.
    //     DSE_DISABLED (0) - Output driver disabled.
    //     DSE_240OHM (1) - 240 Ohm
    //     DSE_120OHM (2) - 120 Ohm
    //     DSE_80OHM (3) - 80 Ohm
    //     DSE_60OHM (4) - 60 Ohm
    //     DSE_48OHM (5) - 48 Ohm
    //     DSE_40OHM (6) - 40 Ohm
    //     DSE_34OHM (7) - 34 Ohm
    //   SRE [0] - Slew Rate Field Reset: SRE_SLOW
    //             Select one out of next values for pad: FEC_RXD1.
    //     SRE_SLOW (0) - Slow Slew Rate
    //     SRE_FAST (1) - Fast Slew Rate
    HW_IOMUXC_SW_PAD_CTL_PAD_FEC_RXD1_WR(
            BF_IOMUXC_SW_PAD_CTL_PAD_FEC_RXD1_LVE(LVE_DISABLED) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_FEC_RXD1_HYS(HYS_ENABLED) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_FEC_RXD1_PUS(PUS_100KOHM_PD) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_FEC_RXD1_PUE(PUE_KEEP) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_FEC_RXD1_PKE(PKE_ENABLED) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_FEC_RXD1_ODE(ODE_DISABLED) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_FEC_RXD1_SPEED(SPD_100MHZ) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_FEC_RXD1_DSE(DSE_40OHM) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_FEC_RXD1_SRE(SRE_SLOW));

    // Config fec.REF_OUT to pad FEC_REF_CLK(W10)
    // HW_IOMUXC_SW_MUX_CTL_PAD_FEC_REF_CLK_WR(0x00000010);
    // HW_IOMUXC_SW_PAD_CTL_PAD_FEC_REF_CLK_WR(0x000110B0);
    // Mux Register:
    // IOMUXC_SW_MUX_CTL_PAD_FEC_REF_CLK(0x020E0134)
    //   SION [4] - Software Input On Field Reset: SION_DISABLED
    //              Force the selected mux mode Input path no matter of MUX_MODE functionality.
    //     SION_DISABLED (0) - Input Path is determined by functionality of the selected mux mode (regular).
    //     SION_ENABLED (1) - Force input path of pad FEC_REF_CLK.
    //   MUX_MODE [2:0] - MUX Mode Select Field Reset: ALT5
    //                    Select 1 of 8 iomux modes to be used for pad: FEC_REF_CLK.
    //     ALT0 (0) - Select mux mode: ALT0 mux port: REF_OUT of instance: fec.
    //     ALT1 (1) - Select mux mode: ALT1 mux port: RST of instance: usdhc4.
    //     ALT2 (2) - Select mux mode: ALT2 mux port: WDOG_B of instance: wdog1.
    //     ALT3 (3) - Select mux mode: ALT3 mux port: PWMO of instance: pwm4.
    //     ALT4 (4) - Select mux mode: ALT4 mux port: PMIC_RDY of instance: ccm.
    //                NOTE: - Config Register IOMUXC_CCM_PMIC_VFUNCIONAL_READY_SELECT_INPUT for mode ALT4.
    //     ALT5 (5) - Select mux mode: ALT5 mux port: GPIO[26] of instance: gpio4.
    //     ALT6 (6) - Select mux mode: ALT6 mux port: SPDIF_EXT_CLK of instance: spdif.
    //                NOTE: - Config Register IOMUXC_SPDIF_TX_CLK2_SELECT_INPUT for mode ALT6.
    HW_IOMUXC_SW_MUX_CTL_PAD_FEC_REF_CLK_WR(
            BF_IOMUXC_SW_MUX_CTL_PAD_FEC_REF_CLK_SION(SION_ENABLED) | 
            BF_IOMUXC_SW_MUX_CTL_PAD_FEC_REF_CLK_MUX_MODE(ALT0));
    // Pad Control Register:
    // IOMUXC_SW_PAD_CTL_PAD_FEC_REF_CLK(0x020E0424)
    //   LVE [22] - Low Voltage Enable Field Reset: LVE_DISABLED
    //              Select one out of next values for pad: FEC_REF_CLK.
    //     LVE_DISABLED (0) - High Voltage
    //     LVE_ENABLED (1) - Low Voltage
    //   HYS [16] - Hysteresis Enable Field Reset: HYS_ENABLED
    //              Select one out of next values for pad: FEC_REF_CLK.
    //     HYS_DISABLED (0) - Hysteresis Disabled
    //     HYS_ENABLED (1) - Hysteresis Enabled
    //   PUS [15:14] - Pull Up / Down Configure Field Reset: PUS_100KOHM_PD
    //                 Select one out of next values for pad: FEC_REF_CLK.
    //     PUS_100KOHM_PD (0) - 100K Ohm Pull Down
    //     PUS_47KOHM_PU (1) - 47K Ohm Pull Up
    //     PUS_100KOHM_PU (2) - 100K Ohm Pull Up
    //     PUS_22KOHM_PU (3) - 22K Ohm Pull Up
    //   PUE [13] - Pull / Keep Select Field Reset: PUE_KEEP
    //              Select one out of next values for pad: FEC_REF_CLK.
    //     PUE_KEEP (0) - Keeper
    //     PUE_PULL (1) - Pull
    //   PKE [12] - Pull / Keep Enable Field Reset: PKE_ENABLED
    //              Select one out of next values for pad: FEC_REF_CLK.
    //     PKE_DISABLED (0) - Pull/Keeper Disabled
    //     PKE_ENABLED (1) - Pull/Keeper Enabled
    //   ODE [11] - Open Drain Enable Field Reset: ODE_DISABLED
    //              Select one out of next values for pad: FEC_REF_CLK.
    //     ODE_DISABLED (0) - Open Drain Disabled
    //     ODE_ENABLED (1) - Open Drain Enabled
    //   SPEED [7:6] - Speed Field Reset: SPD_100MHZ
    //                 Select one out of next values for pad: FEC_REF_CLK.
    //     SPD_TBD (0) - TBD
    //     SPD_50MHZ (1) - Low(50 MHz)
    //     SPD_100MHZ (2) - Medium(100 MHz)
    //     SPD_200MHZ (3) - Maximum(200 MHz)
    //   DSE [5:3] - Drive Strength Field Reset: DSE_40OHM
    //               Select one out of next values for pad: FEC_REF_CLK.
    //     DSE_DISABLED (0) - Output driver disabled.
    //     DSE_240OHM (1) - 240 Ohm
    //     DSE_120OHM (2) - 120 Ohm
    //     DSE_80OHM (3) - 80 Ohm
    //     DSE_60OHM (4) - 60 Ohm
    //     DSE_48OHM (5) - 48 Ohm
    //     DSE_40OHM (6) - 40 Ohm
    //     DSE_34OHM (7) - 34 Ohm
    //   SRE [0] - Slew Rate Field Reset: SRE_SLOW
    //             Select one out of next values for pad: FEC_REF_CLK.
    //     SRE_SLOW (0) - Slow Slew Rate
    //     SRE_FAST (1) - Fast Slew Rate
    HW_IOMUXC_SW_PAD_CTL_PAD_FEC_REF_CLK_WR(
            BF_IOMUXC_SW_PAD_CTL_PAD_FEC_REF_CLK_LVE(LVE_DISABLED) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_FEC_REF_CLK_HYS(HYS_ENABLED) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_FEC_REF_CLK_PUS(PUS_100KOHM_PD) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_FEC_REF_CLK_PUE(PUE_KEEP) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_FEC_REF_CLK_PKE(PKE_ENABLED) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_FEC_REF_CLK_ODE(ODE_DISABLED) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_FEC_REF_CLK_SPEED(SPD_100MHZ) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_FEC_REF_CLK_DSE(DSE_40OHM) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_FEC_REF_CLK_SRE(SRE_SLOW));

    // Config fec.RX_DV to pad FEC_CRS_DV(AC9)
    // HW_IOMUXC_SW_MUX_CTL_PAD_FEC_CRS_DV_WR(0x00000000);
    // HW_IOMUXC_FEC_FEC_RX_DV_SELECT_INPUT_WR(0x00000001);
    // HW_IOMUXC_SW_PAD_CTL_PAD_FEC_CRS_DV_WR(0x000110B0);
    // Mux Register:
    // IOMUXC_SW_MUX_CTL_PAD_FEC_CRS_DV(0x020E0128)
    //   SION [4] - Software Input On Field Reset: SION_DISABLED
    //              Force the selected mux mode Input path no matter of MUX_MODE functionality.
    //     SION_DISABLED (0) - Input Path is determined by functionality of the selected mux mode (regular).
    //     SION_ENABLED (1) - Force input path of pad FEC_CRS_DV.
    //   MUX_MODE [2:0] - MUX Mode Select Field Reset: ALT5
    //                    Select 1 of 8 iomux modes to be used for pad: FEC_CRS_DV.
    //     ALT0 (0) - Select mux mode: ALT0 mux port: RX_DV of instance: fec.
    //                NOTE: - Config Register IOMUXC_FEC_FEC_RX_DV_SELECT_INPUT for mode ALT0.
    //     ALT1 (1) - Select mux mode: ALT1 mux port: DAT1 of instance: usdhc4.
    //                NOTE: - Config Register IOMUXC_USDHC4_IPP_DAT1_IN_SELECT_INPUT for mode ALT1.
    //     ALT2 (2) - Select mux mode: ALT2 mux port: AUD6_TXC of instance: audmux.
    //                NOTE: - Config Register IOMUXC_AUDMUX_P6_INPUT_TXCLK_AMX_SELECT_INPUT for mode ALT2.
    //     ALT3 (3) - Select mux mode: ALT3 mux port: MISO of instance: ecspi4.
    //                NOTE: - Config Register IOMUXC_ECSPI4_IPP_IND_MISO_SELECT_INPUT for mode ALT3.
    //     ALT4 (4) - Select mux mode: ALT4 mux port: CMPOUT2 of instance: gpt.
    //     ALT5 (5) - Select mux mode: ALT5 mux port: GPIO[25] of instance: gpio4.
    HW_IOMUXC_SW_MUX_CTL_PAD_FEC_CRS_DV_WR(
            BF_IOMUXC_SW_MUX_CTL_PAD_FEC_CRS_DV_SION(SION_DISABLED) | 
            BF_IOMUXC_SW_MUX_CTL_PAD_FEC_CRS_DV_MUX_MODE(ALT0));
    // Pad FEC_CRS_DV is involved in Daisy Chain.
    // Input Select Register:
    // IOMUXC_FEC_FEC_RX_DV_SELECT_INPUT(0x020E0704)
    //   DAISY [1:0] Reset: SEL_AUD_TXC_ALT3
    //                 Selecting Pads Involved in Daisy Chain.
    //                 NOTE: Instance: fec,   In Pin: fec_rx_dv
    //     SEL_AUD_TXC_ALT3 (0) - Selecting Pad: AUD_TXC for Mode: ALT3.
    //     SEL_FEC_CRS_DV_ALT0 (1) - Selecting Pad: FEC_CRS_DV for Mode: ALT0.
    //     SEL_SD1_DAT1_ALT1 (2) - Selecting Pad: SD1_DAT1 for Mode: ALT1.
    HW_IOMUXC_FEC_FEC_RX_DV_SELECT_INPUT_WR(
            BF_IOMUXC_FEC_FEC_RX_DV_SELECT_INPUT_DAISY(SEL_FEC_CRS_DV_ALT0));
    // Pad Control Register:
    // IOMUXC_SW_PAD_CTL_PAD_FEC_CRS_DV(0x020E0418)
    //   LVE [22] - Low Voltage Enable Field Reset: LVE_DISABLED
    //              Select one out of next values for pad: FEC_CRS_DV.
    //     LVE_DISABLED (0) - High Voltage
    //     LVE_ENABLED (1) - Low Voltage
    //   HYS [16] - Hysteresis Enable Field Reset: HYS_ENABLED
    //              Select one out of next values for pad: FEC_CRS_DV.
    //     HYS_DISABLED (0) - Hysteresis Disabled
    //     HYS_ENABLED (1) - Hysteresis Enabled
    //   PUS [15:14] - Pull Up / Down Configure Field Reset: PUS_100KOHM_PD
    //                 Select one out of next values for pad: FEC_CRS_DV.
    //     PUS_100KOHM_PD (0) - 100K Ohm Pull Down
    //     PUS_47KOHM_PU (1) - 47K Ohm Pull Up
    //     PUS_100KOHM_PU (2) - 100K Ohm Pull Up
    //     PUS_22KOHM_PU (3) - 22K Ohm Pull Up
    //   PUE [13] - Pull / Keep Select Field Reset: PUE_KEEP
    //              Select one out of next values for pad: FEC_CRS_DV.
    //     PUE_KEEP (0) - Keeper
    //     PUE_PULL (1) - Pull
    //   PKE [12] - Pull / Keep Enable Field Reset: PKE_ENABLED
    //              Select one out of next values for pad: FEC_CRS_DV.
    //     PKE_DISABLED (0) - Pull/Keeper Disabled
    //     PKE_ENABLED (1) - Pull/Keeper Enabled
    //   ODE [11] - Open Drain Enable Field Reset: ODE_DISABLED
    //              Select one out of next values for pad: FEC_CRS_DV.
    //     ODE_DISABLED (0) - Open Drain Disabled
    //     ODE_ENABLED (1) - Open Drain Enabled
    //   SPEED [7:6] - Speed Field Reset: SPD_100MHZ
    //                 Select one out of next values for pad: FEC_CRS_DV.
    //     SPD_TBD (0) - TBD
    //     SPD_50MHZ (1) - Low(50 MHz)
    //     SPD_100MHZ (2) - Medium(100 MHz)
    //     SPD_200MHZ (3) - Maximum(200 MHz)
    //   DSE [5:3] - Drive Strength Field Reset: DSE_40OHM
    //               Select one out of next values for pad: FEC_CRS_DV.
    //     DSE_DISABLED (0) - Output driver disabled.
    //     DSE_240OHM (1) - 240 Ohm
    //     DSE_120OHM (2) - 120 Ohm
    //     DSE_80OHM (3) - 80 Ohm
    //     DSE_60OHM (4) - 60 Ohm
    //     DSE_48OHM (5) - 48 Ohm
    //     DSE_40OHM (6) - 40 Ohm
    //     DSE_34OHM (7) - 34 Ohm
    //   SRE [0] - Slew Rate Field Reset: SRE_SLOW
    //             Select one out of next values for pad: FEC_CRS_DV.
    //     SRE_SLOW (0) - Slow Slew Rate
    //     SRE_FAST (1) - Fast Slew Rate
    HW_IOMUXC_SW_PAD_CTL_PAD_FEC_CRS_DV_WR(
            BF_IOMUXC_SW_PAD_CTL_PAD_FEC_CRS_DV_LVE(LVE_DISABLED) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_FEC_CRS_DV_HYS(HYS_ENABLED) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_FEC_CRS_DV_PUS(PUS_100KOHM_PD) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_FEC_CRS_DV_PUE(PUE_KEEP) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_FEC_CRS_DV_PKE(PKE_ENABLED) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_FEC_CRS_DV_ODE(ODE_DISABLED) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_FEC_CRS_DV_SPEED(SPD_100MHZ) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_FEC_CRS_DV_DSE(DSE_40OHM) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_FEC_CRS_DV_SRE(SRE_SLOW));

    // Config fec.TDATA[0] to pad FEC_TXD0(Y10)
    // HW_IOMUXC_SW_MUX_CTL_PAD_FEC_TXD0_WR(0x00000000);
    // HW_IOMUXC_SW_PAD_CTL_PAD_FEC_TXD0_WR(0x000110B0);
    // Mux Register:
    // IOMUXC_SW_MUX_CTL_PAD_FEC_TXD0(0x020E014C)
    //   SION [4] - Software Input On Field Reset: SION_DISABLED
    //              Force the selected mux mode Input path no matter of MUX_MODE functionality.
    //     SION_DISABLED (0) - Input Path is determined by functionality of the selected mux mode (regular).
    //     SION_ENABLED (1) - Force input path of pad FEC_TXD0.
    //   MUX_MODE [2:0] - MUX Mode Select Field Reset: ALT5
    //                    Select 1 of 8 iomux modes to be used for pad: FEC_TXD0.
    //     ALT0 (0) - Select mux mode: ALT0 mux port: TDATA[0] of instance: fec.
    //     ALT1 (1) - Select mux mode: ALT1 mux port: DAT3 of instance: usdhc4.
    //                NOTE: - Config Register IOMUXC_USDHC4_IPP_DAT3_IN_SELECT_INPUT for mode ALT1.
    //     ALT2 (2) - Select mux mode: ALT2 mux port: AUD6_TXD of instance: audmux.
    //                NOTE: - Config Register IOMUXC_AUDMUX_P6_INPUT_DB_AMX_SELECT_INPUT for mode ALT2.
    //     ALT3 (3) - Select mux mode: ALT3 mux port: SS2 of instance: ecspi4.
    //                NOTE: - Config Register IOMUXC_ECSPI4_IPP_IND_SS_B_2_SELECT_INPUT for mode ALT3.
    //     ALT4 (4) - Select mux mode: ALT4 mux port: CLKIN of instance: gpt.
    //                NOTE: - Config Register IOMUXC_GPT_IPP_IND_CLKIN_SELECT_INPUT for mode ALT4.
    //     ALT5 (5) - Select mux mode: ALT5 mux port: GPIO[24] of instance: gpio4.
    HW_IOMUXC_SW_MUX_CTL_PAD_FEC_TXD0_WR(
            BF_IOMUXC_SW_MUX_CTL_PAD_FEC_TXD0_SION(SION_DISABLED) | 
            BF_IOMUXC_SW_MUX_CTL_PAD_FEC_TXD0_MUX_MODE(ALT0));
    // Pad Control Register:
    // IOMUXC_SW_PAD_CTL_PAD_FEC_TXD0(0x020E043C)
    //   LVE [22] - Low Voltage Enable Field Reset: LVE_DISABLED
    //              Select one out of next values for pad: FEC_TXD0.
    //     LVE_DISABLED (0) - High Voltage
    //     LVE_ENABLED (1) - Low Voltage
    //   HYS [16] - Hysteresis Enable Field Reset: HYS_ENABLED
    //              Select one out of next values for pad: FEC_TXD0.
    //     HYS_DISABLED (0) - Hysteresis Disabled
    //     HYS_ENABLED (1) - Hysteresis Enabled
    //   PUS [15:14] - Pull Up / Down Configure Field Reset: PUS_100KOHM_PD
    //                 Select one out of next values for pad: FEC_TXD0.
    //     PUS_100KOHM_PD (0) - 100K Ohm Pull Down
    //     PUS_47KOHM_PU (1) - 47K Ohm Pull Up
    //     PUS_100KOHM_PU (2) - 100K Ohm Pull Up
    //     PUS_22KOHM_PU (3) - 22K Ohm Pull Up
    //   PUE [13] - Pull / Keep Select Field Reset: PUE_KEEP
    //              Select one out of next values for pad: FEC_TXD0.
    //     PUE_KEEP (0) - Keeper
    //     PUE_PULL (1) - Pull
    //   PKE [12] - Pull / Keep Enable Field Reset: PKE_ENABLED
    //              Select one out of next values for pad: FEC_TXD0.
    //     PKE_DISABLED (0) - Pull/Keeper Disabled
    //     PKE_ENABLED (1) - Pull/Keeper Enabled
    //   ODE [11] - Open Drain Enable Field Reset: ODE_DISABLED
    //              Select one out of next values for pad: FEC_TXD0.
    //     ODE_DISABLED (0) - Open Drain Disabled
    //     ODE_ENABLED (1) - Open Drain Enabled
    //   SPEED [7:6] - Speed Field Reset: SPD_100MHZ
    //                 Select one out of next values for pad: FEC_TXD0.
    //     SPD_TBD (0) - TBD
    //     SPD_50MHZ (1) - Low(50 MHz)
    //     SPD_100MHZ (2) - Medium(100 MHz)
    //     SPD_200MHZ (3) - Maximum(200 MHz)
    //   DSE [5:3] - Drive Strength Field Reset: DSE_40OHM
    //               Select one out of next values for pad: FEC_TXD0.
    //     DSE_DISABLED (0) - Output driver disabled.
    //     DSE_240OHM (1) - 240 Ohm
    //     DSE_120OHM (2) - 120 Ohm
    //     DSE_80OHM (3) - 80 Ohm
    //     DSE_60OHM (4) - 60 Ohm
    //     DSE_48OHM (5) - 48 Ohm
    //     DSE_40OHM (6) - 40 Ohm
    //     DSE_34OHM (7) - 34 Ohm
    //   SRE [0] - Slew Rate Field Reset: SRE_SLOW
    //             Select one out of next values for pad: FEC_TXD0.
    //     SRE_SLOW (0) - Slow Slew Rate
    //     SRE_FAST (1) - Fast Slew Rate
    HW_IOMUXC_SW_PAD_CTL_PAD_FEC_TXD0_WR(
            BF_IOMUXC_SW_PAD_CTL_PAD_FEC_TXD0_LVE(LVE_DISABLED) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_FEC_TXD0_HYS(HYS_ENABLED) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_FEC_TXD0_PUS(PUS_100KOHM_PD) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_FEC_TXD0_PUE(PUE_KEEP) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_FEC_TXD0_PKE(PKE_ENABLED) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_FEC_TXD0_ODE(ODE_DISABLED) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_FEC_TXD0_SPEED(SPD_100MHZ) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_FEC_TXD0_DSE(DSE_40OHM) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_FEC_TXD0_SRE(SRE_SLOW));

    // Config fec.TDATA[1] to pad FEC_TXD1(W11)
    // HW_IOMUXC_SW_MUX_CTL_PAD_FEC_TXD1_WR(0x00000000);
    // HW_IOMUXC_SW_PAD_CTL_PAD_FEC_TXD1_WR(0x000110B0);
    // Mux Register:
    // IOMUXC_SW_MUX_CTL_PAD_FEC_TXD1(0x020E0150)
    //   SION [4] - Software Input On Field Reset: SION_DISABLED
    //              Force the selected mux mode Input path no matter of MUX_MODE functionality.
    //     SION_DISABLED (0) - Input Path is determined by functionality of the selected mux mode (regular).
    //     SION_ENABLED (1) - Force input path of pad FEC_TXD1.
    //   MUX_MODE [2:0] - MUX Mode Select Field Reset: ALT5
    //                    Select 1 of 8 iomux modes to be used for pad: FEC_TXD1.
    //     ALT0 (0) - Select mux mode: ALT0 mux port: TDATA[1] of instance: fec.
    //     ALT1 (1) - Select mux mode: ALT1 mux port: DAT7 of instance: usdhc4.
    //                NOTE: - Config Register IOMUXC_USDHC4_IPP_DAT7_IN_SELECT_INPUT for mode ALT1.
    //     ALT2 (2) - Select mux mode: ALT2 mux port: OUT1 of instance: spdif.
    //     ALT3 (3) - Select mux mode: ALT3 mux port: CD of instance: usdhc1.
    //                NOTE: - Config Register IOMUXC_USDHC1_IPP_CARD_DET_SELECT_INPUT for mode ALT3.
    //     ALT4 (4) - Select mux mode: ALT4 mux port: CD of instance: usdhc3.
    //                NOTE: - Config Register IOMUXC_USDHC3_IPP_CARD_DET_SELECT_INPUT for mode ALT4.
    //     ALT5 (5) - Select mux mode: ALT5 mux port: GPIO[16] of instance: gpio4.
    //     ALT6 (6) - Select mux mode: ALT6 mux port: RX_CLK of instance: fec.
    //                NOTE: - Config Register IOMUXC_FEC_FEC_RX_CLK_SELECT_INPUT for mode ALT6.
    HW_IOMUXC_SW_MUX_CTL_PAD_FEC_TXD1_WR(
            BF_IOMUXC_SW_MUX_CTL_PAD_FEC_TXD1_SION(SION_DISABLED) | 
            BF_IOMUXC_SW_MUX_CTL_PAD_FEC_TXD1_MUX_MODE(ALT0));
    // Pad Control Register:
    // IOMUXC_SW_PAD_CTL_PAD_FEC_TXD1(0x020E0440)
    //   LVE [22] - Low Voltage Enable Field Reset: LVE_DISABLED
    //              Select one out of next values for pad: FEC_TXD1.
    //     LVE_DISABLED (0) - High Voltage
    //     LVE_ENABLED (1) - Low Voltage
    //   HYS [16] - Hysteresis Enable Field Reset: HYS_ENABLED
    //              Select one out of next values for pad: FEC_TXD1.
    //     HYS_DISABLED (0) - Hysteresis Disabled
    //     HYS_ENABLED (1) - Hysteresis Enabled
    //   PUS [15:14] - Pull Up / Down Configure Field Reset: PUS_100KOHM_PD
    //                 Select one out of next values for pad: FEC_TXD1.
    //     PUS_100KOHM_PD (0) - 100K Ohm Pull Down
    //     PUS_47KOHM_PU (1) - 47K Ohm Pull Up
    //     PUS_100KOHM_PU (2) - 100K Ohm Pull Up
    //     PUS_22KOHM_PU (3) - 22K Ohm Pull Up
    //   PUE [13] - Pull / Keep Select Field Reset: PUE_KEEP
    //              Select one out of next values for pad: FEC_TXD1.
    //     PUE_KEEP (0) - Keeper
    //     PUE_PULL (1) - Pull
    //   PKE [12] - Pull / Keep Enable Field Reset: PKE_ENABLED
    //              Select one out of next values for pad: FEC_TXD1.
    //     PKE_DISABLED (0) - Pull/Keeper Disabled
    //     PKE_ENABLED (1) - Pull/Keeper Enabled
    //   ODE [11] - Open Drain Enable Field Reset: ODE_DISABLED
    //              Select one out of next values for pad: FEC_TXD1.
    //     ODE_DISABLED (0) - Open Drain Disabled
    //     ODE_ENABLED (1) - Open Drain Enabled
    //   SPEED [7:6] - Speed Field Reset: SPD_100MHZ
    //                 Select one out of next values for pad: FEC_TXD1.
    //     SPD_TBD (0) - TBD
    //     SPD_50MHZ (1) - Low(50 MHz)
    //     SPD_100MHZ (2) - Medium(100 MHz)
    //     SPD_200MHZ (3) - Maximum(200 MHz)
    //   DSE [5:3] - Drive Strength Field Reset: DSE_40OHM
    //               Select one out of next values for pad: FEC_TXD1.
    //     DSE_DISABLED (0) - Output driver disabled.
    //     DSE_240OHM (1) - 240 Ohm
    //     DSE_120OHM (2) - 120 Ohm
    //     DSE_80OHM (3) - 80 Ohm
    //     DSE_60OHM (4) - 60 Ohm
    //     DSE_48OHM (5) - 48 Ohm
    //     DSE_40OHM (6) - 40 Ohm
    //     DSE_34OHM (7) - 34 Ohm
    //   SRE [0] - Slew Rate Field Reset: SRE_SLOW
    //             Select one out of next values for pad: FEC_TXD1.
    //     SRE_SLOW (0) - Slow Slew Rate
    //     SRE_FAST (1) - Fast Slew Rate
    HW_IOMUXC_SW_PAD_CTL_PAD_FEC_TXD1_WR(
            BF_IOMUXC_SW_PAD_CTL_PAD_FEC_TXD1_LVE(LVE_DISABLED) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_FEC_TXD1_HYS(HYS_ENABLED) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_FEC_TXD1_PUS(PUS_100KOHM_PD) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_FEC_TXD1_PUE(PUE_KEEP) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_FEC_TXD1_PKE(PKE_ENABLED) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_FEC_TXD1_ODE(ODE_DISABLED) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_FEC_TXD1_SPEED(SPD_100MHZ) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_FEC_TXD1_DSE(DSE_40OHM) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_FEC_TXD1_SRE(SRE_SLOW));

    // Config fec.TX_EN to pad FEC_TX_EN(AD10)
    // HW_IOMUXC_SW_MUX_CTL_PAD_FEC_TX_EN_WR(0x00000000);
    // HW_IOMUXC_SW_PAD_CTL_PAD_FEC_TX_EN_WR(0x000110B0);
    // Mux Register:
    // IOMUXC_SW_MUX_CTL_PAD_FEC_TX_EN(0x020E0148)
    //   SION [4] - Software Input On Field Reset: SION_DISABLED
    //              Force the selected mux mode Input path no matter of MUX_MODE functionality.
    //     SION_DISABLED (0) - Input Path is determined by functionality of the selected mux mode (regular).
    //     SION_ENABLED (1) - Force input path of pad FEC_TX_EN.
    //   MUX_MODE [2:0] - MUX Mode Select Field Reset: ALT5
    //                    Select 1 of 8 iomux modes to be used for pad: FEC_TX_EN.
    //     ALT0 (0) - Select mux mode: ALT0 mux port: TX_EN of instance: fec.
    //     ALT1 (1) - Select mux mode: ALT1 mux port: DAT6 of instance: usdhc4.
    //                NOTE: - Config Register IOMUXC_USDHC4_IPP_DAT6_IN_SELECT_INPUT for mode ALT1.
    //     ALT2 (2) - Select mux mode: ALT2 mux port: IN1 of instance: spdif.
    //                NOTE: - Config Register IOMUXC_SPDIF_SPDIF_IN1_SELECT_INPUT for mode ALT2.
    //     ALT3 (3) - Select mux mode: ALT3 mux port: WP of instance: usdhc1.
    //                NOTE: - Config Register IOMUXC_USDHC1_IPP_WP_ON_SELECT_INPUT for mode ALT3.
    //     ALT4 (4) - Select mux mode: ALT4 mux port: WP of instance: usdhc3.
    //                NOTE: - Config Register IOMUXC_USDHC3_IPP_WP_ON_SELECT_INPUT for mode ALT4.
    //     ALT5 (5) - Select mux mode: ALT5 mux port: GPIO[22] of instance: gpio4.
    HW_IOMUXC_SW_MUX_CTL_PAD_FEC_TX_EN_WR(
            BF_IOMUXC_SW_MUX_CTL_PAD_FEC_TX_EN_SION(SION_DISABLED) | 
            BF_IOMUXC_SW_MUX_CTL_PAD_FEC_TX_EN_MUX_MODE(ALT0));
    // Pad Control Register:
    // IOMUXC_SW_PAD_CTL_PAD_FEC_TX_EN(0x020E0438)
    //   LVE [22] - Low Voltage Enable Field Reset: LVE_DISABLED
    //              Select one out of next values for pad: FEC_TX_EN.
    //     LVE_DISABLED (0) - High Voltage
    //     LVE_ENABLED (1) - Low Voltage
    //   HYS [16] - Hysteresis Enable Field Reset: HYS_ENABLED
    //              Select one out of next values for pad: FEC_TX_EN.
    //     HYS_DISABLED (0) - Hysteresis Disabled
    //     HYS_ENABLED (1) - Hysteresis Enabled
    //   PUS [15:14] - Pull Up / Down Configure Field Reset: PUS_100KOHM_PD
    //                 Select one out of next values for pad: FEC_TX_EN.
    //     PUS_100KOHM_PD (0) - 100K Ohm Pull Down
    //     PUS_47KOHM_PU (1) - 47K Ohm Pull Up
    //     PUS_100KOHM_PU (2) - 100K Ohm Pull Up
    //     PUS_22KOHM_PU (3) - 22K Ohm Pull Up
    //   PUE [13] - Pull / Keep Select Field Reset: PUE_KEEP
    //              Select one out of next values for pad: FEC_TX_EN.
    //     PUE_KEEP (0) - Keeper
    //     PUE_PULL (1) - Pull
    //   PKE [12] - Pull / Keep Enable Field Reset: PKE_ENABLED
    //              Select one out of next values for pad: FEC_TX_EN.
    //     PKE_DISABLED (0) - Pull/Keeper Disabled
    //     PKE_ENABLED (1) - Pull/Keeper Enabled
    //   ODE [11] - Open Drain Enable Field Reset: ODE_DISABLED
    //              Select one out of next values for pad: FEC_TX_EN.
    //     ODE_DISABLED (0) - Open Drain Disabled
    //     ODE_ENABLED (1) - Open Drain Enabled
    //   SPEED [7:6] - Speed Field Reset: SPD_100MHZ
    //                 Select one out of next values for pad: FEC_TX_EN.
    //     SPD_TBD (0) - TBD
    //     SPD_50MHZ (1) - Low(50 MHz)
    //     SPD_100MHZ (2) - Medium(100 MHz)
    //     SPD_200MHZ (3) - Maximum(200 MHz)
    //   DSE [5:3] - Drive Strength Field Reset: DSE_40OHM
    //               Select one out of next values for pad: FEC_TX_EN.
    //     DSE_DISABLED (0) - Output driver disabled.
    //     DSE_240OHM (1) - 240 Ohm
    //     DSE_120OHM (2) - 120 Ohm
    //     DSE_80OHM (3) - 80 Ohm
    //     DSE_60OHM (4) - 60 Ohm
    //     DSE_48OHM (5) - 48 Ohm
    //     DSE_40OHM (6) - 40 Ohm
    //     DSE_34OHM (7) - 34 Ohm
    //   SRE [0] - Slew Rate Field Reset: SRE_SLOW
    //             Select one out of next values for pad: FEC_TX_EN.
    //     SRE_SLOW (0) - Slow Slew Rate
    //     SRE_FAST (1) - Fast Slew Rate
    HW_IOMUXC_SW_PAD_CTL_PAD_FEC_TX_EN_WR(
            BF_IOMUXC_SW_PAD_CTL_PAD_FEC_TX_EN_LVE(LVE_DISABLED) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_FEC_TX_EN_HYS(HYS_ENABLED) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_FEC_TX_EN_PUS(PUS_100KOHM_PD) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_FEC_TX_EN_PUE(PUE_KEEP) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_FEC_TX_EN_PKE(PKE_ENABLED) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_FEC_TX_EN_ODE(ODE_DISABLED) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_FEC_TX_EN_SPEED(SPD_100MHZ) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_FEC_TX_EN_DSE(DSE_40OHM) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_FEC_TX_EN_SRE(SRE_SLOW));

    // Config fec.FEC_RESET_B to pad FEC_TX_CLK(AC8)
    // WAS Instance:gpio4 Signal:GPIO[21]
    // HW_IOMUXC_SW_MUX_CTL_PAD_FEC_TX_CLK_WR(0x00000005);
    // HW_IOMUXC_SW_PAD_CTL_PAD_FEC_TX_CLK_WR(0x000110B0);
    // Mux Register:
    // IOMUXC_SW_MUX_CTL_PAD_FEC_TX_CLK(0x020E0144)
    //   SION [4] - Software Input On Field Reset: SION_DISABLED
    //              Force the selected mux mode Input path no matter of MUX_MODE functionality.
    //     SION_DISABLED (0) - Input Path is determined by functionality of the selected mux mode (regular).
    //     SION_ENABLED (1) - Force input path of pad FEC_TX_CLK.
    //   MUX_MODE [2:0] - MUX Mode Select Field Reset: ALT5
    //                    Select 1 of 8 iomux modes to be used for pad: FEC_TX_CLK.
    //     ALT0 (0) - Select mux mode: ALT0 mux port: TX_CLK of instance: fec.
    //                NOTE: - Config Register IOMUXC_FEC_FEC_TX_CLK_SELECT_INPUT for mode ALT0.
    //     ALT1 (1) - Select mux mode: ALT1 mux port: CMD of instance: usdhc4.
    //                NOTE: - Config Register IOMUXC_USDHC4_IPP_CMD_IN_SELECT_INPUT for mode ALT1.
    //     ALT2 (2) - Select mux mode: ALT2 mux port: AUD6_RXC of instance: audmux.
    //                NOTE: - Config Register IOMUXC_AUDMUX_P6_INPUT_RXCLK_AMX_SELECT_INPUT for mode ALT2.
    //     ALT3 (3) - Select mux mode: ALT3 mux port: SCLK of instance: ecspi4.
    //                NOTE: - Config Register IOMUXC_ECSPI4_IPP_CSPI_CLK_IN_SELECT_INPUT for mode ALT3.
    //     ALT4 (4) - Select mux mode: ALT4 mux port: CAPIN2 of instance: gpt.
    //                NOTE: - Config Register IOMUXC_GPT_IPP_IND_CAPIN2_SELECT_INPUT for mode ALT4.
    //     ALT5 (5) - Select mux mode: ALT5 mux port: GPIO[21] of instance: gpio4.
    HW_IOMUXC_SW_MUX_CTL_PAD_FEC_TX_CLK_WR(
            BF_IOMUXC_SW_MUX_CTL_PAD_FEC_TX_CLK_SION(SION_DISABLED) | 
            BF_IOMUXC_SW_MUX_CTL_PAD_FEC_TX_CLK_MUX_MODE(ALT5));
    // Pad Control Register:
    // IOMUXC_SW_PAD_CTL_PAD_FEC_TX_CLK(0x020E0434)
    //   LVE [22] - Low Voltage Enable Field Reset: LVE_DISABLED
    //              Select one out of next values for pad: FEC_TX_CLK.
    //     LVE_DISABLED (0) - High Voltage
    //     LVE_ENABLED (1) - Low Voltage
    //   HYS [16] - Hysteresis Enable Field Reset: HYS_ENABLED
    //              Select one out of next values for pad: FEC_TX_CLK.
    //     HYS_DISABLED (0) - Hysteresis Disabled
    //     HYS_ENABLED (1) - Hysteresis Enabled
    //   PUS [15:14] - Pull Up / Down Configure Field Reset: PUS_100KOHM_PD
    //                 Select one out of next values for pad: FEC_TX_CLK.
    //     PUS_100KOHM_PD (0) - 100K Ohm Pull Down
    //     PUS_47KOHM_PU (1) - 47K Ohm Pull Up
    //     PUS_100KOHM_PU (2) - 100K Ohm Pull Up
    //     PUS_22KOHM_PU (3) - 22K Ohm Pull Up
    //   PUE [13] - Pull / Keep Select Field Reset: PUE_KEEP
    //              Select one out of next values for pad: FEC_TX_CLK.
    //     PUE_KEEP (0) - Keeper
    //     PUE_PULL (1) - Pull
    //   PKE [12] - Pull / Keep Enable Field Reset: PKE_ENABLED
    //              Select one out of next values for pad: FEC_TX_CLK.
    //     PKE_DISABLED (0) - Pull/Keeper Disabled
    //     PKE_ENABLED (1) - Pull/Keeper Enabled
    //   ODE [11] - Open Drain Enable Field Reset: ODE_DISABLED
    //              Select one out of next values for pad: FEC_TX_CLK.
    //     ODE_DISABLED (0) - Open Drain Disabled
    //     ODE_ENABLED (1) - Open Drain Enabled
    //   SPEED [7:6] - Speed Field Reset: SPD_100MHZ
    //                 Select one out of next values for pad: FEC_TX_CLK.
    //     SPD_TBD (0) - TBD
    //     SPD_50MHZ (1) - Low(50 MHz)
    //     SPD_100MHZ (2) - Medium(100 MHz)
    //     SPD_200MHZ (3) - Maximum(200 MHz)
    //   DSE [5:3] - Drive Strength Field Reset: DSE_40OHM
    //               Select one out of next values for pad: FEC_TX_CLK.
    //     DSE_DISABLED (0) - Output driver disabled.
    //     DSE_240OHM (1) - 240 Ohm
    //     DSE_120OHM (2) - 120 Ohm
    //     DSE_80OHM (3) - 80 Ohm
    //     DSE_60OHM (4) - 60 Ohm
    //     DSE_48OHM (5) - 48 Ohm
    //     DSE_40OHM (6) - 40 Ohm
    //     DSE_34OHM (7) - 34 Ohm
    //   SRE [0] - Slew Rate Field Reset: SRE_SLOW
    //             Select one out of next values for pad: FEC_TX_CLK.
    //     SRE_SLOW (0) - Slow Slew Rate
    //     SRE_FAST (1) - Fast Slew Rate
    HW_IOMUXC_SW_PAD_CTL_PAD_FEC_TX_CLK_WR(
            BF_IOMUXC_SW_PAD_CTL_PAD_FEC_TX_CLK_LVE(LVE_DISABLED) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_FEC_TX_CLK_HYS(HYS_ENABLED) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_FEC_TX_CLK_PUS(PUS_100KOHM_PD) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_FEC_TX_CLK_PUE(PUE_KEEP) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_FEC_TX_CLK_PKE(PKE_ENABLED) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_FEC_TX_CLK_ODE(ODE_DISABLED) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_FEC_TX_CLK_SPEED(SPD_100MHZ) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_FEC_TX_CLK_DSE(DSE_40OHM) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_FEC_TX_CLK_SRE(SRE_SLOW));

    // Config fec.GPIO[19] to pad FEC_RX_ER(AD9)
    // Configure FEC_RX_ERR pad to gpio to avoid RX CRC error.This is the rework of hardware issue; WAS Instance:gpio4 Signal:GPIO[19]
    // HW_IOMUXC_SW_MUX_CTL_PAD_FEC_RX_ER_WR(0x00000005);
    // HW_IOMUXC_SW_PAD_CTL_PAD_FEC_RX_ER_WR(0x000110B0);
    // Mux Register:
    // IOMUXC_SW_MUX_CTL_PAD_FEC_RX_ER(0x020E0138)
    //   SION [4] - Software Input On Field Reset: SION_DISABLED
    //              Force the selected mux mode Input path no matter of MUX_MODE functionality.
    //     SION_DISABLED (0) - Input Path is determined by functionality of the selected mux mode (regular).
    //     SION_ENABLED (1) - Force input path of pad FEC_RX_ER.
    //   MUX_MODE [2:0] - MUX Mode Select Field Reset: ALT5
    //                    Select 1 of 8 iomux modes to be used for pad: FEC_RX_ER.
    //     ALT5 (5) - Select mux mode: ALT5 mux port: GPIO[19] of instance: gpio4.
    //     ALT0 (0) - Select mux mode: ALT0 mux port: RX_ER of instance: fec.
    //                NOTE: - Config Register IOMUXC_FEC_FEC_RX_ER_SELECT_INPUT for mode ALT0.
    //     ALT1 (1) - Select mux mode: ALT1 mux port: DAT0 of instance: usdhc4.
    //                NOTE: - Config Register IOMUXC_USDHC4_IPP_DAT0_IN_SELECT_INPUT for mode ALT1.
    //     ALT2 (2) - Select mux mode: ALT2 mux port: AUD6_RXD of instance: audmux.
    //                NOTE: - Config Register IOMUXC_AUDMUX_P6_INPUT_DA_AMX_SELECT_INPUT for mode ALT2.
    //     ALT3 (3) - Select mux mode: ALT3 mux port: MOSI of instance: ecspi4.
    //                NOTE: - Config Register IOMUXC_ECSPI4_IPP_IND_MOSI_SELECT_INPUT for mode ALT3.
    //     ALT4 (4) - Select mux mode: ALT4 mux port: CMPOUT1 of instance: gpt.
    HW_IOMUXC_SW_MUX_CTL_PAD_FEC_RX_ER_WR(
            BF_IOMUXC_SW_MUX_CTL_PAD_FEC_RX_ER_SION(SION_DISABLED) | 
            BF_IOMUXC_SW_MUX_CTL_PAD_FEC_RX_ER_MUX_MODE(ALT5));
    // Pad Control Register:
    // IOMUXC_SW_PAD_CTL_PAD_FEC_RX_ER(0x020E0428)
    //   LVE [22] - Low Voltage Enable Field Reset: LVE_DISABLED
    //              Select one out of next values for pad: FEC_RX_ER.
    //     LVE_DISABLED (0) - High Voltage
    //     LVE_ENABLED (1) - Low Voltage
    //   HYS [16] - Hysteresis Enable Field Reset: HYS_ENABLED
    //              Select one out of next values for pad: FEC_RX_ER.
    //     HYS_DISABLED (0) - Hysteresis Disabled
    //     HYS_ENABLED (1) - Hysteresis Enabled
    //   PUS [15:14] - Pull Up / Down Configure Field Reset: PUS_100KOHM_PD
    //                 Select one out of next values for pad: FEC_RX_ER.
    //     PUS_100KOHM_PD (0) - 100K Ohm Pull Down
    //     PUS_47KOHM_PU (1) - 47K Ohm Pull Up
    //     PUS_100KOHM_PU (2) - 100K Ohm Pull Up
    //     PUS_22KOHM_PU (3) - 22K Ohm Pull Up
    //   PUE [13] - Pull / Keep Select Field Reset: PUE_KEEP
    //              Select one out of next values for pad: FEC_RX_ER.
    //     PUE_KEEP (0) - Keeper
    //     PUE_PULL (1) - Pull
    //   PKE [12] - Pull / Keep Enable Field Reset: PKE_ENABLED
    //              Select one out of next values for pad: FEC_RX_ER.
    //     PKE_DISABLED (0) - Pull/Keeper Disabled
    //     PKE_ENABLED (1) - Pull/Keeper Enabled
    //   ODE [11] - Open Drain Enable Field Reset: ODE_DISABLED
    //              Select one out of next values for pad: FEC_RX_ER.
    //     ODE_DISABLED (0) - Open Drain Disabled
    //     ODE_ENABLED (1) - Open Drain Enabled
    //   SPEED [7:6] - Speed Field Reset: SPD_100MHZ
    //                 Select one out of next values for pad: FEC_RX_ER.
    //     SPD_TBD (0) - TBD
    //     SPD_50MHZ (1) - Low(50 MHz)
    //     SPD_100MHZ (2) - Medium(100 MHz)
    //     SPD_200MHZ (3) - Maximum(200 MHz)
    //   DSE [5:3] - Drive Strength Field Reset: DSE_40OHM
    //               Select one out of next values for pad: FEC_RX_ER.
    //     DSE_DISABLED (0) - Output driver disabled.
    //     DSE_240OHM (1) - 240 Ohm
    //     DSE_120OHM (2) - 120 Ohm
    //     DSE_80OHM (3) - 80 Ohm
    //     DSE_60OHM (4) - 60 Ohm
    //     DSE_48OHM (5) - 48 Ohm
    //     DSE_40OHM (6) - 40 Ohm
    //     DSE_34OHM (7) - 34 Ohm
    //   SRE [0] - Slew Rate Field Reset: SRE_SLOW
    //             Select one out of next values for pad: FEC_RX_ER.
    //     SRE_SLOW (0) - Slow Slew Rate
    //     SRE_FAST (1) - Fast Slew Rate
    HW_IOMUXC_SW_PAD_CTL_PAD_FEC_RX_ER_WR(
            BF_IOMUXC_SW_PAD_CTL_PAD_FEC_RX_ER_LVE(LVE_DISABLED) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_FEC_RX_ER_HYS(HYS_ENABLED) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_FEC_RX_ER_PUS(PUS_100KOHM_PD) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_FEC_RX_ER_PUE(PUE_KEEP) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_FEC_RX_ER_PKE(PKE_ENABLED) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_FEC_RX_ER_ODE(ODE_DISABLED) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_FEC_RX_ER_SPEED(SPD_100MHZ) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_FEC_RX_ER_DSE(DSE_40OHM) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_FEC_RX_ER_SRE(SRE_SLOW));
}
