/*
 * Copyright (C) 2012, Freescale Semiconductor, Inc. All Rights Reserved
 * THIS SOURCE CODE IS CONFIDENTIAL AND PROPRIETARY AND MAY NOT
 * BE USED OR DISTRIBUTED WITHOUT THE WRITTEN PERMISSION OF
 * Freescale Semiconductor, Inc.
*/

// File: kpp_iomux_config.c

/* ------------------------------------------------------------------------------
 * <auto-generated>
 *     This code was generated by a tool.
 *     Runtime Version:3.3.2.0
 *
 *     Changes to this file may cause incorrect behavior and will be lost if
 *     the code is regenerated.
 * </auto-generated>
 * ------------------------------------------------------------------------------
*/

#include "iomux_config.h"
#include "iomux_define.h"
#include "registers/regsiomuxc.h"

// Function to configure IOMUXC for kpp module.
void kpp_iomux_config(void)
{
    // Config kpp.COL[5] to pad SD2_CLK(C21)
    // HW_IOMUXC_SW_MUX_CTL_PAD_SD2_CLK_WR(0x00000012);
    // HW_IOMUXC_KPP_IPP_IND_COL_5_SELECT_INPUT_WR(0x00000003);
    // HW_IOMUXC_SW_PAD_CTL_PAD_SD2_CLK_WR(0x000170B0);
    // Mux Register:
    // IOMUXC_SW_MUX_CTL_PAD_SD2_CLK(0x020E0354)
    //   SION (4) - Software Input On Field Reset: SION_DISABLED
    //              Force the selected mux mode Input path no matter of MUX_MODE functionality.
    //     SION_DISABLED (0) - Input Path is determined by functionality of the selected mux mode (regular).
    //     SION_ENABLED (1) - Force input path of pad SD2_CLK.
    //   MUX_MODE (2-0) - MUX Mode Select Field Reset: ALT5
    //                    Select 1 of 8 iomux modes to be used for pad: SD2_CLK.
    //     ALT0 (0) - Select mux mode: ALT0 mux port: CLK of instance: usdhc2.
    //     ALT1 (1) - Select mux mode: ALT1 mux port: SCLK of instance: ecspi5.
    //                NOTE: - Config Register IOMUXC_ECSPI5_IPP_CSPI_CLK_IN_SELECT_INPUT for mode ALT1.
    //     ALT2 (2) - Select mux mode: ALT2 mux port: COL[5] of instance: kpp.
    //                NOTE: - Config Register IOMUXC_KPP_IPP_IND_COL_5_SELECT_INPUT for mode ALT2.
    //     ALT3 (3) - Select mux mode: ALT3 mux port: AUD4_RXFS of instance: audmux.
    //                NOTE: - Config Register IOMUXC_AUDMUX_P4_INPUT_RXFS_AMX_SELECT_INPUT for mode ALT3.
    //     ALT4 (4) - Select mux mode: ALT4 mux port: DIAG_STATUS_BUS_MUX[9] of instance: pcie_ctrl.
    //     ALT5 (5) - Select mux mode: ALT5 mux port: GPIO[10] of instance: gpio1.
    //     ALT6 (6) - Select mux mode: ALT6 mux port: DTB[1] of instance: phy.
    //     ALT7 (7) - Select mux mode: ALT7 mux port: DTB[1] of instance: sata_phy.
    HW_IOMUXC_SW_MUX_CTL_PAD_SD2_CLK_WR(
            BF_IOMUXC_SW_MUX_CTL_PAD_SD2_CLK_SION(SION_ENABLED) | 
            BF_IOMUXC_SW_MUX_CTL_PAD_SD2_CLK_MUX_MODE(ALT2));
    // Pad SD2_CLK is involved in Daisy Chain.
    // Input Select Register:
    // IOMUXC_KPP_IPP_IND_COL_5_SELECT_INPUT(0x020E08E8)
    //   DAISY (1-0) Reset: SEL_GPIO_0_ALT2
    //                 Selecting Pads Involved in Daisy Chain.
    //                 NOTE: Instance: kpp, In Pin: ipp_ind_col[5]
    //     SEL_GPIO_0_ALT2 (0) - Selecting Pad: GPIO_0 for Mode: ALT2.
    //     SEL_GPIO_19_ALT0 (1) - Selecting Pad: GPIO_19 for Mode: ALT0.
    //     SEL_CSI0_DAT4_ALT3 (2) - Selecting Pad: CSI0_DAT4 for Mode: ALT3.
    //     SEL_SD2_CLK_ALT2 (3) - Selecting Pad: SD2_CLK for Mode: ALT2.
    HW_IOMUXC_KPP_IPP_IND_COL_5_SELECT_INPUT_WR(
            BF_IOMUXC_KPP_IPP_IND_COL_5_SELECT_INPUT_DAISY(SEL_SD2_CLK_ALT2));
    // Pad Control Register:
    // IOMUXC_SW_PAD_CTL_PAD_SD2_CLK(0x020E073C)
    //   HYS (16) - Hysteresis Enable Field Reset: HYS_ENABLED
    //              Select one out of next values for pad: SD2_CLK.
    //     HYS_DISABLED (0) - Hysteresis Disabled
    //     HYS_ENABLED (1) - Hysteresis Enabled
    //   PUS (15-14) - Pull Up / Down Config. Field Reset: PUS_100KOHM_PU
    //                 Select one out of next values for pad: SD2_CLK.
    //     PUS_100KOHM_PD (0) - 100K Ohm Pull Down
    //     PUS_47KOHM_PU (1) - 47K Ohm Pull Up
    //     PUS_100KOHM_PU (2) - 100K Ohm Pull Up
    //     PUS_22KOHM_PU (3) - 22K Ohm Pull Up
    //   PUE (13) - Pull / Keep Select Field Reset: PUE_PULL
    //              Select one out of next values for pad: SD2_CLK.
    //     PUE_KEEP (0) - Keeper
    //     PUE_PULL (1) - Pull
    //   PKE (12) - Pull / Keep Enable Field Reset: PKE_ENABLED
    //              Select one out of next values for pad: SD2_CLK.
    //     PKE_DISABLED (0) - Pull/Keeper Disabled
    //     PKE_ENABLED (1) - Pull/Keeper Enabled
    //   ODE (11) - Open Drain Enable Field Reset: ODE_DISABLED
    //              Select one out of next values for pad: SD2_CLK.
    //     ODE_DISABLED (0) - Open Drain Disabled
    //     ODE_ENABLED (1) - Open Drain Enabled
    //   SPEED (7-6) - Speed Field Reset: SPD_100MHZ
    //                 Select one out of next values for pad: SD2_CLK.
    //     SPD_TBD (0) - TBD
    //     SPD_50MHZ (1) - Low(50 MHz)
    //     SPD_100MHZ (2) - Medium(100 MHz)
    //     SPD_200MHZ (3) - Maximum(200 MHz)
    //   DSE (5-3) - Drive Strength Field Reset: DSE_40OHM
    //               Select one out of next values for pad: SD2_CLK.
    //     DSE_DISABLED (0) - Output driver disabled.
    //     DSE_240OHM (1) - 240 Ohm
    //     DSE_120OHM (2) - 120 Ohm
    //     DSE_80OHM (3) - 80 Ohm
    //     DSE_60OHM (4) - 60 Ohm
    //     DSE_48OHM (5) - 48 Ohm
    //     DSE_40OHM (6) - 40 Ohm
    //     DSE_34OHM (7) - 34 Ohm
    //   SRE (0) - Slew Rate Field Reset: SRE_SLOW
    //             Select one out of next values for pad: SD2_CLK.
    //     SRE_SLOW (0) - Slow Slew Rate
    //     SRE_FAST (1) - Fast Slew Rate
    HW_IOMUXC_SW_PAD_CTL_PAD_SD2_CLK_WR(
            BF_IOMUXC_SW_PAD_CTL_PAD_SD2_CLK_HYS(HYS_ENABLED) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_SD2_CLK_PUS(PUS_47KOHM_PU) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_SD2_CLK_PUE(PUE_PULL) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_SD2_CLK_PKE(PKE_ENABLED) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_SD2_CLK_ODE(ODE_DISABLED) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_SD2_CLK_SPEED(SPD_100MHZ) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_SD2_CLK_DSE(DSE_40OHM) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_SD2_CLK_SRE(SRE_SLOW));

    // Config kpp.COL[6] to pad SD2_DAT3(B22)
    // HW_IOMUXC_SW_MUX_CTL_PAD_SD2_DAT3_WR(0x00000012);
    // HW_IOMUXC_KPP_IPP_IND_COL_6_SELECT_INPUT_WR(0x00000002);
    // HW_IOMUXC_SW_PAD_CTL_PAD_SD2_DAT3_WR(0x000170B0);
    // Mux Register:
    // IOMUXC_SW_MUX_CTL_PAD_SD2_DAT3(0x020E035C)
    //   SION (4) - Software Input On Field Reset: SION_DISABLED
    //              Force the selected mux mode Input path no matter of MUX_MODE functionality.
    //     SION_DISABLED (0) - Input Path is determined by functionality of the selected mux mode (regular).
    //     SION_ENABLED (1) - Force input path of pad SD2_DAT3.
    //   MUX_MODE (2-0) - MUX Mode Select Field Reset: ALT5
    //                    Select 1 of 8 iomux modes to be used for pad: SD2_DAT3.
    //     ALT0 (0) - Select mux mode: ALT0 mux port: DAT3 of instance: usdhc2.
    //     ALT1 (1) - Select mux mode: ALT1 mux port: SS3 of instance: ecspi5.
    //     ALT2 (2) - Select mux mode: ALT2 mux port: COL[6] of instance: kpp.
    //                NOTE: - Config Register IOMUXC_KPP_IPP_IND_COL_6_SELECT_INPUT for mode ALT2.
    //     ALT3 (3) - Select mux mode: ALT3 mux port: AUD4_TXC of instance: audmux.
    //                NOTE: - Config Register IOMUXC_AUDMUX_P4_INPUT_TXCLK_AMX_SELECT_INPUT for mode ALT3.
    //     ALT4 (4) - Select mux mode: ALT4 mux port: DIAG_STATUS_BUS_MUX[11] of instance: pcie_ctrl.
    //     ALT5 (5) - Select mux mode: ALT5 mux port: GPIO[12] of instance: gpio1.
    //     ALT6 (6) - Select mux mode: ALT6 mux port: DONE of instance: sjc.
    //     ALT7 (7) - Select mux mode: ALT7 mux port: ANATOP_TESTO[3] of instance: anatop.
    HW_IOMUXC_SW_MUX_CTL_PAD_SD2_DAT3_WR(
            BF_IOMUXC_SW_MUX_CTL_PAD_SD2_DAT3_SION(SION_ENABLED) | 
            BF_IOMUXC_SW_MUX_CTL_PAD_SD2_DAT3_MUX_MODE(ALT2));
    // Pad SD2_DAT3 is involved in Daisy Chain.
    // Input Select Register:
    // IOMUXC_KPP_IPP_IND_COL_6_SELECT_INPUT(0x020E08EC)
    //   DAISY (1-0) Reset: SEL_GPIO_9_ALT2
    //                 Selecting Pads Involved in Daisy Chain.
    //                 NOTE: Instance: kpp, In Pin: ipp_ind_col[6]
    //     SEL_GPIO_9_ALT2 (0) - Selecting Pad: GPIO_9 for Mode: ALT2.
    //     SEL_CSI0_DAT6_ALT3 (1) - Selecting Pad: CSI0_DAT6 for Mode: ALT3.
    //     SEL_SD2_DAT3_ALT2 (2) - Selecting Pad: SD2_DAT3 for Mode: ALT2.
    HW_IOMUXC_KPP_IPP_IND_COL_6_SELECT_INPUT_WR(
            BF_IOMUXC_KPP_IPP_IND_COL_6_SELECT_INPUT_DAISY(SEL_SD2_DAT3_ALT2));
    // Pad Control Register:
    // IOMUXC_SW_PAD_CTL_PAD_SD2_DAT3(0x020E0744)
    //   HYS (16) - Hysteresis Enable Field Reset: HYS_ENABLED
    //              Select one out of next values for pad: SD2_DAT3.
    //     HYS_DISABLED (0) - Hysteresis Disabled
    //     HYS_ENABLED (1) - Hysteresis Enabled
    //   PUS (15-14) - Pull Up / Down Config. Field Reset: PUS_100KOHM_PU
    //                 Select one out of next values for pad: SD2_DAT3.
    //     PUS_100KOHM_PD (0) - 100K Ohm Pull Down
    //     PUS_47KOHM_PU (1) - 47K Ohm Pull Up
    //     PUS_100KOHM_PU (2) - 100K Ohm Pull Up
    //     PUS_22KOHM_PU (3) - 22K Ohm Pull Up
    //   PUE (13) - Pull / Keep Select Field Reset: PUE_PULL
    //              Select one out of next values for pad: SD2_DAT3.
    //     PUE_KEEP (0) - Keeper
    //     PUE_PULL (1) - Pull
    //   PKE (12) - Pull / Keep Enable Field Reset: PKE_ENABLED
    //              Select one out of next values for pad: SD2_DAT3.
    //     PKE_DISABLED (0) - Pull/Keeper Disabled
    //     PKE_ENABLED (1) - Pull/Keeper Enabled
    //   ODE (11) - Open Drain Enable Field Reset: ODE_DISABLED
    //              Select one out of next values for pad: SD2_DAT3.
    //     ODE_DISABLED (0) - Open Drain Disabled
    //     ODE_ENABLED (1) - Open Drain Enabled
    //   SPEED (7-6) - Speed Field Reset: SPD_100MHZ
    //                 Select one out of next values for pad: SD2_DAT3.
    //     SPD_TBD (0) - TBD
    //     SPD_50MHZ (1) - Low(50 MHz)
    //     SPD_100MHZ (2) - Medium(100 MHz)
    //     SPD_200MHZ (3) - Maximum(200 MHz)
    //   DSE (5-3) - Drive Strength Field Reset: DSE_40OHM
    //               Select one out of next values for pad: SD2_DAT3.
    //     DSE_DISABLED (0) - Output driver disabled.
    //     DSE_240OHM (1) - 240 Ohm
    //     DSE_120OHM (2) - 120 Ohm
    //     DSE_80OHM (3) - 80 Ohm
    //     DSE_60OHM (4) - 60 Ohm
    //     DSE_48OHM (5) - 48 Ohm
    //     DSE_40OHM (6) - 40 Ohm
    //     DSE_34OHM (7) - 34 Ohm
    //   SRE (0) - Slew Rate Field Reset: SRE_SLOW
    //             Select one out of next values for pad: SD2_DAT3.
    //     SRE_SLOW (0) - Slow Slew Rate
    //     SRE_FAST (1) - Fast Slew Rate
    HW_IOMUXC_SW_PAD_CTL_PAD_SD2_DAT3_WR(
            BF_IOMUXC_SW_PAD_CTL_PAD_SD2_DAT3_HYS(HYS_ENABLED) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_SD2_DAT3_PUS(PUS_47KOHM_PU) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_SD2_DAT3_PUE(PUE_PULL) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_SD2_DAT3_PKE(PKE_ENABLED) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_SD2_DAT3_ODE(ODE_DISABLED) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_SD2_DAT3_SPEED(SPD_100MHZ) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_SD2_DAT3_DSE(DSE_40OHM) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_SD2_DAT3_SRE(SRE_SLOW));

    // Config kpp.COL[7] to pad SD2_DAT1(E20)
    // HW_IOMUXC_SW_MUX_CTL_PAD_SD2_DAT1_WR(0x00000014);
    // HW_IOMUXC_KPP_IPP_IND_COL_7_SELECT_INPUT_WR(0x00000000);
    // HW_IOMUXC_SW_PAD_CTL_PAD_SD2_DAT1_WR(0x000170B0);
    // Mux Register:
    // IOMUXC_SW_MUX_CTL_PAD_SD2_DAT1(0x020E004C)
    //   SION (4) - Software Input On Field Reset: SION_DISABLED
    //              Force the selected mux mode Input path no matter of MUX_MODE functionality.
    //     SION_DISABLED (0) - Input Path is determined by functionality of the selected mux mode (regular).
    //     SION_ENABLED (1) - Force input path of pad SD2_DAT1.
    //   MUX_MODE (2-0) - MUX Mode Select Field Reset: ALT5
    //                    Select 1 of 8 iomux modes to be used for pad: SD2_DAT1.
    //     ALT0 (0) - Select mux mode: ALT0 mux port: DAT1 of instance: usdhc2.
    //     ALT1 (1) - Select mux mode: ALT1 mux port: SS0 of instance: ecspi5.
    //                NOTE: - Config Register IOMUXC_ECSPI5_IPP_IND_SS_B_0_SELECT_INPUT for mode ALT1.
    //     ALT2 (2) - Select mux mode: ALT2 mux port: WEIM_CS[2] of instance: weim.
    //     ALT3 (3) - Select mux mode: ALT3 mux port: AUD4_TXFS of instance: audmux.
    //                NOTE: - Config Register IOMUXC_AUDMUX_P4_INPUT_TXFS_AMX_SELECT_INPUT for mode ALT3.
    //     ALT4 (4) - Select mux mode: ALT4 mux port: COL[7] of instance: kpp.
    //                NOTE: - Config Register IOMUXC_KPP_IPP_IND_COL_7_SELECT_INPUT for mode ALT4.
    //     ALT5 (5) - Select mux mode: ALT5 mux port: GPIO[14] of instance: gpio1.
    //     ALT6 (6) - Select mux mode: ALT6 mux port: WAIT of instance: ccm.
    //     ALT7 (7) - Select mux mode: ALT7 mux port: ANATOP_TESTO[0] of instance: anatop.
    HW_IOMUXC_SW_MUX_CTL_PAD_SD2_DAT1_WR(
            BF_IOMUXC_SW_MUX_CTL_PAD_SD2_DAT1_SION(SION_ENABLED) | 
            BF_IOMUXC_SW_MUX_CTL_PAD_SD2_DAT1_MUX_MODE(ALT4));
    // Pad SD2_DAT1 is involved in Daisy Chain.
    // Input Select Register:
    // IOMUXC_KPP_IPP_IND_COL_7_SELECT_INPUT(0x020E08F0)
    //   DAISY (1-0) Reset: SEL_SD2_DAT1_ALT4
    //                 Selecting Pads Involved in Daisy Chain.
    //                 NOTE: Instance: kpp, In Pin: ipp_ind_col[7]
    //     SEL_SD2_DAT1_ALT4 (0) - Selecting Pad: SD2_DAT1 for Mode: ALT4.
    //     SEL_GPIO_4_ALT2 (1) - Selecting Pad: GPIO_4 for Mode: ALT2.
    //     SEL_CSI0_DAT8_ALT3 (2) - Selecting Pad: CSI0_DAT8 for Mode: ALT3.
    HW_IOMUXC_KPP_IPP_IND_COL_7_SELECT_INPUT_WR(
            BF_IOMUXC_KPP_IPP_IND_COL_7_SELECT_INPUT_DAISY(SEL_SD2_DAT1_ALT4));
    // Pad Control Register:
    // IOMUXC_SW_PAD_CTL_PAD_SD2_DAT1(0x020E0360)
    //   HYS (16) - Hysteresis Enable Field Reset: HYS_ENABLED
    //              Select one out of next values for pad: SD2_DAT1.
    //     HYS_DISABLED (0) - Hysteresis Disabled
    //     HYS_ENABLED (1) - Hysteresis Enabled
    //   PUS (15-14) - Pull Up / Down Config. Field Reset: PUS_100KOHM_PU
    //                 Select one out of next values for pad: SD2_DAT1.
    //     PUS_100KOHM_PD (0) - 100K Ohm Pull Down
    //     PUS_47KOHM_PU (1) - 47K Ohm Pull Up
    //     PUS_100KOHM_PU (2) - 100K Ohm Pull Up
    //     PUS_22KOHM_PU (3) - 22K Ohm Pull Up
    //   PUE (13) - Pull / Keep Select Field Reset: PUE_PULL
    //              Select one out of next values for pad: SD2_DAT1.
    //     PUE_KEEP (0) - Keeper
    //     PUE_PULL (1) - Pull
    //   PKE (12) - Pull / Keep Enable Field Reset: PKE_ENABLED
    //              Select one out of next values for pad: SD2_DAT1.
    //     PKE_DISABLED (0) - Pull/Keeper Disabled
    //     PKE_ENABLED (1) - Pull/Keeper Enabled
    //   ODE (11) - Open Drain Enable Field Reset: ODE_DISABLED
    //              Select one out of next values for pad: SD2_DAT1.
    //     ODE_DISABLED (0) - Open Drain Disabled
    //     ODE_ENABLED (1) - Open Drain Enabled
    //   SPEED (7-6) - Speed Field Reset: SPD_100MHZ
    //                 Select one out of next values for pad: SD2_DAT1.
    //     SPD_TBD (0) - TBD
    //     SPD_50MHZ (1) - Low(50 MHz)
    //     SPD_100MHZ (2) - Medium(100 MHz)
    //     SPD_200MHZ (3) - Maximum(200 MHz)
    //   DSE (5-3) - Drive Strength Field Reset: DSE_40OHM
    //               Select one out of next values for pad: SD2_DAT1.
    //     DSE_DISABLED (0) - Output driver disabled.
    //     DSE_240OHM (1) - 240 Ohm
    //     DSE_120OHM (2) - 120 Ohm
    //     DSE_80OHM (3) - 80 Ohm
    //     DSE_60OHM (4) - 60 Ohm
    //     DSE_48OHM (5) - 48 Ohm
    //     DSE_40OHM (6) - 40 Ohm
    //     DSE_34OHM (7) - 34 Ohm
    //   SRE (0) - Slew Rate Field Reset: SRE_SLOW
    //             Select one out of next values for pad: SD2_DAT1.
    //     SRE_SLOW (0) - Slow Slew Rate
    //     SRE_FAST (1) - Fast Slew Rate
    HW_IOMUXC_SW_PAD_CTL_PAD_SD2_DAT1_WR(
            BF_IOMUXC_SW_PAD_CTL_PAD_SD2_DAT1_HYS(HYS_ENABLED) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_SD2_DAT1_PUS(PUS_47KOHM_PU) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_SD2_DAT1_PUE(PUE_PULL) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_SD2_DAT1_PKE(PKE_ENABLED) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_SD2_DAT1_ODE(ODE_DISABLED) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_SD2_DAT1_SPEED(SPD_100MHZ) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_SD2_DAT1_DSE(DSE_40OHM) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_SD2_DAT1_SRE(SRE_SLOW));

    // Config kpp.ROW[5] to pad SD2_CMD(F19)
    // HW_IOMUXC_SW_MUX_CTL_PAD_SD2_CMD_WR(0x00000012);
    // HW_IOMUXC_KPP_IPP_IND_ROW_5_SELECT_INPUT_WR(0x00000002);
    // HW_IOMUXC_SW_PAD_CTL_PAD_SD2_CMD_WR(0x0001F0B0);
    // Mux Register:
    // IOMUXC_SW_MUX_CTL_PAD_SD2_CMD(0x020E0358)
    //   SION (4) - Software Input On Field Reset: SION_DISABLED
    //              Force the selected mux mode Input path no matter of MUX_MODE functionality.
    //     SION_DISABLED (0) - Input Path is determined by functionality of the selected mux mode (regular).
    //     SION_ENABLED (1) - Force input path of pad SD2_CMD.
    //   MUX_MODE (2-0) - MUX Mode Select Field Reset: ALT5
    //                    Select 1 of 6 iomux modes to be used for pad: SD2_CMD.
    //     ALT0 (0) - Select mux mode: ALT0 mux port: CMD of instance: usdhc2.
    //     ALT1 (1) - Select mux mode: ALT1 mux port: MOSI of instance: ecspi5.
    //                NOTE: - Config Register IOMUXC_ECSPI5_IPP_IND_MOSI_SELECT_INPUT for mode ALT1.
    //     ALT2 (2) - Select mux mode: ALT2 mux port: ROW[5] of instance: kpp.
    //                NOTE: - Config Register IOMUXC_KPP_IPP_IND_ROW_5_SELECT_INPUT for mode ALT2.
    //     ALT3 (3) - Select mux mode: ALT3 mux port: AUD4_RXC of instance: audmux.
    //                NOTE: - Config Register IOMUXC_AUDMUX_P4_INPUT_RXCLK_AMX_SELECT_INPUT for mode ALT3.
    //     ALT4 (4) - Select mux mode: ALT4 mux port: DIAG_STATUS_BUS_MUX[10] of instance: pcie_ctrl.
    //     ALT5 (5) - Select mux mode: ALT5 mux port: GPIO[11] of instance: gpio1.
    HW_IOMUXC_SW_MUX_CTL_PAD_SD2_CMD_WR(
            BF_IOMUXC_SW_MUX_CTL_PAD_SD2_CMD_SION(SION_ENABLED) | 
            BF_IOMUXC_SW_MUX_CTL_PAD_SD2_CMD_MUX_MODE(ALT2));
    // Pad SD2_CMD is involved in Daisy Chain.
    // Input Select Register:
    // IOMUXC_KPP_IPP_IND_ROW_5_SELECT_INPUT(0x020E08F4)
    //   DAISY (1-0) Reset: SEL_GPIO_1_ALT2
    //                 Selecting Pads Involved in Daisy Chain.
    //                 NOTE: Instance: kpp, In Pin: ipp_ind_row[5]
    //     SEL_GPIO_1_ALT2 (0) - Selecting Pad: GPIO_1 for Mode: ALT2.
    //     SEL_CSI0_DAT5_ALT3 (1) - Selecting Pad: CSI0_DAT5 for Mode: ALT3.
    //     SEL_SD2_CMD_ALT2 (2) - Selecting Pad: SD2_CMD for Mode: ALT2.
    HW_IOMUXC_KPP_IPP_IND_ROW_5_SELECT_INPUT_WR(
            BF_IOMUXC_KPP_IPP_IND_ROW_5_SELECT_INPUT_DAISY(SEL_SD2_CMD_ALT2));
    // Pad Control Register:
    // IOMUXC_SW_PAD_CTL_PAD_SD2_CMD(0x020E0740)
    //   HYS (16) - Hysteresis Enable Field Reset: HYS_ENABLED
    //              Select one out of next values for pad: SD2_CMD.
    //     HYS_DISABLED (0) - Hysteresis Disabled
    //     HYS_ENABLED (1) - Hysteresis Enabled
    //   PUS (15-14) - Pull Up / Down Config. Field Reset: PUS_100KOHM_PU
    //                 Select one out of next values for pad: SD2_CMD.
    //     PUS_100KOHM_PD (0) - 100K Ohm Pull Down
    //     PUS_47KOHM_PU (1) - 47K Ohm Pull Up
    //     PUS_100KOHM_PU (2) - 100K Ohm Pull Up
    //     PUS_22KOHM_PU (3) - 22K Ohm Pull Up
    //   PUE (13) - Pull / Keep Select Field Reset: PUE_PULL
    //              Select one out of next values for pad: SD2_CMD.
    //     PUE_KEEP (0) - Keeper
    //     PUE_PULL (1) - Pull
    //   PKE (12) - Pull / Keep Enable Field Reset: PKE_ENABLED
    //              Select one out of next values for pad: SD2_CMD.
    //     PKE_DISABLED (0) - Pull/Keeper Disabled
    //     PKE_ENABLED (1) - Pull/Keeper Enabled
    //   ODE (11) - Open Drain Enable Field Reset: ODE_DISABLED
    //              Select one out of next values for pad: SD2_CMD.
    //     ODE_DISABLED (0) - Open Drain Disabled
    //     ODE_ENABLED (1) - Open Drain Enabled
    //   SPEED (7-6) - Speed Field Reset: SPD_100MHZ
    //                 Select one out of next values for pad: SD2_CMD.
    //     SPD_TBD (0) - TBD
    //     SPD_50MHZ (1) - Low(50 MHz)
    //     SPD_100MHZ (2) - Medium(100 MHz)
    //     SPD_200MHZ (3) - Maximum(200 MHz)
    //   DSE (5-3) - Drive Strength Field Reset: DSE_40OHM
    //               Select one out of next values for pad: SD2_CMD.
    //     DSE_DISABLED (0) - Output driver disabled.
    //     DSE_240OHM (1) - 240 Ohm
    //     DSE_120OHM (2) - 120 Ohm
    //     DSE_80OHM (3) - 80 Ohm
    //     DSE_60OHM (4) - 60 Ohm
    //     DSE_48OHM (5) - 48 Ohm
    //     DSE_40OHM (6) - 40 Ohm
    //     DSE_34OHM (7) - 34 Ohm
    //   SRE (0) - Slew Rate Field Reset: SRE_SLOW
    //             Select one out of next values for pad: SD2_CMD.
    //     SRE_SLOW (0) - Slow Slew Rate
    //     SRE_FAST (1) - Fast Slew Rate
    HW_IOMUXC_SW_PAD_CTL_PAD_SD2_CMD_WR(
            BF_IOMUXC_SW_PAD_CTL_PAD_SD2_CMD_HYS(HYS_ENABLED) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_SD2_CMD_PUS(PUS_22KOHM_PU) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_SD2_CMD_PUE(PUE_PULL) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_SD2_CMD_PKE(PKE_ENABLED) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_SD2_CMD_ODE(ODE_DISABLED) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_SD2_CMD_SPEED(SPD_100MHZ) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_SD2_CMD_DSE(DSE_40OHM) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_SD2_CMD_SRE(SRE_SLOW));

    // Config kpp.ROW[6] to pad SD2_DAT2(A23)
    // HW_IOMUXC_SW_MUX_CTL_PAD_SD2_DAT2_WR(0x00000014);
    // HW_IOMUXC_KPP_IPP_IND_ROW_6_SELECT_INPUT_WR(0x00000000);
    // HW_IOMUXC_SW_PAD_CTL_PAD_SD2_DAT2_WR(0x0001F0B0);
    // Mux Register:
    // IOMUXC_SW_MUX_CTL_PAD_SD2_DAT2(0x020E0050)
    //   SION (4) - Software Input On Field Reset: SION_DISABLED
    //              Force the selected mux mode Input path no matter of MUX_MODE functionality.
    //     SION_DISABLED (0) - Input Path is determined by functionality of the selected mux mode (regular).
    //     SION_ENABLED (1) - Force input path of pad SD2_DAT2.
    //   MUX_MODE (2-0) - MUX Mode Select Field Reset: ALT5
    //                    Select 1 of 8 iomux modes to be used for pad: SD2_DAT2.
    //     ALT0 (0) - Select mux mode: ALT0 mux port: DAT2 of instance: usdhc2.
    //     ALT1 (1) - Select mux mode: ALT1 mux port: SS1 of instance: ecspi5.
    //                NOTE: - Config Register IOMUXC_ECSPI5_IPP_IND_SS_B_1_SELECT_INPUT for mode ALT1.
    //     ALT2 (2) - Select mux mode: ALT2 mux port: WEIM_CS[3] of instance: weim.
    //     ALT3 (3) - Select mux mode: ALT3 mux port: AUD4_TXD of instance: audmux.
    //                NOTE: - Config Register IOMUXC_AUDMUX_P4_INPUT_DB_AMX_SELECT_INPUT for mode ALT3.
    //     ALT4 (4) - Select mux mode: ALT4 mux port: ROW[6] of instance: kpp.
    //                NOTE: - Config Register IOMUXC_KPP_IPP_IND_ROW_6_SELECT_INPUT for mode ALT4.
    //     ALT5 (5) - Select mux mode: ALT5 mux port: GPIO[13] of instance: gpio1.
    //     ALT6 (6) - Select mux mode: ALT6 mux port: STOP of instance: ccm.
    //     ALT7 (7) - Select mux mode: ALT7 mux port: ANATOP_TESTO[1] of instance: anatop.
    HW_IOMUXC_SW_MUX_CTL_PAD_SD2_DAT2_WR(
            BF_IOMUXC_SW_MUX_CTL_PAD_SD2_DAT2_SION(SION_ENABLED) | 
            BF_IOMUXC_SW_MUX_CTL_PAD_SD2_DAT2_MUX_MODE(ALT4));
    // Pad SD2_DAT2 is involved in Daisy Chain.
    // Input Select Register:
    // IOMUXC_KPP_IPP_IND_ROW_6_SELECT_INPUT(0x020E08F8)
    //   DAISY (1-0) Reset: SEL_SD2_DAT2_ALT4
    //                 Selecting Pads Involved in Daisy Chain.
    //                 NOTE: Instance: kpp, In Pin: ipp_ind_row[6]
    //     SEL_SD2_DAT2_ALT4 (0) - Selecting Pad: SD2_DAT2 for Mode: ALT4.
    //     SEL_GPIO_2_ALT2 (1) - Selecting Pad: GPIO_2 for Mode: ALT2.
    //     SEL_CSI0_DAT7_ALT3 (2) - Selecting Pad: CSI0_DAT7 for Mode: ALT3.
    HW_IOMUXC_KPP_IPP_IND_ROW_6_SELECT_INPUT_WR(
            BF_IOMUXC_KPP_IPP_IND_ROW_6_SELECT_INPUT_DAISY(SEL_SD2_DAT2_ALT4));
    // Pad Control Register:
    // IOMUXC_SW_PAD_CTL_PAD_SD2_DAT2(0x020E0364)
    //   HYS (16) - Hysteresis Enable Field Reset: HYS_ENABLED
    //              Select one out of next values for pad: SD2_DAT2.
    //     HYS_DISABLED (0) - Hysteresis Disabled
    //     HYS_ENABLED (1) - Hysteresis Enabled
    //   PUS (15-14) - Pull Up / Down Config. Field Reset: PUS_100KOHM_PU
    //                 Select one out of next values for pad: SD2_DAT2.
    //     PUS_100KOHM_PD (0) - 100K Ohm Pull Down
    //     PUS_47KOHM_PU (1) - 47K Ohm Pull Up
    //     PUS_100KOHM_PU (2) - 100K Ohm Pull Up
    //     PUS_22KOHM_PU (3) - 22K Ohm Pull Up
    //   PUE (13) - Pull / Keep Select Field Reset: PUE_PULL
    //              Select one out of next values for pad: SD2_DAT2.
    //     PUE_KEEP (0) - Keeper
    //     PUE_PULL (1) - Pull
    //   PKE (12) - Pull / Keep Enable Field Reset: PKE_ENABLED
    //              Select one out of next values for pad: SD2_DAT2.
    //     PKE_DISABLED (0) - Pull/Keeper Disabled
    //     PKE_ENABLED (1) - Pull/Keeper Enabled
    //   ODE (11) - Open Drain Enable Field Reset: ODE_DISABLED
    //              Select one out of next values for pad: SD2_DAT2.
    //     ODE_DISABLED (0) - Open Drain Disabled
    //     ODE_ENABLED (1) - Open Drain Enabled
    //   SPEED (7-6) - Speed Field Reset: SPD_100MHZ
    //                 Select one out of next values for pad: SD2_DAT2.
    //     SPD_TBD (0) - TBD
    //     SPD_50MHZ (1) - Low(50 MHz)
    //     SPD_100MHZ (2) - Medium(100 MHz)
    //     SPD_200MHZ (3) - Maximum(200 MHz)
    //   DSE (5-3) - Drive Strength Field Reset: DSE_40OHM
    //               Select one out of next values for pad: SD2_DAT2.
    //     DSE_DISABLED (0) - Output driver disabled.
    //     DSE_240OHM (1) - 240 Ohm
    //     DSE_120OHM (2) - 120 Ohm
    //     DSE_80OHM (3) - 80 Ohm
    //     DSE_60OHM (4) - 60 Ohm
    //     DSE_48OHM (5) - 48 Ohm
    //     DSE_40OHM (6) - 40 Ohm
    //     DSE_34OHM (7) - 34 Ohm
    //   SRE (0) - Slew Rate Field Reset: SRE_SLOW
    //             Select one out of next values for pad: SD2_DAT2.
    //     SRE_SLOW (0) - Slow Slew Rate
    //     SRE_FAST (1) - Fast Slew Rate
    HW_IOMUXC_SW_PAD_CTL_PAD_SD2_DAT2_WR(
            BF_IOMUXC_SW_PAD_CTL_PAD_SD2_DAT2_HYS(HYS_ENABLED) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_SD2_DAT2_PUS(PUS_22KOHM_PU) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_SD2_DAT2_PUE(PUE_PULL) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_SD2_DAT2_PKE(PKE_ENABLED) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_SD2_DAT2_ODE(ODE_DISABLED) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_SD2_DAT2_SPEED(SPD_100MHZ) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_SD2_DAT2_DSE(DSE_40OHM) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_SD2_DAT2_SRE(SRE_SLOW));

    // Config kpp.ROW[7] to pad SD2_DAT0(A22)
    // HW_IOMUXC_SW_MUX_CTL_PAD_SD2_DAT0_WR(0x00000014);
    // HW_IOMUXC_KPP_IPP_IND_ROW_7_SELECT_INPUT_WR(0x00000000);
    // HW_IOMUXC_SW_PAD_CTL_PAD_SD2_DAT0_WR(0x0001F0B0);
    // Mux Register:
    // IOMUXC_SW_MUX_CTL_PAD_SD2_DAT0(0x020E0054)
    //   SION (4) - Software Input On Field Reset: SION_DISABLED
    //              Force the selected mux mode Input path no matter of MUX_MODE functionality.
    //     SION_DISABLED (0) - Input Path is determined by functionality of the selected mux mode (regular).
    //     SION_ENABLED (1) - Force input path of pad SD2_DAT0.
    //   MUX_MODE (2-0) - MUX Mode Select Field Reset: ALT5
    //                    Select 1 of 7 iomux modes to be used for pad: SD2_DAT0.
    //     ALT0 (0) - Select mux mode: ALT0 mux port: DAT0 of instance: usdhc2.
    //     ALT1 (1) - Select mux mode: ALT1 mux port: MISO of instance: ecspi5.
    //                NOTE: - Config Register IOMUXC_ECSPI5_IPP_IND_MISO_SELECT_INPUT for mode ALT1.
    //     ALT3 (3) - Select mux mode: ALT3 mux port: AUD4_RXD of instance: audmux.
    //                NOTE: - Config Register IOMUXC_AUDMUX_P4_INPUT_DA_AMX_SELECT_INPUT for mode ALT3.
    //     ALT4 (4) - Select mux mode: ALT4 mux port: ROW[7] of instance: kpp.
    //                NOTE: - Config Register IOMUXC_KPP_IPP_IND_ROW_7_SELECT_INPUT for mode ALT4.
    //     ALT5 (5) - Select mux mode: ALT5 mux port: GPIO[15] of instance: gpio1.
    //     ALT6 (6) - Select mux mode: ALT6 mux port: DCIC_OUT of instance: dcic2.
    //     ALT7 (7) - Select mux mode: ALT7 mux port: ANATOP_TESTO[2] of instance: anatop.
    HW_IOMUXC_SW_MUX_CTL_PAD_SD2_DAT0_WR(
            BF_IOMUXC_SW_MUX_CTL_PAD_SD2_DAT0_SION(SION_ENABLED) | 
            BF_IOMUXC_SW_MUX_CTL_PAD_SD2_DAT0_MUX_MODE(ALT4));
    // Pad SD2_DAT0 is involved in Daisy Chain.
    // Input Select Register:
    // IOMUXC_KPP_IPP_IND_ROW_7_SELECT_INPUT(0x020E08FC)
    //   DAISY (1-0) Reset: SEL_SD2_DAT0_ALT4
    //                 Selecting Pads Involved in Daisy Chain.
    //                 NOTE: Instance: kpp, In Pin: ipp_ind_row[7]
    //     SEL_SD2_DAT0_ALT4 (0) - Selecting Pad: SD2_DAT0 for Mode: ALT4.
    //     SEL_GPIO_5_ALT2 (1) - Selecting Pad: GPIO_5 for Mode: ALT2.
    //     SEL_CSI0_DAT9_ALT3 (2) - Selecting Pad: CSI0_DAT9 for Mode: ALT3.
    HW_IOMUXC_KPP_IPP_IND_ROW_7_SELECT_INPUT_WR(
            BF_IOMUXC_KPP_IPP_IND_ROW_7_SELECT_INPUT_DAISY(SEL_SD2_DAT0_ALT4));
    // Pad Control Register:
    // IOMUXC_SW_PAD_CTL_PAD_SD2_DAT0(0x020E0368)
    //   HYS (16) - Hysteresis Enable Field Reset: HYS_ENABLED
    //              Select one out of next values for pad: SD2_DAT0.
    //     HYS_DISABLED (0) - Hysteresis Disabled
    //     HYS_ENABLED (1) - Hysteresis Enabled
    //   PUS (15-14) - Pull Up / Down Config. Field Reset: PUS_100KOHM_PU
    //                 Select one out of next values for pad: SD2_DAT0.
    //     PUS_100KOHM_PD (0) - 100K Ohm Pull Down
    //     PUS_47KOHM_PU (1) - 47K Ohm Pull Up
    //     PUS_100KOHM_PU (2) - 100K Ohm Pull Up
    //     PUS_22KOHM_PU (3) - 22K Ohm Pull Up
    //   PUE (13) - Pull / Keep Select Field Reset: PUE_PULL
    //              Select one out of next values for pad: SD2_DAT0.
    //     PUE_KEEP (0) - Keeper
    //     PUE_PULL (1) - Pull
    //   PKE (12) - Pull / Keep Enable Field Reset: PKE_ENABLED
    //              Select one out of next values for pad: SD2_DAT0.
    //     PKE_DISABLED (0) - Pull/Keeper Disabled
    //     PKE_ENABLED (1) - Pull/Keeper Enabled
    //   ODE (11) - Open Drain Enable Field Reset: ODE_DISABLED
    //              Select one out of next values for pad: SD2_DAT0.
    //     ODE_DISABLED (0) - Open Drain Disabled
    //     ODE_ENABLED (1) - Open Drain Enabled
    //   SPEED (7-6) - Speed Field Reset: SPD_100MHZ
    //                 Select one out of next values for pad: SD2_DAT0.
    //     SPD_TBD (0) - TBD
    //     SPD_50MHZ (1) - Low(50 MHz)
    //     SPD_100MHZ (2) - Medium(100 MHz)
    //     SPD_200MHZ (3) - Maximum(200 MHz)
    //   DSE (5-3) - Drive Strength Field Reset: DSE_40OHM
    //               Select one out of next values for pad: SD2_DAT0.
    //     DSE_DISABLED (0) - Output driver disabled.
    //     DSE_240OHM (1) - 240 Ohm
    //     DSE_120OHM (2) - 120 Ohm
    //     DSE_80OHM (3) - 80 Ohm
    //     DSE_60OHM (4) - 60 Ohm
    //     DSE_48OHM (5) - 48 Ohm
    //     DSE_40OHM (6) - 40 Ohm
    //     DSE_34OHM (7) - 34 Ohm
    //   SRE (0) - Slew Rate Field Reset: SRE_SLOW
    //             Select one out of next values for pad: SD2_DAT0.
    //     SRE_SLOW (0) - Slow Slew Rate
    //     SRE_FAST (1) - Fast Slew Rate
    HW_IOMUXC_SW_PAD_CTL_PAD_SD2_DAT0_WR(
            BF_IOMUXC_SW_PAD_CTL_PAD_SD2_DAT0_HYS(HYS_ENABLED) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_SD2_DAT0_PUS(PUS_22KOHM_PU) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_SD2_DAT0_PUE(PUE_PULL) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_SD2_DAT0_PKE(PKE_ENABLED) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_SD2_DAT0_ODE(ODE_DISABLED) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_SD2_DAT0_SPEED(SPD_100MHZ) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_SD2_DAT0_DSE(DSE_40OHM) | 
            BF_IOMUXC_SW_PAD_CTL_PAD_SD2_DAT0_SRE(SRE_SLOW));
}
