include $(SDK_ROOT)/mk/common.mk


C_SOURCES = \
	cache_wrappers.c \
	fsclearbuf.c \
	fsdriveinit.c \
	fsdriveshutdown.c \
	fsinit.c \
	fsrecoverdrive.c \
	fsshutdown.c \
	setcwdhandle.c



include $(SDK_ROOT)/mk/targets.mk
