/*
 * Copyright (C) 2012, Freescale Semiconductor, Inc. All Rights Reserved.
 * THIS SOURCE CODE IS CONFIDENTIAL AND PROPRIETARY AND MAY NOT
 * BE USED OR DISTRIBUTED WITHOUT THE WRITTEN PERMISSION OF
 * Freescale Semiconductor, Inc.
*/

// File: iomux_define.h

#ifndef _IOMUX_DEFINE_H_
#define _IOMUX_DEFINE_H_

// IOMUXC_SW_MUX_CTL_PAD_*
// SION
#define SION_DISABLED 0x0
#define SION_ENABLED  0x1
// MUX_MODE
#define ALT0 0x0
#define ALT1 0x1
#define ALT2 0x2
#define ALT3 0x3
#define ALT4 0x4
#define ALT5 0x5
#define ALT6 0x6
#define ALT7 0x7

// IOMUXC_SW_PAD_CTL_PAD_*
// IOMUXC_SW_PAD_CTL_GRP_*
// HVE
#define HVE_RES0 0x0
#define HVE_RES1 0x1
// TEST_TS
#define TEST_TS_DISABLED 0x0
#define TEST_TS_ENABLED  0x1
// DSE_TEST
#define DSE_TEST_NORMAL 0x0
#define DSE_TEST_TEST   0x1
// STRENGTH_MODE
#define STRENGTH_MODE_RES0       0x0
#define STRENGTH_MODE_FOUR_LEVEL 0x1
// HYS
#define HYS_DISABLED 0x0
#define HYS_ENABLED  0x1
// PUS
#define PUS_100KOHM_PD 0x0
#define PUS_360KOHM_PD 0x0
#define PUS_75KOHM_PU  0x1
#define PUS_47KOHM_PU  0x1
#define PUS_100KOHM_PU 0x2
#define PUS_22KOHM_PU  0x3
// PUE
#define PUE_KEEP 0x0
#define PUE_PULL 0x1
// PKE
#define PKE_DISABLED 0x0
#define PKE_ENABLED  0x1
// ODE
#define ODE_DISABLED 0x0
#define ODE_ENABLED  0x1
// DSE
#define DSE_DISABLED 0x0
#define DSE_240OHM   0x1
#define DSE_120OHM   0x2
#define DSE_80OHM    0x3
#define DSE_60OHM    0x4
#define DSE_48OHM    0x5
#define DSE_40OHM    0x6
#define DSE_34OHM    0x7
// SRE
#define SRE_SLOW 0x0
#define SRE_FAST 0x1
// ODT
#define ODT_OFF    0x0
#define ODT_120OHM 0x1
#define ODT_60OHM  0x2
#define ODT_40OHM  0x3
#define ODT_30OHM  0x4
#define ODT_RES5   0x5
#define ODT_20OHM  0x6
#define ODT_RES7   0x7
// DDR_INPUT
#define DDR_INPUT_CMOS 0x0
#define DDR_INPUT_DIFF 0x1
// DDR_SEL
#define DDR_SEL_RES0   0x0
#define DDR_SEL_RES1   0x1
#define DDR_SEL_LPDDR2 0x3
#define DDR_SEL_DDR3   0x4

// IOMUXC_AUDMUX_P4_INPUT_DA_AMX_SELECT_INPUT
// DAISY
#define SEL_DISP0_DAT23_ALT3 0x0
#define SEL_SD2_DATA0_ALT3   0x1

// IOMUXC_AUDMUX_P4_INPUT_DB_AMX_SELECT_INPUT
// DAISY
#define SEL_DISP0_DAT21_ALT3 0x0
#define SEL_SD2_DATA2_ALT3   0x1

// IOMUXC_AUDMUX_P4_INPUT_RXCLK_AMX_SELECT_INPUT
// DAISY
#define SEL_DISP0_DAT19_ALT4 0x0
#define SEL_SD2_CMD_ALT3     0x1

// IOMUXC_AUDMUX_P4_INPUT_RXFS_AMX_SELECT_INPUT
// DAISY
#define SEL_DISP0_DAT18_ALT4 0x0
#define SEL_SD2_CLK_ALT3     0x1

// IOMUXC_AUDMUX_P4_INPUT_TXCLK_AMX_SELECT_INPUT
// DAISY
#define SEL_DISP0_DAT20_ALT3 0x0
#define SEL_SD2_DATA3_ALT3   0x1

// IOMUXC_AUDMUX_P4_INPUT_TXFS_AMX_SELECT_INPUT
// DAISY
#define SEL_DISP0_DAT22_ALT3 0x0
#define SEL_SD2_DATA1_ALT3   0x1

// IOMUXC_AUDMUX_P5_INPUT_DA_AMX_SELECT_INPUT
// DAISY
#define SEL_KEY_ROW1_ALT2    0x0
#define SEL_DISP0_DAT19_ALT3 0x1

// IOMUXC_AUDMUX_P5_INPUT_DB_AMX_SELECT_INPUT
// DAISY
#define SEL_KEY_ROW0_ALT2    0x0
#define SEL_DISP0_DAT17_ALT3 0x1

// IOMUXC_AUDMUX_P5_INPUT_RXCLK_AMX_SELECT_INPUT
// DAISY
#define SEL_DISP0_DAT14_ALT3 0x0
#define SEL_EIM_D25_ALT5     0x1

// IOMUXC_AUDMUX_P5_INPUT_RXFS_AMX_SELECT_INPUT
// DAISY
#define SEL_DISP0_DAT13_ALT3 0x0
#define SEL_EIM_D24_ALT5     0x1

// IOMUXC_AUDMUX_P5_INPUT_TXCLK_AMX_SELECT_INPUT
// DAISY
#define SEL_KEY_COL0_ALT2    0x0
#define SEL_DISP0_DAT16_ALT3 0x1

// IOMUXC_AUDMUX_P5_INPUT_TXFS_AMX_SELECT_INPUT
// DAISY
#define SEL_KEY_COL1_ALT2    0x0
#define SEL_DISP0_DAT18_ALT3 0x1

// IOMUXC_CAN1_IPP_IND_CANRX_SELECT_INPUT
// DAISY
#define SEL_KEY_ROW2_ALT2  0x0
#define SEL_PATA_DIOR_ALT4 0x1
#define SEL_GPIO_8_ALT3    0x2

// IOMUXC_CAN2_IPP_IND_CANRX_SELECT_INPUT
// DAISY
#define SEL_KEY_ROW4_ALT2   0x0
#define SEL_PATA_IORDY_ALT4 0x1

// IOMUXC_CCM_IPP_ASRC_EXT_SELECT_INPUT
// DAISY
#define SEL_KEY_ROW3_ALT3 0x0
#define SEL_GPIO_18_ALT5  0x1

// IOMUXC_CCM_IPP_DI1_CLK_SELECT_INPUT
// DAISY
#define SEL_EIM_EB2_ALT2  0x0
#define SEL_EIM_DA13_ALT4 0x1

// IOMUXC_CCM_PLL1_BYPASS_CLK_SELECT_INPUT
// DAISY
#define SEL_SD1_CMD_ALT7 0x0
#define SEL_GPIO_5_ALT7  0x1

// IOMUXC_CCM_PLL2_BYPASS_CLK_SELECT_INPUT
// DAISY
#define SEL_SD1_DATA2_ALT7 0x0
#define SEL_GPIO_7_ALT7    0x1

// IOMUXC_CCM_PLL3_BYPASS_CLK_SELECT_INPUT
// DAISY
#define SEL_SD1_DATA0_ALT7 0x0
#define SEL_GPIO_8_ALT7    0x1

// IOMUXC_CCM_PLL4_BYPASS_CLK_SELECT_INPUT
// DAISY
#define SEL_KEY_ROW3_ALT6  0x0
#define SEL_SD1_DATA1_ALT7 0x1

// IOMUXC_CSPI_IPP_CSPI_CLK_IN_SELECT_INPUT
// DAISY
#define SEL_DISP0_DAT0_ALT2 0x0
#define SEL_EIM_D21_ALT4    0x1
#define SEL_SD1_CLK_ALT5    0x2
#define SEL_SD2_CLK_ALT5    0x3

// IOMUXC_CSPI_IPP_IND_MISO_SELECT_INPUT
// DAISY
#define SEL_DISP0_DAT2_ALT2 0x0
#define SEL_EIM_D22_ALT4    0x1
#define SEL_SD1_DATA0_ALT5  0x2
#define SEL_SD2_DATA0_ALT5  0x3

// IOMUXC_CSPI_IPP_IND_MOSI_SELECT_INPUT
// DAISY
#define SEL_DISP0_DAT1_ALT2 0x0
#define SEL_EIM_D28_ALT4    0x1
#define SEL_SD1_CMD_ALT5    0x2
#define SEL_SD2_CMD_ALT5    0x3

// IOMUXC_CSPI_IPP_IND_SS0_B_SELECT_INPUT
// DAISY
#define SEL_DISP0_DAT3_ALT2 0x0
#define SEL_EIM_D20_ALT4    0x1
#define SEL_EIM_D29_ALT4    0x2
#define SEL_SD1_DATA1_ALT5  0x3
#define SEL_SD2_DATA1_ALT5  0x4

// IOMUXC_CSPI_IPP_IND_SS1_B_SELECT_INPUT
// DAISY
#define SEL_DISP0_DAT4_ALT2 0x0
#define SEL_EIM_A25_ALT4    0x1
#define SEL_SD1_DATA2_ALT5  0x2
#define SEL_SD2_DATA2_ALT5  0x3

// IOMUXC_CSPI_IPP_IND_SS2_B_SELECT_INPUT
// DAISY
#define SEL_DISP0_DAT5_ALT2 0x0
#define SEL_EIM_D24_ALT4    0x1
#define SEL_SD1_DATA3_ALT5  0x2
#define SEL_SD2_DATA3_ALT5  0x3

// IOMUXC_CSPI_IPP_IND_SS3_B_SELECT_INPUT
// DAISY
#define SEL_DISP0_DAT6_ALT2 0x0
#define SEL_EIM_D25_ALT4    0x1

// IOMUXC_ECSPI1_IPP_CSPI_CLK_IN_SELECT_INPUT
// DAISY
#define SEL_KEY_COL0_ALT5    0x0
#define SEL_DISP0_DAT20_ALT2 0x1
#define SEL_CSI0_DAT4_ALT3   0x2
#define SEL_EIM_D16_ALT4     0x3

// IOMUXC_ECSPI1_IPP_IND_MISO_SELECT_INPUT
// DAISY
#define SEL_KEY_COL1_ALT5    0x0
#define SEL_DISP0_DAT22_ALT2 0x1
#define SEL_CSI0_DAT6_ALT3   0x2
#define SEL_EIM_D17_ALT4     0x3

// IOMUXC_ECSPI1_IPP_IND_MOSI_SELECT_INPUT
// DAISY
#define SEL_KEY_ROW0_ALT5    0x0
#define SEL_DISP0_DAT21_ALT2 0x1
#define SEL_CSI0_DAT5_ALT3   0x2
#define SEL_EIM_D18_ALT4     0x3

// IOMUXC_ECSPI1_IPP_IND_SS_B_0_SELECT_INPUT
// DAISY
#define SEL_KEY_ROW1_ALT5    0x0
#define SEL_DISP0_DAT23_ALT2 0x1
#define SEL_CSI0_DAT7_ALT3   0x2
#define SEL_EIM_EB2_ALT4     0x3

// IOMUXC_ECSPI1_IPP_IND_SS_B_1_SELECT_INPUT
// DAISY
#define SEL_KEY_COL2_ALT5    0x0
#define SEL_DISP0_DAT15_ALT2 0x1
#define SEL_EIM_D19_ALT4     0x2

// IOMUXC_ECSPI1_IPP_IND_SS_B_2_SELECT_INPUT
// DAISY
#define SEL_KEY_ROW2_ALT5 0x0
#define SEL_EIM_D24_ALT3  0x1

// IOMUXC_ECSPI1_IPP_IND_SS_B_3_SELECT_INPUT
// DAISY
#define SEL_KEY_COL3_ALT5 0x0
#define SEL_EIM_D25_ALT3  0x1

// IOMUXC_ECSPI2_IPP_CSPI_CLK_IN_SELECT_INPUT
// DAISY
#define SEL_DISP0_DAT19_ALT2 0x0
#define SEL_CSI0_DAT8_ALT3   0x1
#define SEL_EIM_CS0_ALT2     0x2

// IOMUXC_ECSPI2_IPP_IND_MISO_SELECT_INPUT
// DAISY
#define SEL_DISP0_DAT17_ALT2 0x0
#define SEL_CSI0_DAT10_ALT3  0x1
#define SEL_EIM_OE_ALT2      0x2

// IOMUXC_ECSPI2_IPP_IND_MOSI_SELECT_INPUT
// DAISY
#define SEL_DISP0_DAT16_ALT2 0x0
#define SEL_CSI0_DAT9_ALT3   0x1
#define SEL_EIM_CS1_ALT2     0x2

// IOMUXC_ECSPI2_IPP_IND_SS_B_0_SELECT_INPUT
// DAISY
#define SEL_DISP0_DAT18_ALT2 0x0
#define SEL_CSI0_DAT11_ALT3  0x1
#define SEL_EIM_RW_ALT2      0x2

// IOMUXC_ECSPI2_IPP_IND_SS_B_1_SELECT_INPUT
// DAISY
#define SEL_DISP0_DAT15_ALT3 0x0
#define SEL_EIM_LBA_ALT2     0x1

// IOMUXC_ESAI1_IPP_IND_FSR_SELECT_INPUT
// DAISY
#define SEL_FEC_REF_CLK_ALT2 0x0
#define SEL_GPIO_9_ALT0      0x1

// IOMUXC_ESAI1_IPP_IND_FST_SELECT_INPUT
// DAISY
#define SEL_FEC_RXD1_ALT2 0x0
#define SEL_GPIO_2_ALT0   0x1

// IOMUXC_ESAI1_IPP_IND_HCKR_SELECT_INPUT
// DAISY
#define SEL_FEC_RX_ER_ALT2 0x0
#define SEL_GPIO_3_ALT0    0x1

// IOMUXC_ESAI1_IPP_IND_HCKT_SELECT_INPUT
// DAISY
#define SEL_FEC_RXD0_ALT2 0x0
#define SEL_GPIO_4_ALT0   0x1

// IOMUXC_ESAI1_IPP_IND_SCKR_SELECT_INPUT
// DAISY
#define SEL_FEC_MDIO_ALT2 0x0
#define SEL_GPIO_1_ALT0   0x1

// IOMUXC_ESAI1_IPP_IND_SCKT_SELECT_INPUT
// DAISY
#define SEL_FEC_CRS_DV_ALT2 0x0
#define SEL_GPIO_6_ALT0     0x1

// IOMUXC_ESAI1_IPP_IND_SDO0_SELECT_INPUT
// DAISY
#define SEL_NANDF_CS2_ALT3 0x0
#define SEL_GPIO_17_ALT0   0x1

// IOMUXC_ESAI1_IPP_IND_SDO1_SELECT_INPUT
// DAISY
#define SEL_NANDF_CS3_ALT3 0x0
#define SEL_GPIO_18_ALT0   0x1

// IOMUXC_ESAI1_IPP_IND_SDO2_SDI3_SELECT_INPUT
// DAISY
#define SEL_FEC_TXD1_ALT2 0x0
#define SEL_GPIO_5_ALT0   0x1

// IOMUXC_ESAI1_IPP_IND_SDO3_SDI2_SELECT_INPUT
// DAISY
#define SEL_FEC_TX_EN_ALT2 0x0
#define SEL_GPIO_16_ALT0   0x1

// IOMUXC_ESAI1_IPP_IND_SDO4_SDI1_SELECT_INPUT
// DAISY
#define SEL_FEC_TXD0_ALT2 0x0
#define SEL_GPIO_7_ALT0   0x1

// IOMUXC_ESAI1_IPP_IND_SDO5_SDI0_SELECT_INPUT
// DAISY
#define SEL_FEC_MDC_ALT2 0x0
#define SEL_GPIO_8_ALT0  0x1

// IOMUXC_ESDHC1_IPP_WP_ON_SELECT_INPUT
// DAISY
#define SEL_DI0_PIN4_ALT3 0x0
#define SEL_GPIO_9_ALT6   0x1

// IOMUXC_FEC_FEC_COL_SELECT_INPUT
// DAISY
#define SEL_KEY_ROW1_ALT6 0x0
#define SEL_FEC_MDIO_ALT3 0x1

// IOMUXC_FEC_FEC_MDI_SELECT_INPUT
// DAISY
#define SEL_KEY_COL2_ALT4 0x0
#define SEL_FEC_MDIO_ALT0 0x1

// IOMUXC_FEC_FEC_RX_CLK_SELECT_INPUT
// DAISY
#define SEL_KEY_COL1_ALT6  0x0
#define SEL_FEC_RX_ER_ALT3 0x1

// IOMUXC_FIRI_IPP_IND_RXD_SELECT_INPUT
// DAISY
#define SEL_EIM_D26_ALT3 0x0
#define SEL_GPIO_7_ALT5  0x1

// IOMUXC_GPC_PMIC_RDY_SELECT_INPUT
// DAISY
#define SEL_EIM_EB0_ALT5 0x0
#define SEL_GPIO_17_ALT3 0x1

// IOMUXC_I2C1_IPP_SCL_IN_SELECT_INPUT
// DAISY
#define SEL_CSI0_DAT9_ALT5 0x0
#define SEL_EIM_D21_ALT5   0x1

// IOMUXC_I2C1_IPP_SDA_IN_SELECT_INPUT
// DAISY
#define SEL_CSI0_DAT8_ALT5 0x0
#define SEL_EIM_D28_ALT5   0x1

// IOMUXC_I2C2_IPP_SCL_IN_SELECT_INPUT
// DAISY
#define SEL_KEY_COL3_ALT4 0x0
#define SEL_EIM_EB2_ALT5  0x1

// IOMUXC_I2C2_IPP_SDA_IN_SELECT_INPUT
// DAISY
#define SEL_KEY_ROW3_ALT4 0x0
#define SEL_EIM_D16_ALT5  0x1

// IOMUXC_I2C3_IPP_SCL_IN_SELECT_INPUT
// DAISY
#define SEL_EIM_D17_ALT5 0x0
#define SEL_GPIO_3_ALT2  0x1
#define SEL_GPIO_5_ALT6  0x2

// IOMUXC_I2C3_IPP_SDA_IN_SELECT_INPUT
// DAISY
#define SEL_EIM_D18_ALT5 0x0
#define SEL_GPIO_6_ALT2  0x1
#define SEL_GPIO_16_ALT6 0x2

// IOMUXC_IPU_IPP_DI_0_IND_DISPB_SD_D_SELECT_INPUT
// DAISY
#define SEL_EIM_D22_ALT3 0x0
#define SEL_EIM_D28_ALT3 0x1

// IOMUXC_IPU_IPP_DI_1_IND_DISPB_SD_D_SELECT_INPUT
// DAISY
#define SEL_EIM_D17_ALT3 0x0
#define SEL_EIM_D18_ALT3 0x1

// IOMUXC_IPU_IPP_IND_SENS1_DATA_EN_SELECT_INPUT
// DAISY
#define SEL_EIM_D23_ALT6  0x0
#define SEL_EIM_DA10_ALT4 0x1

// IOMUXC_IPU_IPP_IND_SENS1_HSYNC_SELECT_INPUT
// DAISY
#define SEL_EIM_EB3_ALT6  0x0
#define SEL_EIM_DA11_ALT4 0x1

// IOMUXC_IPU_IPP_IND_SENS1_VSYNC_SELECT_INPUT
// DAISY
#define SEL_EIM_D29_ALT6  0x0
#define SEL_EIM_DA12_ALT4 0x1

// IOMUXC_KPP_IPP_IND_COL_5_SELECT_INPUT
// DAISY
#define SEL_GPIO_19_ALT0   0x0
#define SEL_CSI0_DAT4_ALT2 0x1
#define SEL_SD2_CLK_ALT2   0x2
#define SEL_GPIO_0_ALT2    0x3

// IOMUXC_KPP_IPP_IND_COL_6_SELECT_INPUT
// DAISY
#define SEL_CSI0_DAT6_ALT2 0x0
#define SEL_SD2_DATA3_ALT2 0x1
#define SEL_GPIO_9_ALT2    0x2

// IOMUXC_KPP_IPP_IND_COL_7_SELECT_INPUT
// DAISY
#define SEL_CSI0_DAT8_ALT2 0x0
#define SEL_SD2_DATA1_ALT2 0x1
#define SEL_GPIO_4_ALT2    0x2

// IOMUXC_KPP_IPP_IND_ROW_5_SELECT_INPUT
// DAISY
#define SEL_CSI0_DAT5_ALT2 0x0
#define SEL_SD2_CMD_ALT2   0x1
#define SEL_GPIO_1_ALT2    0x2

// IOMUXC_KPP_IPP_IND_ROW_6_SELECT_INPUT
// DAISY
#define SEL_CSI0_DAT7_ALT2 0x0
#define SEL_SD2_DATA2_ALT2 0x1
#define SEL_GPIO_2_ALT2    0x2

// IOMUXC_KPP_IPP_IND_ROW_7_SELECT_INPUT
// DAISY
#define SEL_CSI0_DAT9_ALT2 0x0
#define SEL_SD2_DATA0_ALT2 0x1
#define SEL_GPIO_5_ALT2    0x2

// IOMUXC_MLB_MLBCLK_IN_SELECT_INPUT
// DAISY
#define SEL_NANDF_CS1_ALT6 0x0
#define SEL_FEC_TXD1_ALT3  0x1
#define SEL_GPIO_3_ALT7    0x2

// IOMUXC_MLB_MLBDAT_IN_SELECT_INPUT
// DAISY
#define SEL_NANDF_CS3_ALT6 0x0
#define SEL_FEC_MDC_ALT3   0x1
#define SEL_GPIO_2_ALT7    0x2

// IOMUXC_MLB_MLBSIG_IN_SELECT_INPUT
// DAISY
#define SEL_NANDF_CS2_ALT6 0x0
#define SEL_FEC_RXD1_ALT3  0x1
#define SEL_GPIO_6_ALT7    0x2

// IOMUXC_OWIRE_BATTERY_LINE_IN_SELECT_INPUT
// DAISY
#define SEL_PATA_DA_0_ALT4 0x0
#define SEL_GPIO_18_ALT3   0x1

// IOMUXC_SDMA_EVENTS_14_SELECT_INPUT
// DAISY
#define SEL_DISP0_DAT16_ALT4 0x0
#define SEL_GPIO_17_ALT2     0x1

// IOMUXC_SDMA_EVENTS_15_SELECT_INPUT
// DAISY
#define SEL_DISP0_DAT17_ALT4 0x0
#define SEL_GPIO_18_ALT2     0x1

// IOMUXC_SPDIF_SPDIF_IN1_SELECT_INPUT
// DAISY
#define SEL_KEY_COL3_ALT3 0x0
#define SEL_GPIO_16_ALT5  0x1

// IOMUXC_UART1_IPP_UART_RTS_B_SELECT_INPUT
// DAISY
#define SEL_EIM_D19_ALT6      0x0
#define SEL_EIM_D20_ALT6      0x1
#define SEL_PATA_RESET_B_ALT3 0x2
#define SEL_PATA_IORDY_ALT3   0x3

// IOMUXC_UART1_IPP_UART_RXD_MUX_SELECT_INPUT
// DAISY
#define SEL_CSI0_DAT10_ALT2 0x0
#define SEL_CSI0_DAT11_ALT2 0x1
#define SEL_PATA_DIOW_ALT3  0x2
#define SEL_PATA_DMACK_ALT3 0x3

// IOMUXC_UART2_IPP_UART_RTS_B_SELECT_INPUT
// DAISY
#define SEL_EIM_D28_ALT2    0x0
#define SEL_EIM_D29_ALT2    0x1
#define SEL_PATA_INTRQ_ALT3 0x2
#define SEL_PATA_DIOR_ALT3  0x3

// IOMUXC_UART2_IPP_UART_RXD_MUX_SELECT_INPUT
// DAISY
#define SEL_EIM_D26_ALT2        0x0
#define SEL_EIM_D27_ALT2        0x1
#define SEL_PATA_DMARQ_ALT3     0x2
#define SEL_PATA_BUFFER_EN_ALT3 0x3
#define SEL_GPIO_7_ALT4         0x4
#define SEL_GPIO_8_ALT4         0x5

// IOMUXC_UART3_IPP_UART_RTS_B_SELECT_INPUT
// DAISY
#define SEL_EIM_D23_ALT2   0x0
#define SEL_EIM_EB3_ALT2   0x1
#define SEL_EIM_D30_ALT2   0x2
#define SEL_EIM_D31_ALT2   0x3
#define SEL_PATA_DA_1_ALT4 0x4
#define SEL_PATA_DA_2_ALT4 0x5

// IOMUXC_UART3_IPP_UART_RXD_MUX_SELECT_INPUT
// DAISY
#define SEL_EIM_D24_ALT2   0x0
#define SEL_EIM_D25_ALT2   0x1
#define SEL_PATA_CS_0_ALT4 0x2
#define SEL_PATA_CS_1_ALT4 0x3

// IOMUXC_UART4_IPP_UART_RTS_B_SELECT_INPUT
// DAISY
#define SEL_CSI0_DAT16_ALT2 0x0
#define SEL_CSI0_DAT17_ALT2 0x1

// IOMUXC_UART4_IPP_UART_RXD_MUX_SELECT_INPUT
// DAISY
#define SEL_KEY_COL0_ALT4   0x0
#define SEL_KEY_ROW0_ALT4   0x1
#define SEL_CSI0_DAT12_ALT2 0x2
#define SEL_CSI0_DAT13_ALT2 0x3

// IOMUXC_UART5_IPP_UART_RTS_B_SELECT_INPUT
// DAISY
#define SEL_KEY_COL4_ALT4   0x0
#define SEL_KEY_ROW4_ALT4   0x1
#define SEL_CSI0_DAT18_ALT2 0x2
#define SEL_CSI0_DAT19_ALT2 0x3

// IOMUXC_UART5_IPP_UART_RXD_MUX_SELECT_INPUT
// DAISY
#define SEL_KEY_COL1_ALT4   0x0
#define SEL_KEY_ROW1_ALT4   0x1
#define SEL_CSI0_DAT14_ALT2 0x2
#define SEL_CSI0_DAT15_ALT2 0x3

// IOMUXC_USBOH3_IPP_IND_OTG_OC_SELECT_INPUT
// DAISY
#define SEL_KEY_COL4_ALT5 0x0
#define SEL_EIM_D21_ALT6  0x1

// IOMUXC_USBOH3_IPP_IND_UH1_OC_SELECT_INPUT
// DAISY
#define SEL_EIM_D30_ALT6 0x0
#define SEL_GPIO_3_ALT6  0x1

// IOMUXC_USBOH3_IPP_IND_UH2_OC_SELECT_INPUT
// DAISY
#define SEL_EIM_D19_ALT7 0x0
#define SEL_EIM_D30_ALT7 0x1


#endif // _IOMUX_DEFINE_H_
