include $(SDK_ROOT)/mk/common.mk


SUBDIRS = \
		base \
		common \
		device \
		fatapi \
		handle \
		higherapi \
		platform \
		standardapi \
		unicode \
		utility



include $(SDK_ROOT)/mk/targets.mk
