/*
 * Copyright (C) 2012, Freescale Semiconductor, Inc. All Rights Reserved
 * THIS SOURCE CODE IS CONFIDENTIAL AND PROPRIETARY AND MAY NOT
 * BE USED OR DISTRIBUTED WITHOUT THE WRITTEN PERMISSION OF
 * Freescale Semiconductor, Inc.
*/

// File: iomux_config.h

/* ------------------------------------------------------------------------------
 * <auto-generated>
 *     This code was generated by a tool.
 *     Runtime Version:3.3.2.0
 *
 *     Changes to this file may cause incorrect behavior and will be lost if
 *     the code is regenerated.
 * </auto-generated>
 * ------------------------------------------------------------------------------
*/

#ifndef _IOMUX_CONFIG_H_
#define _IOMUX_CONFIG_H_

// Board and Module IOMUXC configuration function prototypes.

#if defined(__cplusplus)
extern "C" {
#endif

// Board IOMUXC configuration function.
void iomux_config(void);

// Module IOMUXC configuration functions.
void anatop_iomux_config(void);
void asrc_iomux_config(void);
void audmux_iomux_config(void);
void caam_wrapper_iomux_config(void);
void can1_iomux_config(void);
void can2_iomux_config(void);
void ccm_iomux_config(void);
void cheetah_iomux_config(void);
void csu_iomux_config(void);
void dcic1_iomux_config(void);
void dcic2_iomux_config(void);
void ecspi1_iomux_config(void);
void ecspi2_iomux_config(void);
void ecspi3_iomux_config(void);
void ecspi4_iomux_config(void);
void ecspi5_iomux_config(void);
void enet_iomux_config(void);
void epit1_iomux_config(void);
void epit2_iomux_config(void);
void esai_iomux_config(void);
void gpio1_iomux_config(void);
void gpio2_iomux_config(void);
void gpio3_iomux_config(void);
void gpio4_iomux_config(void);
void gpio5_iomux_config(void);
void gpio6_iomux_config(void);
void gpio7_iomux_config(void);
void gpt_iomux_config(void);
void gpu3d_iomux_config(void);
void hdmi_tx_iomux_config(void);
void i2c1_iomux_config(void);
void i2c2_iomux_config(void);
void i2c3_iomux_config(void);
void ipu1_iomux_config(void);
void ipu2_iomux_config(void);
void kpp_iomux_config(void);
void ldb_iomux_config(void);
void mipi_core_iomux_config(void);
void mipi_hsi_ctrl_iomux_config(void);
void mlb_iomux_config(void);
void mmdc_iomux_config(void);
void observe_mux_iomux_config(void);
void ocotp_ctrl_wrapper_iomux_config(void);
void osc32k_iomux_config(void);
void pcie_ctrl_iomux_config(void);
void phy_iomux_config(void);
void pl301_mx63per1_iomux_config(void);
void pwm1_iomux_config(void);
void pwm2_iomux_config(void);
void pwm3_iomux_config(void);
void pwm4_iomux_config(void);
void rawnand_iomux_config(void);
void sata_phy_iomux_config(void);
void sdma_iomux_config(void);
void sjc_iomux_config(void);
void snvs_hp_wrapper_iomux_config(void);
void snvs_lp_wrapper_iomux_config(void);
void spdif_iomux_config(void);
void src_iomux_config(void);
void tcu_iomux_config(void);
void tpsmp_iomux_config(void);
void uart1_iomux_config(void);
void uart2_iomux_config(void);
void uart3_iomux_config(void);
void uart4_iomux_config(void);
void uart5_iomux_config(void);
void usboh3_iomux_config(void);
void usdhc1_iomux_config(void);
void usdhc2_iomux_config(void);
void usdhc3_iomux_config(void);
void usdhc4_iomux_config(void);
void wdog1_iomux_config(void);
void wdog2_iomux_config(void);
void weim_iomux_config(void);

#if defined(__cplusplus)
}
#endif

#endif // _IOMUX_CONFIG_H_
