include $(SDK_ROOT)/mk/common.mk


# Export the target library name to all child make invocations.
TARGET_LIB_NAME = libsdk.a
export TARGET_LIB_NAME

SUBDIRS = common core utility mx6dq
# \
# 	common \
# 	utility \
# 	core \
# 	mx6dq



include $(SDK_ROOT)/mk/targets.mk
