#!/bin/bash
#
# release_sdk
#

script=$(basename $0)
script_full=$(which $0)
script_path=$(dirname $script_full)
clean_flag=n

usage()
{
    echo "Generate a release packgae for the SDK project."
    echo "Only files releavant for the platform specified as argument are copied to the release folder."
    echo
    echo "Usage: "
    echo "   $script [-target <mx6dq, mx53, ...>] [-board <evb, qsb, ard, smd, ...>]"
    echo "   Must be executed in the diag-sdk tree. "
    echo
    echo "For eg: 1. $script -target mx6dq -board evb"
    echo "        2. $script -target mx53 -board lcb"
    echo
    exit 1
}

if [ $# -lt 2 ]; then
    echo "Need to specify -target & -board as arguments"
    echo
    echo "$script:"
    usage
fi

if echo "$@"|egrep -sq '\-(h|H)'; then
    eval usage
fi

sdk_dir=$PWD

while [ ! -f tools/gen_release.pl -o ! -d src/init ]; do
    if [ "$sdk_dir" = / ]; then
        echo "Couldn't find root of SDK tree. Script must be executed from root of SDK tree"
        eval usage
    fi
    cd ..
    sdk_dir=$PWD
done

config_dir=$sdk_dir/configs
make_perl_script=$sdk_dir/tools/gen_make.pl
release_perl_script=$sdk_dir/tools/gen_release.pl

while [ $# -gt 0 ]; do
    case $1 in
    -target )   soc_name=$2
                shift
            ;;
    -board 	)   board_name=\_$2
                shift
            ;;

    * )     echo "Incorrect parameter: $1"
            echo
            echo "$script:"
            usage
            ;;
    esac
    shift
done

release_dir=$sdk_dir/imx_sdk_release/$soc_name$board_name\_sdk_release

echo "Generating Makefiles for $soc_name$board_name"
perl $make_perl_script $config_dir $sdk_dir $soc_name $board_name

if [ $? -eq 1 ]; then
    echo
    echo "Failed to run the gen_make perl script."
    echo "Please double check the -board & -target arguments passed in"
    echo
    echo "$script:"
    usage
    exit 1
fi

echo "Copying files to Release folder"
perl $release_perl_script $config_dir $sdk_dir $release_dir $soc_name $board_name

echo
echo "Done...Release folder created"
echo
echo "Generating doxygen documentation"

saved_curr_working_dir=$PWD
cd $release_dir
# Variable used in the doxygen title page, convert to upper case
export IMX_SOC_NAME=$(echo $soc_name |tr '[a-z]' '[A-Z]')
$sdk_dir/tools/doxygenate_sdk -sdk_dir $sdk_dir
cd $saved_curr_working_dir

echo "Done...Release ready in $release_dir folder"
echo
