#!/bin/sh
#
#       -npro, --ignore-profile
#           Do not read `.indent.pro´ files.
#
#       -kr, --k-and-r-style
#           Use Kernighan & Ritchie coding style.
#
#       -in, --indent-leveln
#           Set indentation level to n spaces.
#
#       -tsn, --tab-sizen
#           Set tab size to n spaces.
#
#       -sob, --swallow-optional-blank-lines
#           Swallow optional blank lines.
#
#       -ln, --line-lengthn
#           Set maximum line length for non-comment lines to n.
#
#       -ss, --space-special-semicolon
#           On one-line for and while statments, force a blank before the semicolon.
#
#       -ncs, --no-space-after-casts
#           Do not put a space after cast operators.
#
#       -nut, --no-tabs
#           Use spaces instead of tabs.
#
dos2unix "$@"
indent -npro -kr -i4 -ts4 -sob -l100 -ss -ncs -nut -cp1 "$@"

