include $(SDK_ROOT)/mk/common.mk


SOURCES = \
	src/abort_handler.c \
	src/ccm_pll.c \
	src/interrupt.c \
	src/mmu.c \
	src/cortexA9.s \
	src/startup.s \
	src/vectors.S


include $(SDK_ROOT)/mk/targets.mk
